Repository greenpeace/planet4-master-theme, pull requests merged in 2020-10, with the labels that each got.

#1192 PLANET-5526: Add noindex meta tag for no results search page
  src/Search.php
Labels: Review

#1194 Pass test regardless of result
  .circleci/config.yml
Labels: Review

#1197 PLANET-5557 Add Auth creds for all Docker Hub images
  .circleci/config.yml
Labels: Review

#1199 PLANET-5373 Remove the "by" string in post details page and taxonomy details page
  templates/single.twig
  templates/tease-taxonomy-post.twig
Labels: Review

#1196 Planet 5485 Rewrite ImageArchive using hooks
  assets/src/js/Components/ArchivePicker.js
  assets/src/js/Components/ImagePicker.js
  assets/src/js/Components/archivePicker/ArchivePickerList.js
  assets/src/js/Components/archivePicker/MultiSidebar.js
  assets/src/js/Components/archivePicker/SingleSidebar.js
  assets/src/js/Components/archivePicker/archivePickerList.js
  assets/src/js/Components/archivePicker/archivePickerSidebar.js
  assets/src/js/Components/archivePicker/sizeFunctions.js
  assets/src/js/Components/archivePicker/useImages.js
Labels: Review

#1200 Manually specify master for other repo
  .circleci/config.yml
Labels: WIP

#1207 PLANET-5388 Fix author bio translation on Post and Author page
  author.php
  templates/blocks/author_profile.twig
Labels: Review

#1204 PLANET-5388 PLANET-5388 Fix related articles issue on Post
  single.php
Labels: Review

#1206 Always add apps login filter
  src/Cookies.php
Labels: Review

#1211 PLANET-5592: Remove id attributes in svg markup of icon
  assets/src/js/external_links.js
Labels: Review

#1212 Use python3 in zip creation container
  .circleci/config.yml
Labels: Review

#1213 Use python2 in zip creation container
  .circleci/config.yml
Labels: Review

#1208 PLANET-5221 Checkout code for forks, instead of composer
  .circleci/config.yml
Labels: Review

#1215 Planet 5481 - Improve Image Archive UI
  admin/css/picker.css
  assets/src/js/Components/ArchivePicker.js
  assets/src/js/Components/archivePicker/ArchivePickerList.js
  assets/src/js/Components/archivePicker/MultiSidebar.js
  assets/src/js/Components/archivePicker/SingleSidebar.js
  src/ImageArchive/UiIntegration.php
Labels: Review, UAT Passed

#1166 PLANET-4811 Add backtop markup to base template
  templates/base.twig
Labels: Review

#1218 PLANET-5441 Fix hashtag cuts off text for social media sharing
  templates/blocks/meta_fields.twig
  templates/blocks/share_buttons.twig
Labels: hacktoberfest-accepted

#1214 PLANET-5211 Home page Accessibility: Navigation bar and "Skip to..." links
  assets/src/js/country_select.js
  templates/base.twig
  templates/navigation-bar.twig
Labels: Review

#1220 PLANET-5254 Author page accessibility
  assets/src/scss/pages/_author.scss
  templates/author.twig
Labels: Review
