Repository greenpeace/planet4-master-theme, pull requests merged in 2020-01, with the labels that each got.

#983 Fix GP Slovakia url
  templates/countries.json
Labels: Review & Merge

#979 PLANET-4456 Fix special chars in campaign import
  classes/class-p4-campaign-importer.php
  exporter-helper.php
Labels: Review & Merge

#985 PLANET-4510 Fix PHP notice
  classes/class-p4-master-site.php
Labels: Review & Merge

#989 PLANET-4523 Send url of last seen archive from frontend
  assets/src/js/search.js
  classes/class-p4-search.php
Labels: WIP

#990 PLANET-4454: Posts: Anchor link extends beyond the body column
  assets/src/scss/base/_body.scss
Labels: Review & Merge

#993 PLANET-4515 Specify search fields including author
  classes/class-p4-search.php
Labels: Review & Merge

#987 PLANET-4524: CPP: Rogue space at top of page
  assets/src/scss/pages/_page.scss
  templates/single-campaign.twig
Labels: Review & Merge

#988 PLANET-4441 Fix image alignment
  assets/src/scss/pages/_page.scss
  assets/src/scss/pages/post/_article-content.scss
Labels: Review but NOT MERGE

#986 PLANET-4429 Give `list_users` capability to editors
  classes/class-p4-activator.php
Labels: Review & Merge

#998 PLANET-4659 CPP import - Replace regex with parse_block()
  classes/class-p4-campaign-importer.php
Labels: Review & Merge

#995 PLANET-4456 CPP export - Replace regex with parse_block()
  classes/class-p4-campaign-importer.php
  exporter-helper.php
Labels: Review & Merge

#1000 PLANET-4595: Archive - Implement command to include archived content in search results (incl. mobile)
  assets/src/scss/pages/search/_search.scss
  templates/search.twig
Labels: Review & Merge

#1001 PLANET-4690 Change Turkey language to Türkçe in Coutry selector
  templates/countries.json
Labels: Review & Merge
