Repository greenpeace/planet4-master-theme, pull requests merged in 2020-11, with the labels that each got.

#1219 PLANET-5253 Footer Accessibility
  templates/footer.twig
  templates/footer_min.twig
Labels: Review

#1222 PLANET-5606 Center search buttons svg icons
  assets/src/scss/pages/search/_filter-sidebar.scss
  assets/src/scss/pages/search/_search-bar.scss
Labels: Review, UAT Passed

#1229 PLANET-5660 Revert twitter card title url encoding
  templates/blocks/meta_fields.twig
Labels: Review

#1234 No ticket - Update admin login button styles
  admin/css/login.css
Labels: Review

#1235 PLANET-5619 Restrict CF plugin
  functions.php
Labels: Review

#1230 PLANET-5503 Remove hammer and slick CSS and JS resources
  src/MasterSite.php
Labels: Review

#1202 Include dash dash plugin in webpack
  package-lock.json
  package.json
  webpack.config.js
Labels: Review

#1239 Add custom selector config
  .stylelintrc
Labels: Review

#1238 Combine g fonts
  templates/google-fonts.twig
  templates/html-header.twig
Labels: Review

#1232 PLANET-5055 Pinned the ElasticPress Search algorithm to v3.4
  src/MasterSite.php
Labels: Review

#1236 PLANET-5585: Normalize action search results appearance with other results
  assets/src/scss/pages/search/_search-results.scss
  templates/tease-search.twig
Labels: Review, UAT Needed

#1240 PLANET-5619 Command to update CF key from config
  src/Loader.php
Labels: Review
