Repository greenpeace/planet4-master-theme, pull requests merged in 2020-03, with the labels that each got.

#1025 PLANET-4775 P4CG - Fix wrong green color on footer links
  classes/class-p4-post-campaign.php
Labels: Review

#1023 PLANET-4741 Do not show tags/share buttons if title is hidden
  templates/blocks/header.twig
Labels: Review

#1027 PLANET-4712 Remove breadcrumbs
  single-campaign.php
  templates/base.twig
  templates/single-campaign.twig
Labels: DO NOT MERGE

#1026 PLANET-3427 Prevent wordpress autosave recreation
  classes/class-p4-loader.php
  single-campaign.php
Labels: Review

#1028 PLANET-4751 Refactor campaign exporter module
  exporter-helper.php
  exporter.php
Labels: Review

#1022 Use IN query and separate some logic for readability
  exporter-helper.php
Labels: WIP

#1012 PLANET-4745: Campaigns CSS: EN form block title and CTA style
  assets/src/js/app.js
  assets/src/js/cssvarsponyfill.js
  classes/class-p4-master-site.php
  classes/class-p4-post-campaign.php
  templates/css-variables.twig
Labels: Review

#1030 PLANET-4750: Campaigns customiser - Adjust Header primary font options
  campaign_themes/antarctic.json
  campaign_themes/arctic.json
  campaign_themes/climate.json
  campaign_themes/default.json
  campaign_themes/forest.json
  campaign_themes/oceans.json
  campaign_themes/oil.json
  campaign_themes/plastic.json
Labels: Review

#1032 PLANET-4821: Gallery block: only first image is being displayed
  classes/class-p4-master-site.php
Labels: Review

#1033 PLANET-4840 Fix campaign meta
  single-campaign.php
Labels: Review

#1036 PLANET-4860 Fix a bug catch by Sentry Issue: 908
  exporter-helper.php
Labels: Review

#1037 PLANET-4845: JS Error: Unable to edit background image in pages
  classes/class-p4-master-site.php
Labels: Review

#1040 PLANET-4844: Pages: Open Graph/Social fields not pulled
  classes/class-p4-metabox-register.php
  classes/class-p4-post.php
Labels: Review

#1041 PLANET-4880 Increase GTM timeout to 4000
  templates/html-header.twig
Labels: Review

#1038 PLANET-4869 Remove unnecessary css code from login page
  README.md
  admin/css/login.css
  classes/class-p4-master-site.php
  images/p4-logo.png
  images/planet4.png
  planet4.png
Labels: Review

#1031 PLANET-4561: Make sure P4 Spreadsheet embed (New Block) respects all Campaign Styles
  assets/src/scss/campaigns/_campaign_footer.scss
  assets/src/scss/style.scss
  campaign_themes/antarctic.json
  campaign_themes/arctic.json
  campaign_themes/climate.json
  campaign_themes/default.json
  campaign_themes/forest.json
  campaign_themes/oceans.json
  campaign_themes/oil.json
  campaign_themes/plastic.json
  classes/class-p4-post-campaign.php
  templates/css-variables.twig
  templates/html-header.twig
Labels: Review

#1042 Hotfix: Restore old body font logic in a method.
  classes/class-p4-post-campaign.php
Labels: Review

#1046 [No issue]: Fix JSON file for the Default campaign theme
  campaign_themes/default.json
Labels: Review

#1045 PLANET-4889 Added new value to campaign dataLayer dropdown (Covid-19)
  classes/class-p4-metabox-register.php
Labels: Review

#1047 [No issue]: Font size for XL screens in pages.
  assets/src/scss/pages/_page.scss
Labels: Review

#1049 PLANET-4858 Add gPlatform var to dataLayer to track platform source
  templates/html-header.twig
Labels: Review
