Repository greenpeace/planet4-master-theme, pull requests merged in 2021-11, with the labels that each got.

#1505 PLANET-6455 Add filter to catch core bug removing gradients
  assets/src/js/external_links.js
  functions.php
Labels: [Test Env] pluto

#1504 PLANET-5799 Align search results title color with design system
  assets/src/scss/pages/search/_search-results.scss
Labels: Review, UAT Passed

#1506 PLANET-6006 Remove Gallery carousel indicator active color
  assets/src/scss/base/_colors.scss
Labels: Review, UAT Needed

#1500 PLANET-6008 Button and link focus outline
  assets/src/scss/base/_typography.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/components/_share-buttons.scss
  assets/src/scss/layout/_navbar.scss
Labels: [Test Env] janus

#1512 Make sure unit tests run on the right WP version
  .circleci/config.yml
  bin/install-wp-tests.sh
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/data/images/pressmedia.jpg
Labels: Review, [Test Env] pandora

#1454 PLANET-6379 New post design
  assets/src/images/icons/comments.svg
  assets/src/scss/base/_colors.scss
  assets/src/scss/components/_share-buttons.scss
  assets/src/scss/editor/postWidth.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/editorWidth.scss
  assets/src/scss/layout/_breadcrumbs.scss
  assets/src/scss/pages/post/_article-content.scss
  assets/src/scss/pages/post/_author-block.scss
  assets/src/scss/pages/post/_comments-block.scss
  assets/src/scss/pages/post/_comments-form.scss
  assets/src/scss/pages/post/_post.scss
  images/blue-chevron.svg
  images/comment_bubble.svg
  single.php
  src/MasterSite.php
  templates/blocks/author_profile.twig
  templates/child_comments.twig
  templates/comment.twig
  templates/comment_form/author_field.twig
  templates/comment_form/comment_field.twig
  templates/comment_form/email_field.twig
  templates/comment_form/submit_button.twig
  templates/comments_section.twig
  templates/single-attachment.twig
  templates/single.twig
  tests/acceptance/ActPageCept.php
Labels: Review, [Test Env] sinope

#1516 Keep tests folder on zip creation
  .circleci/config.yml
Labels: Review

#1517 Fix space between breadcrumb tags
  assets/src/scss/layout/_breadcrumbs.scss
Labels: Review, [Test Env] saturn

#1510 PLANET-6430: Carousel Header - CTA button is not editable in Safari
  assets/src/scss/editorOverrides.scss
Labels: Review, [Test Env] nix

#1508 PLANET-6091 Add new XXL breakpoint
  assets/src/scss/base/_mixins.scss
  assets/src/scss/base/_variables.scss
  assets/src/scss/pages/_page.scss
  assets/src/scss/pages/post/_post.scss
  assets/src/scss/vendors/_bootstrap.scss
  webpack.config.js
Labels: Review, UAT Passed

#1493 Convert Take Action Boxout setting to blocks, and remove field
  src/MetaboxRegister.php
  src/Migrations/M005TurnBoxoutSettingIntoBlock.php
  src/Migrator.php
Labels: Review, [Test Env] phobos

#1521 Move front end assets logic out of MasterSite, create separate partial CSS files depending on country selector feature
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/partials/country-selector-new.scss
  assets/src/scss/partials/country-selector-old.scss
  src/Features.php
  src/Loader.php
  src/MasterSite.php
  src/PublicAssets.php
  webpack.config.js
Labels: Review, [Test Env] tavros

#1522 Move palette classes to separate file
  assets/src/scss/base/_colors.scss
  assets/src/scss/base/_palette.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
Labels: [Test Env] saturn

#1525 Load master-theme partial styles before any child-theme
  src/MasterSite.php
  src/PublicAssets.php
Labels: [Test Env] umbriel

#1471 PLANET-6257: New country selector design implementation
  assets/src/js/header.js
  assets/src/scss/layout/_country-selector.scss
  assets/src/scss/partials/country-selector-new.scss
  images/cross.svg
  images/gp-g-logo.png
  src/Features.php
  src/MasterSite.php
  src/Settings.php
  templates/base.twig
  templates/footer.twig
  templates/footer_country_selector.twig
  templates/navigation-bar.twig
Labels: Review, UAT Passed, [Test Env] iocaste

#1528 Add draggable svg icon
  images/draggable-icon.svg
Labels: Review

#1527 Faster update command for data sync to test instances
  src/Commands.php
  src/Commands/FixOrphans.php
Labels: [Test Env] venus

#1530 Fix footer icons to inherit hover color
  assets/src/scss/layout/_footer.scss
Labels: Review, UAT Passed, [Test Env] tavros

#1524 Add container class to page-template elements
  assets/src/scss/pages/_page.scss
  assets/src/scss/pages/post/_post.scss
  templates/author.twig
  templates/evergreen.twig
  templates/page.twig
  templates/single-campaign.twig
  templates/single-page.twig
  templates/tag.twig
  templates/taxonomy.twig
Labels: [Test Env] uranus
