Repository greenpeace/planet4-master-theme, pull requests merged in 2021-03, with the labels that each got.

#1319 PLANET-5979 Fix Twitter share button on evergreen page template
  page-templates/evergreen.php
Labels: Review

#1320 Bump dashdash, whitelist shorthand
  .stylelintrc
  package-lock.json
  package.json
Labels: Review

#1297 PLANET-5843 Replace some colors to align with the design system
  admin/css/login.css
  assets/src/scss/pages/_evergreen.scss
  assets/src/scss/pages/_sitemap.scss
  assets/src/scss/pages/post/_article-content.scss
  assets/src/scss/pages/post/_author-block.scss
  assets/src/scss/pages/search/_filter-sidebar.scss
  assets/src/scss/pages/search/_search-bar.scss
  assets/src/scss/pages/search/_search-results.scss
  assets/src/scss/pages/search/_search.scss
  images/down-arrow-blue.svg
Labels: HOLD, UAT Passed

#1305 PLANET-5906: Migrate to Bootstrap 5
  assets/src/scss/bootstrap-build.scss
  package-lock.json
  package.json
  templates/blocks/share_buttons.twig
  templates/footer.twig
  templates/footer_min.twig
  templates/tease-author.twig
  templates/tease-search.twig
  templates/tease-taxonomy-post.twig
Labels: Review, UAT Needed

#1322 Fix base branch and name
  .circleci/config.yml
Labels: Review

#1321 Move over svg icons from styleguide
  assets/src/js/app.js
  images/icons/angle-right.svg
  images/icons/creative-commons.svg
  images/icons/download.svg
  images/icons/envelope.svg
  images/icons/facebook-f.svg
  images/icons/facebook-square.svg
  images/icons/facebook.svg
  images/icons/file-pdf.svg
  images/icons/filter.svg
  images/icons/flickr.svg
  images/icons/github-alt.svg
  images/icons/github-square.svg
  images/icons/github.svg
  images/icons/instagram.svg
  images/icons/line.svg
  images/icons/linkedin-in.svg
  images/icons/linkedin.svg
  images/icons/mastodon.svg
  images/icons/medium-m.svg
  images/icons/medium.svg
  images/icons/pinterest-p.svg
  images/icons/pinterest-square.svg
  images/icons/pinterest.svg
  images/icons/rss-square.svg
  images/icons/rss.svg
  images/icons/search.svg
  images/icons/snapchat-ghost.svg
  images/icons/snapchat-square.svg
  images/icons/snapchat.svg
  images/icons/soundcloud.svg
  images/icons/spotify.svg
  images/icons/telegram-plane.svg
  images/icons/telegram.svg
  images/icons/tiktok.svg
  images/icons/times.svg
  images/icons/tumblr-square.svg
  images/icons/tumblr.svg
  images/icons/twitter-square.svg
  images/icons/twitter.svg
  images/icons/viber.svg
  images/icons/vimeo-square.svg
  images/icons/vimeo-v.svg
  images/icons/vimeo.svg
  images/icons/vine.svg
  images/icons/weibo.svg
  images/icons/weixin.svg
  images/icons/whatsapp-square.svg
  images/icons/whatsapp.svg
  images/icons/wikipedia.svg
  images/icons/xing-square.svg
  images/icons/xing.svg
  images/icons/youtube-square.svg
  images/icons/youtube.svg
Labels: Review

#1324 PLANET-5035 Make sure author image is full height
  assets/src/scss/pages/post/_author-block.scss
Labels: Review

#1326 PLANET-5990 Restrict max-width on floated elements
  assets/src/scss/pages/post/_article-content.scss
Labels: Review

#1259 PLANET-4590: add credit text to the rest api response
  src/MasterSite.php
Labels: Review

#1268 PLANET-5748 Add password validation message on password protected page
  assets/src/scss/pages/_page.scss
  page.php
  single-campaign.php
  single.php
  src/Post.php
  templates/single-page.twig
  templates/single-password.twig
Labels: Review

#1328 PLANET-5501 Update clear search filters button styles
  assets/src/scss/pages/search/_filter-sidebar.scss
  templates/search.twig
Labels: Review

#1329 PLANET-5519 Update Timber plugin to v1.18.*
  composer.json
  composer.lock
Labels: Review

#1332 test against version we use
  .circleci/config.yml
  bin/install-wp-tests.sh
Labels: Review

#1331 Prevent unneeded prefixes, we autoprefix
  .stylelintrc
  assets/src/scss/pages/post/_author-block.scss
  assets/src/scss/pages/post/_post.scss
Labels: Review

#1295 PLANET-5756 Remove jQuery from external_link.js and pdf_icon.js
  assets/src/js/external_links.js
  assets/src/js/pdf_icon.js
  images/external-link.svg
Labels: Review, UAT Passed

#1334 PLANET-5848 Remove blue caption from classic editor images
  assets/src/scss/pages/post/_article-content.scss
Labels: Review

#1279 WordPress 5.6 preparation
  .circleci/config.yml
  bin/install-wp-tests.sh
  src/ImageArchive/Rest.php
  src/MasterSite.php
Labels: DO NOT MERGE, WIP

#1341 PLANET-6021 Hide core upgrade notice
  functions.php
Labels: Review

#1333 PLANET-5748 Update password form UI as per design system
  assets/src/scss/pages/_page.scss
  templates/single-page.twig
  templates/single-password.twig
Labels: Review, UAT Passed

#1342 PLANET-6028 explicitly define bootstrap as dep of parent-style
  src/MasterSite.php
Labels: Review

#1345 Upgrade github-archive-installer to support composer 2
  composer.json
  composer.lock
Labels: Review

#1335 PLANET-6004 Fix pdf link icon (hover) colors
  assets/src/js/external_links.js
Labels: Review

#1347 PLANET-6035 Restore embed block iframe heights
  assets/src/scss/editorOverrides.scss
Labels: Review

#1330 PLANET-4535: Match change in plugin's script handle
  src/MasterSite.php
Labels: Review

#1346 PLANET-5622: Skewed overlay changes position when page length changes
  assets/src/scss/styleguide/src/layout/_skewed-overlay.scss
Labels: Review

#1343 PLANET-5984 Move input error styles to _forms.scss
  assets/src/scss/pages/_page.scss
  assets/src/scss/styleguide/src/layout/_forms.scss
  templates/single-page.twig
  templates/single-password.twig
Labels: Review

#1351 Fix Finland localized name
  templates/countries.json
Labels: Review
