Repository greenpeace/planet4-master-theme, pull requests merged in 2021-12, with the labels that each got.

#1533 Replace page-template with page-content as its main class
  assets/src/js/external_links.js
  assets/src/scss/layout/_tables.scss
  assets/src/scss/pages/_evergreen.scss
  assets/src/scss/pages/_page.scss
  templates/author.twig
  templates/evergreen.twig
  templates/page.twig
  templates/single-campaign.twig
  templates/single-page.twig
  templates/tag.twig
  templates/taxonomy.twig
Labels: Review, HOLD, [Test Env] nix

#1534 PLANET-6252 New Cookie Box design (1st iteration)
  assets/src/scss/layout/_cookies-new.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/style.scss
  templates/cookies.twig
Labels: Review, UAT Passed, [Test Env] umbriel

#1535 Check for possible bool return value from CMB2_Field before calling value()
  src/Features.php
Labels: [Test Env] tavros

#1538 Class selector as multiple blocks will be allowed
  assets/src/js/external_links.js
Labels: Review, [Test Env] iocaste

#1509 PLANET-6256: New navigation bar design
  assets/src/images/icons/menu.svg
  assets/src/js/header.js
  assets/src/scss/base/_colors.scss
  assets/src/scss/base/_mixins.scss
  assets/src/scss/layout/_navbar-old.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/pages/_page.scss
  assets/src/scss/partials/navigation-bar-dark.scss
  assets/src/scss/partials/navigation-bar-light.scss
  assets/src/scss/style.scss
  images/checkmark.svg
  images/cross-circle.svg
  images/menu.svg
  src/Features.php
  src/MasterSite.php
  src/PublicAssets.php
  src/Settings.php
  templates/base.twig
  templates/navigation-bar-new.twig
  templates/navigation-bar_min-new.twig
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] pandora

#1540 Fix template error on navbar with multilingual site
  src/MasterSite.php
  templates/navigation-bar-new.twig
Labels: [Test Env] rhea

#1543 Fix main & partial styles enqueue order
  src/MasterSite.php
  src/PublicAssets.php
Labels: [Test Env] atlas

#1544 Fix negative spacing interpolation
  assets/src/scss/layout/_country-selector.scss
Labels: Review, [Test Env] tavros

#1545 Restore js enqueue order
  src/MasterSite.php
  src/PublicAssets.php
Labels: [Test Env] titan

#1546 Country Selector: Remove white space from button
  assets/src/scss/layout/_country-selector.scss
  templates/footer_country_selector.twig
Labels: Review, [Test Env] iocaste

#1547 Split navigation bar SCSS file
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/layout/navbar/_site-logo.scss
  assets/src/scss/layout/navbar/languages.scss
Labels: Review, [Test Env] uranus

#1550 Avoid performing calculations at runtime in CSS
  assets/src/scss/base/_variables.scss
  assets/src/scss/layout/_country-selector.scss
  assets/src/scss/layout/navbar/_search.scss
Labels: Review, [Test Env] rhea

#1548 Reduce amount of variable properties, some fixes
  assets/src/js/header.js
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/languages.scss
Labels: Review, [Test Env] neptune

#1554 Add Google API client lib
  composer.json
  composer.lock
Labels: Review, [Test Env] atlas

#1541 Support Analytics values using Google Sheet
  src/AnalyticsValues.php
  src/Features.php
  src/GoogleDocsClient.php
  src/Settings.php
  src/Smartsheet.php
  src/SmartsheetClient.php
Labels: Review, [Test Env] umbriel

#1553 Allow setting features with a filter
  src/Features.php
Labels: Review, [Test Env] tavros

#1551 Remove enhanced donate button on new navbar, fix search toggle
  assets/src/js/header.js
  assets/src/scss/layout/navbar/_search.scss
  src/MasterSite.php
Labels: [Test Env] umbriel

#1552 Check every updated post for non CDN URLs
  functions.php
  src/Loader.php
Labels: Review, [Test Env] phobos

#1557 PLANET-6474 Remove space between truncated bio and remainder
  templates/blocks/author_profile.twig
Labels: Review
