Repository greenpeace/planet4-master-theme, pull requests merged in 2021-08, with the labels that each got.

#1422 Add P4 trainings to message board
  src/MasterSite.php
Labels: Review, [Test Env] phoebe

#1427 Fix fonts location and add missing fonts
  fonts/Jost-Black.woff
  fonts/Jost-BlackItalic.woff
  fonts/Jost-Book.woff
  fonts/Jost-BookItalic.woff
  fonts/save-the-arctic.otf
  templates/head/google_fonts.twig
Labels: [Test Env] neptune

#1419 PLANET-6083: Add UTM Parameters to share buttons
  page.php
  single-campaign.php
  single.php
  src/Context.php
  templates/blocks/share_buttons.twig
  templates/single.twig
Labels: Review, [Test Env] umbriel

#1430 Add quotes, message contains spaces
  .circleci/config.yml
Labels: DO NOT MERGE, [Test Env] phoebe

#1429 Add quotes, message contains spaces
  .circleci/config.yml
Labels: Review, [Test Env] venus

#1428 Ensure migrated old vars override new themes
  src/PostCampaign.php
Labels: [Test Env] tavros

#1432 Re-add GP green for plastics and climate nav color
  campaign_themes/climate.json
  campaign_themes/plastic.json
Labels: Review, [Test Env] pluto

#1434 PLANET-6318 Fix Twitter share description issue
  templates/blocks/share_buttons.twig
Labels: Review, [Test Env] titan
