Repository greenpeace/planet4-master-theme, pull requests merged in 2021-07, with the labels that each got.

#1402 Planet 6040 Update articles block attribute
  src/MigrationLog.php
  src/Migrations/M003UpdateArticlesBlockAttribute.php
  src/Migrator.php
Labels: Review

#1411 PLANET-6124: Change the way of setting the target to links when are externals
  assets/src/js/external_links.js
Labels: Review

#1412 PLANET-6238 Add private campaigns caps for editor role
  src/Campaigner.php
Labels: Review

#1384 PLANET-6237 Slack notifications
  composer.json
  composer.lock
  functions.php
  src/Notifications/MrkDwnField.php
  src/Notifications/Slack.php
  src/Settings.php
Labels: Review, [Test Env] janus

#1421 Move PR check in a script
  .circleci/config.yml
Labels: Review, [Test Env] neptune

#1281 Do ci setup in separate job step
  .circleci/config.yml
Labels: Review
