Repository greenpeace/planet4-master-theme, pull requests merged in 2021-04, with the labels that each got.

#1352 PLANET-5951 Fix search filter checkboxes font size
  assets/src/scss/pages/search/_filter-sidebar.scss
Labels: Review, UAT Passed

#1354 PLANET-6043 Fix search pages image aspect ratios
  assets/src/scss/pages/search/_search-results.scss
  templates/tease-search.twig
Labels: Review

#1355 PLANET-6045 Add relevant Acceptance tests
  phpcs.xml.dist
  tests/acceptance/404PageCept.php
  tests/acceptance/AboutUsPageCept.php
  tests/acceptance/ActPageCept.php
  tests/acceptance/AddCommentCept.php
  tests/acceptance/CookiesBannerCept.php
  tests/acceptance/CopyrightPageCept.php
  tests/acceptance/CustomTaxonomyPageCept.php
  tests/acceptance/ExplorePageCept.php
  tests/acceptance/FooterCept.php
  tests/acceptance/HeaderCept.php
  tests/acceptance/HomePageCept.php
  tests/acceptance/LoginCept.php
  tests/acceptance/PHPWarningsCept.php
  tests/acceptance/SearchCept.php
  tests/acceptance/SitemapPageCept.php
  tests/acceptance/campaign.feature
  tests/acceptance/editor.feature
  tests/data/test-campaign.lorem-ipsum.xml
Labels: Review

#1356 PLANET-5983: Properly extract vars from multiple files
  package-lock.json
  package.json
  webpack.config.js
Labels: Review

#1358 PLANET-6053 Remove inline-block from icon links to properly wrap
  assets/src/scss/styleguide/src/base/_icons.scss
  tests/acceptance/CustomTaxonomyPageCept.php
Labels: Review

#1359 PLANET-6041 Move up styleguide folders
  assets/src/scss/base/_body.scss
  assets/src/scss/base/_colors.scss
  assets/src/scss/base/_fonts.scss
  assets/src/scss/base/_functions.scss
  assets/src/scss/base/_icons.scss
  assets/src/scss/base/_mixins.scss
  assets/src/scss/base/_rtl.scss
  assets/src/scss/base/_shame.scss
  assets/src/scss/base/_typography.scss
  assets/src/scss/base/_variables.scss
  assets/src/scss/components/_blockquote.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/components/_share-buttons.scss
  assets/src/scss/components/_skip-links.scss
  assets/src/scss/components/_spinner.scss
  assets/src/scss/components/_tweet-block.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/layout/_blocks.scss
  assets/src/scss/layout/_breadcrumbs.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/layout/_footer.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/_page-header.scss
  assets/src/scss/layout/_page-section.scss
  assets/src/scss/layout/_skewed-overlay.scss
  assets/src/scss/layout/_tables.scss
  assets/src/scss/style.scss
Labels: Review

#1357 PLANET-5983 Prepare old campaign code
  src/PostCampaign.php
Labels: Review

#1325 PLANET-5983: Add variables
  assets/src/scss/base/_body.scss
  assets/src/scss/base/_typography.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/layout/_breadcrumbs.scss
  assets/src/scss/layout/_footer.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/_skewed-overlay.scss
  package-lock.json
  package.json
  src/PostCampaign.php
  webpack.config.js
Labels: Review

#1363 PLANET-6062 Hide Menu text when main menu is open on small screens
  assets/src/scss/layout/_navbar.scss
Labels: Review

#1365 PLANET-6082 Fix incorrect old name migration
  assets/src/scss/base/_icons.scss
  src/PostCampaign.php
Labels: Review

#1366 PLANET-5523 Add Beta Blocks option
  src/Features.php
  tag.php
Labels: Review

#1369 PLANET-6087 Refer to beta category in help
  src/Features.php
Labels: Review

#1285 PLANET-5897: Add HTTP Header class that sends CSP and X-Frame headers
  src/HttpHeaders.php
  src/Loader.php
Labels: Review

#1294 PLANET-5897: Feature/csp http headers
  src/HttpHeaders.php
  src/Loader.php
Labels: DO NOT MERGE

#1364 PLANET-6080 Add fonts in HTML head for campaigns
  single-campaign.php
  templates/head/google_fonts.twig
  templates/html-header.twig
Labels: Review

#1372 Add a job for posting a PR comment when test instance is ready
  .circleci/config.yml
Labels: Review
