Repository greenpeace/planet4-master-theme, pull requests merged in 2021-09, with the labels that each got.

#1435 PLANET-6361 Add JSON file of new themes
  assets/src/scss/layout/_page-header.scss
  campaign_themes/oceans.json
  src/PostCampaign.php
  themes/climate.json
  themes/forest.json
  themes/oceans.json
  themes/plastic.json
Labels: Review, [Test Env] pluto

#1436 PLANET-6336 Implement new Cookies banner design
  assets/src/scss/campaigns/_campaign_cookies.scss
  assets/src/scss/layout/_cookies-new.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/style.scss
Labels: Review, UAT Passed

#1438 PLANET-6253 Add analytical cookies setting in Planet4 settings
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] oberon

#1440 PLANET-6306: Run tests on PHP 7.4
  .circleci/config.yml
  src/Commands/CloudflarePurge.php
Labels: [Test Env] mars

#1441 Add styles for counter block in enform
  themes/climate.json
Labels: Review, [Test Env] pluto

#1443 Add font-family variable for page-section-header
  assets/src/scss/layout/_page-section.scss
  themes/oceans.json
Labels: Review, [Test Env] pluto

#1444 Remove legacy theme code
  campaign_themes/antarctic.json
  campaign_themes/arctic.json
  campaign_themes/oil.json
  src/PostCampaign.php
Labels: Review, [Test Env] venus

#1446 PLANET-6267 Remove incorrect urls for external and PDF link icons
  assets/src/images/icons/file-pdf.svg
  assets/src/scss/base/_icons.scss
Labels: Review, [Test Env] titan

#1451 Give theme options directory an accurate name
  src/PostCampaign.php
  theme_options/climate.json
  theme_options/default.json
  theme_options/forest.json
  theme_options/oceans.json
  theme_options/plastic.json
Labels: Review, [Test Env] sinope

#1453 Refactor of the current Footer campaign version
  assets/src/scss/layout/_footer.scss
  templates/base.twig
  templates/footer.twig
  templates/footer_min.twig
Labels: Review

#1456 Fix custom logo on campaign pages
  src/PostCampaign.php
Labels: Review, [Test Env] sinope

#1458 Improve and refactor the current Footer version
  assets/src/scss/layout/_footer.scss
  src/PostCampaign.php
  templates/base.twig
  templates/footer.twig
  themes/climate.json
  themes/plastic.json
Labels: Review, [Test Env] rhea

#1459 Move the Footer social media nav logic from the Footer to a new template
  templates/footer.twig
  templates/footer_social_media.twig
Labels: Review, HOLD, [Test Env] uranus

#1463 Add new social icons, rounded version, used by the new Footer design
  assets/src/images/icons/facebook-rounded.svg
  assets/src/images/icons/linkedin-rounded.svg
Labels: Review, [Test Env] uranus

#1468 Move footer social media to own template
  assets/src/scss/layout/_footer-social-media.scss
  assets/src/scss/layout/_footer.scss
  assets/src/scss/style.scss
Labels: [Test Env] venus

#1442 PLANET-6223 Implement Google's Consent Mode on Planet 4
  assets/src/js/app.js
  assets/src/js/cookies.js
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] iocaste

#1455 Add optional support for "block templates"
  src/Features.php
  src/MasterSite.php
Labels: Review, [Test Env] phoebe

#1473 Use different class for Cookies A/B test instead of additional one
  assets/src/scss/layout/_cookies-new.scss
  assets/src/scss/layout/_cookies.scss
Labels: Review, [Test Env] venus

#1474 PLANET-6421 Fix inverted logic of minimal footer
  templates/base.twig
Labels: Review, [Test Env] rhea

#1475 PLANET-6225 Fix source maps for generated CSS variables
  package-lock.json
  package.json
Labels: Review, [Test Env] iocaste, [Test Env] atlas
