Repository greenpeace/planet4-master-theme, pull requests merged in 2022-12, with the labels that each got.

#1834 PLANET-6931 Navigation submenu items that are anchors are not clickable
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
Labels: WIP, [Test Env] mars

#1836 PLANET-6954 Adding a custom CSS class through the admin panel is not reflected in the frontend when inspecting the page
  templates/navigation-submenu.twig
Labels: Review, [Test Env] rhea

#1857 PLANET-6980 Remove restricted tags box
  partials/tags-box.php
  src/MasterSite.php
Labels: Review, [Test Env] umbriel

#1853 PLANET-6981 Remove jQuery from dashboard.js
  admin/js/dashboard.js
  src/ControlPanel.php
Labels: Review, [Test Env] saturn

#1860 Add command for WPML media path migration
  src/Commands.php
  src/Migrations/M004UpdateMissingMediaPath.php
Labels: Review, [Test Env] mars

#1861 PLANET-6981 Remove jQuery from posts_report.js
  admin/js/posts_report.js
  src/PostReportController.php
Labels: Review, [Test Env] pandora

#1865 Switch Poland to the proper url
  templates/countries.json
Labels: Review, [Test Env] rhea

#1856 PLANET-6852: Remove features fallback and deduplicate p4 features in options
  src/Feature.php
  src/Migrations/M013RemoveDuplicatedOptions.php
  src/Migrator.php
  src/Settings/Features.php
Labels: Review, [Test Env] oberon

#1868 Fix form token field label text transform
  assets/src/scss/editorOverrides.scss
Labels: Review, [Test Env] phoebe

#1866 PLANET-6960 Add sidebar option to define canonical link
  functions.php
  src/ActionPage.php
  src/PageMeta.php
  src/PostCampaign.php
  src/PostMeta.php
Labels: Review, UAT Passed, [Test Env] umbriel

#1870 Remove duotone feature the proper way
  theme.json
Labels: Review

#1869 Remove Campaign tags from Action Pages
  single-p4_action.php
Labels: Review, [Test Env] titan
