Repository greenpeace/planet4-master-theme, pull requests merged in 2022-04, with the labels that each got.

#1661 PLANET-6154 Skip indexing archived content if Archive feature flag is…
  src/MasterSite.php
  src/Settings.php
Labels: Review, [Test Env] titan

#1654 PLANET-6670 Set right editor width per post type*
  assets/src/scss/editor/postWidth.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/editorWidth.scss
  functions.php
  src/Context.php
  templates/blocks/header.twig
  templates/page.twig
  templates/single-campaign.twig
  tests/acceptance/ExplorePageCept.php
  theme.json
Labels: Review, [Test Env] phobos

#1645 PLANET-6515 Migrate "Include Articles In Post" setting to a regular Articles block on Post
  single.php
  src/MetaboxRegister.php
  src/Migrations/M011TurnIncludeArticlesSettingIntoBlock.php
  src/Migrator.php
  templates/single.twig
Labels: Review

#1662 PLANET-6690 Use secondary style by default on buttons in the editor
  assets/src/scss/editorOverrides.scss
Labels: Review, [Test Env] titan

#1665 PLANET-6690 Update Table block settings in theme.json
  theme.json
Labels: Review, [Test Env] titan

#1663 PLANET-6702: Fix Mobile nav link color
  assets/src/scss/layout/navbar/mobile.scss
  assets/src/scss/partials/navigation-bar-light.scss
Labels: Review, UAT Passed, [Test Env] venus

#1621 PLANET-6625: Set default consent mode on every page
  assets/src/js/cookies.js
  templates/blocks/google_tag_manager.twig
Labels: UAT Passed, [Test Env] tavros

#1667 PLANET-6729 Make IA features use feature classes
  single.php
  src/ActionPage.php
  src/Feature.php
  src/Features/ActionPostType.php
  src/Features/GdprCheckbox.php
  src/Features/MobileTabsMenu.php
  src/MasterSite.php
  src/Migrations/M001EnableEnFormFeature.php
  src/Migrations/M002EnableLazyYoutube.php
  src/Migrations/M010RemoveGdprPluginOptions.php
  src/Settings/Comments.php
  src/Settings/InformationArchitecture.php
Labels: Review, [Test Env] venus

#1670 PLANET-6551: Fix navbar issue on ipad pro
  assets/src/scss/layout/navbar/_search.scss
Labels: Review, [Test Env] rhea

#1660 PLANET-6730 Split post css
  assets/src/scss/pages/post/_article-content.scss
  assets/src/scss/pages/post/_post.scss
  assets/src/scss/post.scss
  assets/src/scss/style.scss
  src/PublicAssets.php
  webpack.config.js
Labels: Review, [Test Env] pandora, Dev Sites testing needed

#1628 PLANET-6673: Navigation bar drop down menus
  assets/src/js/header.js
  assets/src/js/menu_editor.js
  assets/src/scss/base/_mixins.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/layout/navbar/languages.scss
  assets/src/scss/partials/navigation-bar-light.scss
  src/AdminAssets.php
  src/Features/DropdownMenu.php
  src/MasterSite.php
  src/Settings.php
  src/Settings/InformationArchitecture.php
  templates/burger-menu-items.twig
  templates/burger-menu.twig
  templates/navigation-bar-new.twig
  templates/navigation-submenu.twig
Labels: Review, [Test Env] nix, Dev Sites testing needed

#1631 PLANET-6645 Add paginated list on tag pages
  assets/src/scss/layout/_block-classes.scss
  assets/src/scss/style.scss
  functions.php
  parts/query-grid.html
  parts/query-list.html
  src/Feature.php
  src/Features/Dev/DisableTagRedirectPages.php
  src/Features/Dev/ListingPageGridView.php
  src/Features/Dev/ListingPagePagination.php
  src/Post.php
  src/Settings/Features.php
  tag.php
  templates/tag.twig
Labels: [Test Env] mars

#1672 Clean up burger menu code
  assets/src/scss/layout/navbar/_burger-menu.scss
  templates/burger-menu-items.twig
  templates/burger-menu.twig
Labels: Review, [Test Env] titan

#1674 PLANET-6705 Treat gp_nro cookie as 1st party cookie
  assets/src/js/cookies.js
Labels: Review, [Test Env] rhea

#1678 Remove unused scss import
  assets/src/scss/layout/navbar/mobile.scss
Labels: [Test Env] titan

#1673 PLANET-6673 Burger menu fixes
  assets/src/scss/base/_mixins.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
  templates/burger-menu.twig
Labels: Review, [Test Env] venus

#1683 PLANET-6733: Nav search form is hidden on large screens
  templates/navigation-bar-new.twig
Labels: Review, [Test Env] neptune

#1684 Change <section> to <header> from Header
  templates/navigation-bar-new.twig
Labels: [Test Env] neptune

#1679 PLANET-6734 Inherit color for heading links
  assets/src/scss/base/_typography.scss
Labels: Review, [Test Env] venus

#1680 Use opacity instead of visibility for better performance
  assets/src/scss/layout/navbar/_burger-menu.scss
Labels: Review, [Test Env] venus

#1675 PLANET-6708: Fix page padding with mobile tabs menu
  assets/src/js/header.js
  assets/src/scss/pages/_page.scss
Labels: [Test Env] tavros

#1682 PLANET-6637: Create a Reviewer user role
  load-class-aliases.php
  src/Activator.php
  src/Role/Campaigner.php
  src/Role/Reviewer.php
Labels: [Test Env] titan

#1677 PLANET-6695 Always show scroll bar in cookies settings
  assets/src/scss/layout/_cookies-settings.scss
Labels: Review, [Test Env] rhea

#1688 Add setting to link to category directly
  src/Features/PostPageCategoryLinks.php
  src/Post.php
  src/Settings/Features.php
  src/Settings/InformationArchitecture.php
Labels: Review, [Test Env] titan

#1689 Modify Donate button functionality on Mobile
  templates/burger-menu.twig
Labels: Review, [Test Env] titan

#1693 Harmonize Features titles and descriptions
  src/Feature.php
  src/Features/ActionPostType.php
  src/Features/CloudflareDeployPurge.php
  src/Features/Dev/AllowAllBlocks.php
  src/Features/Dev/BetaBlocks.php
  src/Features/Dev/CoreBlockPatterns.php
  src/Features/Dev/DisableTagRedirectPages.php
  src/Features/Dev/ListingPagePagination.php
  src/Features/Dev/WPTemplateEditor.php
  src/Features/DropdownMenu.php
  src/Features/EngagingNetworks.php
  src/Features/GdprCheckbox.php
  src/Features/GoogleSheetReplacesSmartsheet.php
  src/Features/ImageArchive.php
  src/Features/LazyYoutubePlayer.php
  src/Features/MobileTabsMenu.php
  src/Features/NewDesignCountrySelector.php
  src/Features/NewDesignNavigationBar.php
  src/Features/PostPageCategoryLinks.php
  src/Features/PurgeOnFeatureChanges.php
  src/Settings/Features.php
Labels: [Test Env] titan
