Repository greenpeace/planet4-master-theme, pull requests merged in 2022-01, with the labels that each got.

#1556 Also add lite YouTube player on 2nd oembed filter
  assets/src/scss/editorStyle.scss
  src/MasterSite.php
Labels: [Test Env] pluto

#1562 Clean up (some) search dead code
  assets/src/js/search.js
  src/Search.php
  templates/search.twig
Labels: Review, [Test Env] nix

#1558 PLANET-5968 Ensure translated media gets Stateless meta
  functions.php
  src/MasterSite.php
Labels: Review, [Test Env] venus

#1559 PLANET-5758 Remove jQuery from header.js
  assets/src/js/app.js
  assets/src/js/header.js
Labels: Review, [Test Env] deimos

#1567 PLANET-6549 Fix ga-action attribute for navbar hamburger menu
  assets/src/js/header.js
  templates/navigation-bar-new.twig
Labels: Review, [Test Env] venus

#1560 PLANET-6338: Fix duplicate results in search
  assets/src/js/search.js
  search.php
  src/ElasticSearch.php
  src/Search.php
Labels: [Test Env] pluto

#1568 PLANET-6548 Fix new navbar site logo link width in small screens
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_site-logo.scss
Labels: Review, [Test Env] tavros

#1569 PLANET-6466 Anonymize Comment Authors IP address
  src/MasterSite.php
Labels: Review, [Test Env] sinope

#1571 PLANET-6572 Use a high z-index number for navbar
  assets/src/scss/layout/_navbar.scss
Labels: Review, [Test Env] nix

#1573 Adjust CSS Customizer typography for readability
  assets/src/scss/editorOverrides.scss
Labels: Review, [Test Env] pluto

#1574 PLANET-6574 Remove unneeded filter that broke media library
  src/Search.php
Labels: Review, [Test Env] tavros

#1575 PLANET-6542 Disable search button when search input is empty
  assets/src/scss/layout/navbar/_search.scss
Labels: Review, [Test Env] sinope

#1564 PLANET-5761 Remove jQuery from search
  assets/src/js/app.js
  assets/src/js/search.js
  assets/src/scss/pages/search/_search-results.scss
  templates/search.twig
  templates/tease-search.twig
Labels: Review

#1576 PLANET-6505 Remove author image in case of author override
  templates/single.twig
Labels: Review, [Test Env] neptune

#1566 PLANET-6522: Remove option for enhanced Donate button
  assets/src/js/app.js
  assets/src/js/enhancedDonateButton.js
  src/MasterSite.php
  src/Migrations/M007RemoveEnhancedDonateButtonOption.php
  src/Migrator.php
  src/Settings.php
  templates/navigation-bar-new.twig
  templates/navigation-bar.twig
Labels: [Test Env] venus

#1578 Use grid for Planet 4 admin options
  admin/css/campaign.css
  admin/css/options.css
  src/Settings.php
Labels: Review, [Test Env] pluto

#1572 PLANET-6536 Move feature settings to a separate WP option
  src/Features.php
  src/Migrations/M006MoveFeaturesToSeparateOption.php
  src/Migrator.php
  src/Settings.php
Labels: Review, [Test Env] deimos

#1447 PLANET-6387 Allow import/export for all post types
  load-class-aliases.php
  src/Exporter.php
  src/Importer.php
  src/Loader.php
Labels: Review, [Test Env] tavros

#1570 PLANET-6263 Implement country selector banner A/B test
  templates/navigation-bar-new.twig
Labels: Review, UAT Passed, [Test Env] umbriel

#1582 Add reading time to listing pages
  templates/tease-author.twig
  templates/tease-taxonomy-post.twig
Labels: Review, [Test Env] venus

#1585 Add feature toggle for core block patterns
  src/Features.php
  src/MasterSite.php
Labels: Review, [Test Env] rhea

#1581 Update pseudo selectors for buttons
  assets/src/scss/components/_share-buttons.scss
Labels: [Test Env] tavros

#1589 Enable experimental features on local environment too
  src/Features.php
  src/MasterSite.php
Labels: Review, [Test Env] rhea

#1592 PLANET-6512 Update post top links
  assets/src/scss/layout/_breadcrumbs.scss
  templates/single.twig
Labels: Review, UAT Passed

#1590 PLANET-6577 Hj search event
  assets/src/js/header.js
Labels: Review, [Test Env] venus, [Test Env] rhea

#1583 PLANET-6496 Happy Point: add option for code snippet embed
  src/Settings.php
Labels: Review

#1586 PLANET-6603 Add Cookies text fields to settings
  src/Settings.php
Labels: Review, UAT Passed

#1595 Cache the reading time using ID and date as key
  src/Post.php
Labels: [Test Env] umbriel

#1593 Planet 6606 fix navbar issue
  assets/src/scss/base/_mixins.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_search.scss
Labels: [Test Env] rhea

#1597 Fix tags spacing in breadcrumbs
  assets/src/scss/layout/_breadcrumbs.scss
Labels: Review, [Test Env] titan
