Repository greenpeace/planet4-master-theme, pull requests merged in 2022-11, with the labels that each got.

#1827 PLANET-6950: Add new visited pseudo class style
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/partials/navigation-bar-light.scss
Labels: Review, [Test Env] phobos

#1829 PLANET-6948 Increase the size of the navigation bar drop-down menu
  assets/src/scss/layout/_navbar.scss
  src/AdminAssets.php
Labels: Review, UAT Passed, [Test Env] rhea

#1831 PLANET-6929 Fixed GF confirmation message share button issue
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] titan

#1832 PLANET-6930 Fix Gravity Forms share text issues
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] venus

#1833 FIx navlink hover color
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/partials/navigation-bar-light.scss
Labels: Review, [Test Env] leda

#1835 PLANET-6955 ErrorException: Warning: uasort() expects parameter 1 to be array, null given
  functions.php
Labels: Review, [Test Env] phobos

#1828 Simplify Ci config
  .circleci/config.yml
Labels: Review, [Test Env] pluto

#1837 PLANET-6928: Create a new listing page stylesheet
  assets/src/scss/pages/_listing-page.scss
  assets/src/scss/style.scss
Labels: Review, [Test Env] venus

#1812 PLANET-6918: Implement actions listing page
  archive-p4_action.php
  archive.php
  parts/action/query-grid.html
  parts/action/query-list.html
  src/Features/ListingPagePagination.php
  src/Post.php
  templates/all-actions.twig
  templates/blocks/image.twig
  templates/tease-taxonomy-action.twig
Labels: Review, UAT Passed, [Test Env] titan

#1838 Fix reading time value
  src/Post.php
Labels: Review, [Test Env] pandora

#1839 PLANET-6952: New layout applied to default and category listing pages
  assets/src/scss/layout/_block-classes.scss
  assets/src/scss/pages/_listing-page.scss
  assets/src/scss/style.scss
  parts/query-grid.html
  parts/query-list.html
Labels: Review, UAT Passed, [Test Env] pandora

#1840 PLANET-6892 Add localize action slug option
  src/ActionPage.php
Labels: Review, UAT Needed, [Test Env] phoebe

#1843 PLANET-6961: Action Type listing page empty when no pagination
  taxonomy.php
Labels: [Test Env] saturn

#1842 PLANET-6914 Prepare to upgrade to Wordpress 6.1.1
  assets/src/scss/base/_typography.scss
  assets/src/scss/editorOverrides.scss
  theme.json
Labels: Review, [Test Env] janus

#1849 Fix post title declaration
  src/Context.php
Labels: Review, [Test Env] telesto

#1850 PLANET-5771 Remove jQuery from app.js
  assets/src/js/app.js
  assets/src/js/country_select.js
  tests/acceptance/HomePageCept.php
Labels: Review, [Test Env] phoebe
