Repository greenpeace/planet4-master-theme, pull requests merged in 2022-07, with the labels that each got.

#1753 PLANET-6845: Fix menu config loading
  src/AdminAssets.php
Labels: [Test Env] phobos

#1751 PLANET-6844: Anti-flicker snippet does not load properly
  templates/blocks/google_antiflicker.twig
  templates/blocks/google_tag_manager.twig
  templates/html-header.twig
Labels: [Test Env] neptune, [Test Env] saturn

#1754 PLANET-6847: Improve the Page Create Patterns modal layout
  assets/src/scss/editorOverrides.scss
Labels: Review, UAT Passed, [Test Env] rhea

#1755 PLANET-6506: Remove Smartsheet code
  load-class-aliases.php
  src/AnalyticsValues.php
  src/Features/GoogleSheetReplacesSmartsheet.php
  src/GoogleDocsClient.php
  src/Migrations/M011RemoveSmartsheetOption.php
  src/Migrator.php
  src/Settings.php
  src/Settings/Features.php
  src/SmartsheetClient.php
  src/Spreadsheet.php
Labels: [Test Env] deimos

#1756 PLANET-6850 Add allow-plugns config to composer
  composer.json
Labels: Review

#1715 PLANET-6698: Remove the Donate button styles and classes
  assets/src/scss/base/_colors.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
Labels: [Test Env] phoebe
