Repository greenpeace/planet4-master-theme, pull requests merged in 2022-02, with the labels that each got.

#1602 PLANET-6622 Rename navigation title option
  src/Settings.php
Labels: Review, [Test Env] rhea

#1600 PLANET-6611 Hide post type in admin listings
  functions.php
Labels: Review, [Test Env] pluto

#1601 PLANET-6614: Save post tags as ordered
  src/MasterSite.php
Labels: [Test Env] proteus

#1607 PLANET-6589: Fix search error when act page not selected
  src/ElasticSearch.php
  src/Search.php
Labels: [Test Env] mars

#1591 PLANET-6510: Navigation bar - Tabs menu on mobile
  assets/src/js/header.js
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/_page-header.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/layout/navbar/_site-logo.scss
  assets/src/scss/layout/navbar/mobile.scss
  assets/src/scss/pages/_page.scss
  assets/src/scss/partials/navigation-bar-light.scss
  src/MasterSite.php
  src/Settings.php
  src/Settings/InformationArchitecture.php
  templates/navigation-bar-new.twig
Labels: UAT Passed, [Test Env] tavros

#1614 Add toggle to allow all blocks on development environments
  src/Features.php
Labels: Review, [Test Env] tavros

#1603 PLANET-6496: HappyPoint global switch and default content
  src/Settings.php
Labels: [Test Env] pluto

#1617 Show redirect_page in tag list
  src/Campaigns.php
Labels: [Test Env] atlas

#1610 PLANET-6440: Remove unused related articles settings
  src/Migrations/M008RemoveArticlesDefaultOptions.php
  src/Migrator.php
  src/Settings.php
Labels: [Test Env] tavros

#1622 PLANET-6615: Make Global project field non mandatory
  tests/acceptance/campaign.feature
Labels: [Test Env] proteus

#1599 PLANET-6480 Disable CSS Customizer on production
  src/MasterSite.php
Labels: Review, [Test Env] umbriel

#1613 PLANET-6515 Add new Action page type and Action Type taxonomy
  single-p4_action.php
  src/ActionPage.php
  src/Loader.php
  src/Settings/InformationArchitecture.php
Labels: Review, [Test Env] mars

#1625 Fix navbar search position in large screens
  assets/src/scss/layout/navbar/_search.scss
Labels: Review, [Test Env] sinope

#1624 PLANET-6644: Set cookies settings from cookies block data
  src/Migrations/M009PopulateCookiesFields.php
  src/Migrator.php
Labels: [Test Env] jupiter

#1580 PLANET-6075 Add settings to Cookies box
  assets/src/js/cookies.js
  assets/src/scss/layout/_cookies-settings.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/style.scss
  src/MasterSite.php
  src/Settings.php
  templates/cookies.twig
  templates/cookies/cookies_settings.twig
  tests/acceptance/CookiesBannerCept.php
Labels: Review, UAT Passed

#1629 PLANET-6648 Add object tag on Posts
  src/MasterSite.php
Labels: Review, [Test Env] sinope
