Repository greenpeace/planet4-master-theme, pull requests merged in 2022-09, with the labels that each got.

#1785 Add BrowserStack notice
  README.md
Labels: Review, [Test Env] pandora

#1784 PLANET-6890 Add meta field to hide page title in Actions
  src/ActionPage.php
Labels: Review, UAT Passed, [Test Env] telesto

#1791 PLANET-6405 Fix download icon not showing in later search results
  assets/src/js/pdf_icon.js
  src/Search.php
  templates/tease-search.twig
Labels: Review, [Test Env] pluto

#1773 PLANET-6527: Style the default 'all posts' listing page
  assets/src/js/load_more.js
  functions.php
  index.php
  src/Search.php
  templates/all-posts.twig
Labels: Review, UAT Passed, [Test Env] tavros

#1793 PLANET-6912 Fix site name appearing twice in author page title
  author.php
Labels: [Test Env] telesto

#1790 PLANET-6897 Fix scroll to top bug when opening side menu
  assets/src/js/header.js
  assets/src/scss/layout/_navbar.scss
Labels: Review, [Test Env] oberon

#1794 PLANET-6867 Fix Gravity form file path before output
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] rhea

#1795 PLANET-6907 Update Gravity Forms settings initial values
  src/GravityFormsExtensions.php
Labels: Review, UAT Passed, [Test Env] phoebe

#1798 Fix Gravity Forms settings function name
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] janus

#1797 PLANET-6891 Action post type enable the Opengraph metabox
  src/MetaboxRegister.php
Labels: Review, [Test Env] neptune

#1802 PLANET-6915 Remove wp_kses_post filter from post content
  templates/single.twig
Labels: Review

#1801 PLANET-6908 Remove Cookies box slide animation
  assets/src/scss/layout/_cookies.scss
Labels: Review, [Test Env] iocaste, [Test Env] venus

#1800 Check if share platforms are set for GF confirmation message
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] mars

#1806 PLANET-6780 Remove unused transparent-button class
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
Labels: Review, [Test Env] titan

#1807 Return current GF confirmation if no corresponding one is found
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] phoebe

#1808 Fix Gravity Forms confirmations filtering
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] janus
