Repository greenpeace/planet4-master-theme, pull requests merged in 2022-03, with the labels that each got.

#1636 PLANET-6656 Hide Follow us link when no social media links
  assets/src/scss/layout/_footer-social-media.scss
  templates/footer.twig
Labels: Review

#1637 PLANET-6647: Youtube Embed - block not showing in the editor
  assets/src/scss/editorStyle.scss
  src/MasterSite.php
Labels: [Test Env] atlas

#1641 PLANET-6663 Fix password input width on mobile
  assets/src/scss/pages/_page.scss
Labels: Review, [Test Env] saturn

#1638 PLANET-6555 Style Gravity Forms
  assets/src/scss/editorStyle.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_gravity-forms.scss
  assets/src/scss/style.scss
Labels: Review, UAT Passed, [Test Env] nix

#1639 PLANET-6465: Add opt-in checkbox for submitting the comments form
  assets/src/scss/pages/post/_comments-form.scss
  single.php
  src/Migrations/M010RemoveGdprPluginOptions.php
  src/Migrator.php
  src/Settings.php
  src/Settings/Comments.php
  templates/comment_form/submit_button.twig
Labels: [Test Env] rhea

#1647 Revert "PLANET-6555 Style Gravity Forms"
  assets/src/scss/editorStyle.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_gravity-forms.scss
  assets/src/scss/style.scss
Labels: [Test Env] saturn

#1630 PLANET-6513 Implement the new post tags
  assets/src/scss/components/_buttons.scss
  assets/src/scss/pages/post/_post.scss
  templates/blocks/author_profile.twig
  templates/single-attachment.twig
  templates/single-password.twig
  templates/single.twig
Labels: Review, UAT Passed, [Test Env] phobos

#1644 PLANET-6659 Fix Download file button styles
  assets/src/scss/components/_buttons.scss
Labels: Review

#1646 Unwrap cookies CSS
  assets/src/scss/components/_buttons.scss
  assets/src/scss/layout/_cookies-settings.scss
  assets/src/scss/layout/_cookies.scss
  templates/cookies.twig
Labels: Review, [Test Env] oberon

#1649 Remove unused function add_terms_as_rewrite_rules
  src/CustomTaxonomy.php
Labels: Review, [Test Env] rhea

#1650 Use a class per feature
  src/AnalyticsValues.php
  src/Commands/CloudflarePurge.php
  src/Feature.php
  src/Features.php
  src/Features/CloudflareDeployPurge.php
  src/Features/Dev/AllowAllBlocks.php
  src/Features/Dev/BetaBlocks.php
  src/Features/Dev/CoreBlockPatterns.php
  src/Features/Dev/ThemeEditor.php
  src/Features/Dev/WPTemplateEditor.php
  src/Features/EngagingNetworks.php
  src/Features/GoogleSheetReplacesSmartsheet.php
  src/Features/ImageArchive.php
  src/Features/LazyYoutubePlayer.php
  src/Features/NewDesignCountrySelector.php
  src/Features/NewDesignNavigationBar.php
  src/Features/PurgeOnFeatureChanges.php
  src/ImageArchive/Rest.php
  src/ImageArchive/UiIntegration.php
  src/MasterSite.php
  src/Migrations/M001EnableEnFormFeature.php
  src/Migrations/M002EnableLazyYoutube.php
  src/PublicAssets.php
  src/Settings.php
Labels: Review, [Test Env] titan

#1653 Reverse logic on template editor feature
  src/MasterSite.php
Labels: Review, [Test Env] sinope

#1652 Move Features into Settings\Features
  load-class-aliases.php
  src/ImageArchive/Rest.php
  src/ImageArchive/UiIntegration.php
  src/Loader.php
  src/Migrations/M006MoveFeaturesToSeparateOption.php
  src/Notifications/Slack.php
  src/Settings.php
  src/Settings/Features.php
Labels: Review, [Test Env] venus

#1651 PLANET-6668 Implement Highlighted CTA pattern
  assets/src/scss/base/_colors.scss
  assets/src/scss/base/_palette.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
Labels: Review, UAT Passed

#1655 PLANET-6668 Remove dark green color from our palette
  assets/src/scss/base/_colors.scss
  assets/src/scss/base/_palette.scss
Labels: Review, UAT Passed

#1658 PLANET-6696 Add white color to visited primary buttons
  assets/src/scss/components/_buttons.scss
Labels: Review, [Test Env] oberon
