Repository greenpeace/planet4-master-theme, pull requests merged in 2022-08, with the labels that each got.

#1761 PLANET-6860: Update the tag page
  tag.php
Labels: Review, [Test Env] venus

#1765 Add spacing feature to theme
  theme.json
Labels: Review, [Test Env] phoebe

#1763 PLANET-6569 Add form type field in Gravity form settings
  src/GravityFormsExtensions.php
  src/Loader.php
Labels: Review, UAT Passed, [Test Env] nix

#1759 PLANET-6724: Improve pagination UI
  assets/src/scss/layout/_block-classes.scss
  src/Features/Dev/DisableTagRedirectPages.php
  src/Features/ListingPagePagination.php
  src/Settings/Features.php
  src/Settings/InformationArchitecture.php
Labels: Review, UAT Passed, [Test Env] pandora

#1767 Implement new spacing values
  theme.json
Labels: Review, [Test Env] deimos

#1769 Add border radius feature to theme
  theme.json
Labels: Review, [Test Env] iocaste

#1775 Fix notice on undefined $filename variable
  src/PublicAssets.php
Labels: [Test Env] oberon

#1778 PLANET-6873: Fix the color of links from footer
  assets/src/scss/layout/_footer.scss
Labels: Review, UAT Passed, [Test Env] janus

#1780 PLANET-6895: Use open graph title for title tag
  templates/blocks/title.twig
Labels: [Test Env] titan

#1782 PLANET-6861 Add tooltip to P4 form type setting for Gravity Forms
  src/GravityFormsExtensions.php
Labels: Review, UAT Passed, [Test Env] umbriel
