Repository greenpeace/planet4-master-theme, pull requests merged in 2022-05, with the labels that each got.

#1700 PLANET-6760 Prepare to fix search box position
  templates/desktop-menu.twig
  templates/navigation-bar-new.twig
  templates/search-form.twig
Labels: Review, [Test Env] iocaste

#1681 PLANET-6697: Fire consent before gtm starts
  assets/src/js/cookies.js
  src/MasterSite.php
  templates/blocks/google_tag_manager.twig
Labels: UAT Passed, [Test Env] tavros

#1701 Move duplicated language switcher code to separate file
  templates/burger-menu.twig
  templates/desktop-menu.twig
  templates/language-switcher.twig
Labels: [Test Env] deimos

#1703 PLANET-6760 Restore search bar position
  assets/src/scss/layout/_navbar.scss
  templates/desktop-menu.twig
  templates/navigation-bar-new.twig
Labels: [Test Env] deimos

#1704 PLANET-6765 Fix slide in direction of mobile menu on RTL
  assets/src/scss/layout/navbar/_burger-menu.scss
Labels: Review, [Test Env] iocaste

#1697 PLANET-6727 Update search results UI
  assets/src/scss/pages/search/_search-results.scss
  templates/tease-author.twig
  templates/tease-search.twig
  templates/tease-taxonomy-post.twig
Labels: Review, UAT Passed, [Test Env] leda

#1705 Ensure unique HTTPS URLs get purged
  src/CloudflarePurger.php
Labels: Review, [Test Env] iocaste

#1707 Add share icon
  assets/src/images/icons/share.svg
Labels: Review, [Test Env] iocaste

#1698 PLANET-6725 Remove listing pages background and overlay
  src/Campaigns.php
  src/Features/HideListingPagesBackground.php
  src/Settings/InformationArchitecture.php
  tag.php
  templates/blocks/header.twig
  templates/tag.twig
Labels: Review, UAT Passed, [Test Env] pluto

#1708 Add new placeholder images
  images/placeholders/placeholder-40x40.jpg
  images/placeholders/placeholder-546 x415.jpg
  images/placeholders/placeholder-75x75.jpg
  images/placeholders/placeholder-80x80.jpg
Labels: Review, [Test Env] sinope

#1712 Add feature flag to disable automated data sync
  src/Features/Dev/DisableDataSync.php
  src/Settings/Features.php
Labels: Review, [Test Env] sinope

#1713 PLANET-6755 Update GF forms max width specification
  assets/src/scss/layout/_gravity-forms.scss
Labels: Review, UAT Passed, [Test Env] saturn

#1710 PLANET-6775: Add chevron icon to the languages nav
  assets/src/scss/layout/navbar/languages.scss
  assets/src/scss/partials/navigation-bar-light.scss
Labels: UAT Passed, [Test Env] pluto

#1714 PLANET-6712 Add transparent style to core Button block
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
Labels: Review, UAT Passed, [Test Env] titan

#1711 PLANET-6776: Change languages dropdown menu condition
  templates/burger-menu.twig
  templates/navigation-bar-new.twig
Labels: Review, UAT Needed

#1716 PLANET-6767: Remove control panel overlay blocking clicks
  admin/css/dashboard.css
  src/ControlPanel.php
Labels: [Test Env] telesto

#1718 Add Grey 5% to our color palette
  assets/src/scss/base/_palette.scss
Labels: Review, [Test Env] iocaste

#1719 PLANET-6788 Define color palette in theme.json
  theme.json
Labels: Review, [Test Env] rhea

#1720 PLANET-6784 Remove WP default color palette
  assets/src/scss/base/_palette.scss
  theme.json
Labels: Review, [Test Env] titan

#1721 PLANET-6749: Display hard-coded list when Global projects sheet fails
  src/AnalyticsValues.php
Labels: [Test Env] oberon

#1722 PLANET-6784 Remove color duotone functionality
  theme.json
Labels: Review, [Test Env] titan

#1725 PLANET-6800: Fix title and intro text width
  assets/src/scss/layout/_page-header.scss
Labels: Review, UAT Needed, [Test Env] saturn
