Repository greenpeace/planet4-master-theme, pull requests merged in 2022-10, with the labels that each got.

#1811 PLANET-5872 Run a11y against test instances
  .circleci/config.yml
Labels: Review, [Test Env] neptune

#1803 PLANET-6901 Remove Page Header metabox fields
  src/Loader.php
  src/MetaboxRegister.php
  src/Page.php
  src/PostCampaign.php
Labels: Review, UAT Passed

#1824 PLANET-4444 Add meta field for Action button text
  src/ActionPage.php
  src/Search.php
  templates/tease-search.twig
Labels: Review, UAT Passed, [Test Env] titan

#1825 PLANET-6678 Alphabetically order Planet 4 settings menu
  functions.php
Labels: Review, [Test Env] saturn
