Repository greenpeace/planet4-master-theme, pull requests merged in 2022-06, with the labels that each got.

#1640 PLANET-6619 Ensure "redirect page" has no duplicate URL by redirecting to the tag URL it's overriding
  page.php
  src/Features/RedirectRedirectPages.php
  src/Settings/Features.php
Labels: Review, [Test Env] umbriel

#1730 Add schema link to theme.json
  theme.json
Labels: Review

#1723 PLANET-6773: Fix WP importer fetches media along with posts
  exporter-helper.php
  src/Importer.php
Labels: Review, [Test Env] tavros

#1728 Apply filter to youtube embed parameters
  src/MasterSite.php
Labels: [Test Env] phobos

#1695 PLANET-6805: Change donate button text through the burger menu
  src/MasterSite.php
  templates/burger-menu.twig
Labels: Review, [Test Env] deimos

#1717 Add image placeholders for new block patterns
  images/placeholders/placeholder-180x180.jpg
  images/placeholders/placeholder-90x90.jpg
Labels: Review, UAT Passed, [Test Env] saturn

#1733 PLANET-6887 Fix placeholder color for Button block
  assets/src/scss/editorOverrides.scss
Labels: Review

#1735 PLANET-6789 Add pointer-events none to animated form field labels
  assets/src/scss/layout/_forms.scss
Labels: Review, [Test Env] sinope

#1691 PLANET-6652: Extract search filters
  src/ElasticSearch.php
  src/Search.php
  src/Search/Filters/ActionTypes.php
  src/Search/Filters/Categories.php
  src/Search/Filters/ContentTypes.php
  src/Search/Filters/PostTypes.php
  src/Search/Filters/Tags.php
  templates/search.twig
Labels: Review, [Test Env] phobos

#1740 PLANET-6811 Remove default duotones
  theme.json
Labels: Review, [Test Env] iocaste

#1739 PLANET-6744 Make listing pages author name bold
  assets/src/scss/pages/search/_search-results.scss
Labels: Review, UAT Passed, [Test Env] pluto

#1742 PLANET-6325 Add padding top to pages with no title
  assets/src/scss/pages/_page.scss
  templates/page.twig
Labels: Review, [Test Env] umbriel

#1743 PLANET-6822 Fix author block image margins
  assets/src/scss/pages/post/_author-block.scss
Labels: Review, [Test Env] deimos

#1744 Fix WP importer error with wp-stateless 3.2
  functions.php
Labels: Review

#1738 PLANET-6794: Fix languges switcher through the navigation bar
  assets/src/js/menu_editor.js
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/languages.scss
Labels: Review, UAT Passed, [Test Env] rhea

#1741 Allow articles block in posts
  assets/src/scss/pages/post/_article-content.scss
Labels: Review, UAT Passed, [Test Env] leda

#1749 PLANET-6831: Fix PDF attachment links missing in attachment pages
  functions.php
Labels: [Test Env] phobos

#1750 Allow box-orient to be vendor prefixed
  .stylelintrc
  assets/src/js/menu_editor.js
Labels: Review, [Test Env] janus

#1747 PLANET-6803: Add Gravity Forms Capabilities for Editors
  src/Activator.php
  src/Role/GravityForms.php
Labels: Review, [Test Env] deimos
