Repository greenpeace/planet4-master-theme, pull requests merged in 2023-04, with the labels that each got.

#1962 PLANET-7003 Implement client-side dynamic population on form fields
  assets/src/js/gravityforms-client-side.js
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] pandora

#1968 Add new identity colors to our color palette
  functions.php
Labels: Review, UAT Passed, [Test Env] pandora

#1971 PLANET-7022 Apply new identity colors to transparent buttons
  assets/src/scss/base/_palette.scss
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] janus

#1969 Convert navbar variables to CSS variables
  assets/src/scss/base/_css-variables.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/layout/navbar/_site-logo.scss
  assets/src/scss/layout/navbar/languages.scss
  assets/src/scss/pages/_page.scss
Labels: Review

#1976 Fix Donate button dropdown arrow color
  assets/src/scss/layout/_navbar.scss
Labels: Review, [Test Env] telesto

#1972 PLANET-7119: Infinite scrolling of Covers block
  assets/src/scss/bootstrap-build.scss
  package-lock.json
  package.json
Labels: [Test Env] deimos, [Test Env] atlas

#1981 PLANET-7125: Fix filemtime() warning issue on GF Client Side file
  src/GravityFormsExtensions.php
Labels: Review

#1964 PLANET-7106 Implement ESLint config in Master Theme
  .eslintrc.json
  assets/src/js/Components/ArchivePicker.js
  assets/src/js/Components/archivePicker/ArchivePickerList.js
  assets/src/js/Components/archivePicker/MultiSidebar.js
  assets/src/js/Components/archivePicker/SingleSidebar.js
  assets/src/js/Components/archivePicker/sizeFunctions.js
  assets/src/js/Components/archivePicker/useImages.js
  assets/src/js/app.js
  assets/src/js/archive_picker.js
  assets/src/js/cookies.js
  assets/src/js/external_links.js
  assets/src/js/gravityforms-client-side.js
  assets/src/js/header.js
  assets/src/js/load_more.js
  assets/src/js/menu_editor.js
  assets/src/js/pdf_icon.js
  assets/src/js/search.js
  package-lock.json
  package.json
Labels: Review

#1983 Adjust GF redirection message
  src/GravityFormsExtensions.php
Labels: Review

#1970 PLANET-7016 Apply the new colors to the Table block
  assets/src/scss/base/_colors.scss
  assets/src/scss/layout/_tables.scss
  assets/src/scss/new-identity/style.scss
  functions.php
Labels: Review, UAT Passed, [Test Env] saturn

#1975 Remove 404 and cookiebanner codeception tests
  tests/acceptance/404PageCept.php
  tests/acceptance/CookiesBannerCept.php
Labels: Review, [Test Env] phoebe

#1978 PLANET-7019 Remove navigation bar dark style for new identity
  src/PublicAssets.php
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] telesto

#1974 PLANET-7014 Apply new identity colors to Accordion block
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed

#1979 PLANET-6996 Apply new identity colors to the navigation bar
  assets/src/scss/layout/navbar/_burger-menu.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/layout/navbar/languages.scss
  assets/src/scss/new-identity/style.scss
  assets/src/scss/partials/navigation-bar-light.scss
Labels: Review, UAT Passed, [Test Env] deimos

#1965 PLANET-6994: Implement new identity colors to standalone links
  assets/src/scss/new-identity/style.scss
Labels: UAT Passed, [Test Env] nix

#1984 PLANET-7062 Rewrite country selector test with Playwright
  tests/acceptance/HomePageCept.php
  tests/e2e/country-selector.spec.js
Labels: Review, [Test Env] telesto

#1986 Add empty text case to cookie notice e2e test
  tests/e2e/cookies-banner.spec.js
Labels: [Test Env] telesto

#1995 Design Tokens: New release [v0.11.1]
  assets/src/scss/base/_tokens.scss
Labels: [Test Env] deimos, Design Tokens

#1994 PLANET-7109 Disable GFTrackEvent
  src/GravityFormsExtensions.php
Labels: Review, UAT Needed, [Test Env] telesto

#1977 PLANET-6975 Disable Background updates check in Site health.
  src/MasterSite.php
Labels: Review, [Test Env] atlas

#1955 PLANET-6990 Apply the new style to body copy links
  assets/src/scss/new-identity/style.scss
  tests/e2e/404.spec.js
Labels: Review, UAT Passed, [Test Env] tavros

#1959 PLANET-6998: Apply new colors to comments block
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/post/_comments-form.scss
Labels: Review, UAT Passed, [Test Env] proteus

#1999 Fix reading time translation in listing pages
  src/Post.php
Labels: Review, [Test Env] neptune
