Repository greenpeace/planet4-master-theme, pull requests merged in 2023-12, with the labels that each got.

#2153 PLANET-7192 Enable elasticpress search query on admin ajax request
  src/Search.php
Labels: Review, [Test Env] oberon

#2165 PLANET-7363 Fix admin media library search issue
  src/Search.php
Labels: Review, [Test Env] phobos

#2159 PLANET-7277 Listing pages: add a featured Action section
  assets/src/scss/layout/_featured-action.scss
  assets/src/scss/style.scss
  category.php
  tag.php
  templates/featured-action.twig
  templates/tag.twig
  templates/taxonomy.twig
Labels: Review, UAT Needed, [Test Env] venus

#2168 Fix Gravity Forms confirmation text test
  tests/e2e/gravity-forms.spec.js
Labels: Review, [Test Env] pluto

#2166 Capture errors on google client instantiation
  src/AnalyticsValues.php
  src/GoogleDocsClient.php
Labels: [Test Env] atlas

#2174 Idea: Create block-editor directory for components
  assets/src/block-editor/ImagePlaceholderIcon/ImagePlaceholderIcon.js
  assets/src/block-editor/URLInput/URLInput.js
  assets/src/block-editor/URLValidationMessage/URLValidationMessage.js
Labels: Review, [Test Env] atlas

#2177 Maintenance: Add functions directory from plugin into the theme
  assets/src/functions/hydrateBlock.js
Labels: [Test Env] pluto

#2175 Fix warnings on PHP8
  index.php
  page-templates/evergreen.php
  search.php
  single-campaign.php
  single-p4_action.php
  src/MediaArchive/ApiClient.php
  src/Post.php
  src/Search.php
Labels: [Test Env] iocaste

#2147 PLANET-6795: Fix top spacing of Media and Text
  assets/src/scss/pages/_page.scss
Labels: Review

#2171 PLANET-7301: Move Carousel Header block into master theme
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/CarouselHeader/CarouselControls.js
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditorScript.js
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
  assets/src/blocks/CarouselHeader/EditableBackground.js
  assets/src/blocks/CarouselHeader/ImagePlaceholder.js
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/blocks/CarouselHeader/SidebarSlide.js
  assets/src/blocks/CarouselHeader/Slide.js
  assets/src/blocks/CarouselHeader/SlideBackground.js
  assets/src/blocks/CarouselHeader/StaticCaption.js
  assets/src/blocks/CarouselHeader/deprecated/carouselHeaderV1.js
  assets/src/blocks/CarouselHeader/useSlides.js
  assets/src/scss/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
  assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/scss/blocks/CarouselHeader/SidebarSlidesEditor.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
  images/carousel-blurred-overlay.png
  src/Blocks/CarouselHeader.php
  src/Loader.php
  webpack.config.js
Labels: Review, [Test Env] neptune

#2170 PLANET-7276 Add a 'back to News & stories' link to listing pages
  assets/src/scss/layout/_breadcrumbs.scss
  category.php
  src/Context.php
  tag.php
  taxonomy.php
  templates/tag.twig
  templates/taxonomy.twig
Labels: Review, UAT Passed, [Test Env] oberon

#2173 PLANET-7300: Move Accordion block into master theme
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Accordion/AccordionEditorScript.js
  assets/src/blocks/Accordion/AccordionFrontend.js
  assets/src/blocks/Accordion/AccordionScript.js
  assets/src/scss/blocks/Accordion/AccordionEditorStyle.scss
  assets/src/scss/blocks/Accordion/AccordionStyle.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
  src/Blocks/Accordion.php
  src/Loader.php
  webpack.config.js
Labels: Review, [Test Env] phobos

#2181 Media Archive: include new close button
  admin/css/archive-picker.css
  assets/src/js/Components/ArchivePicker/MultiSearchOption.js
  assets/src/js/Components/ArchivePicker/SingleSidebar.js
  assets/src/scss/editorOverrides.scss
  images/arrow-right.svg
Labels: Review, [Test Env] atlas

#2179 Guestbook: Change package name of class
  src/Blocks/GuestBook.php
Labels: Review, [Test Env] venus

#2167 PLANET-7302 Move Cookies block into master theme
  assets/src/blocks/Cookies/CookiesBlock.js
  assets/src/blocks/Cookies/CookiesEditor.js
  assets/src/blocks/Cookies/CookiesEditorScript.js
  assets/src/blocks/Cookies/CookiesFieldResetButton.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/blocks/Cookies/CookiesScript.js
  assets/src/blocks/Cookies/useCookie.js
  assets/src/blocks/components/FrontendRichText/FrontendRichText.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Cookies/CookiesEditorStyle.scss
  assets/src/scss/blocks/Cookies/CookiesStyle.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
  src/Blocks/Cookies.php
  src/Loader.php
  src/MasterBlocks.php
  webpack.config.js
Labels: Review, [Test Env] janus
