Repository greenpeace/planet4-master-theme, pull requests merged in 2023-08, with the labels that each got.

#2076 PLANET-7047: Migrate Donate button setting to a menu
  src/MasterSite.php
  src/Migrations/M018MigrateDonateButtonSetting.php
  src/Migrator.php
  src/Settings.php
  templates/burger-menu.twig
Labels: [Test Env] atlas

#2082 PLANET-7046: Align tag listing page with new design
  tag.php
  templates/tag.twig
Labels: [Test Env] deimos

#2087 PLANET-7102 Add categories DLV on Posts
  page.php
  single-campaign.php
  single-p4_action.php
  single.php
  templates/blocks/google_tag_manager.twig
Labels: Review, UAT Passed, [Test Env] atlas

#2070 Update Browserslist DB
  package-lock.json
Labels: [Test Env] neptune

#2086 PLANET-7137: Add and EOL date on new identity feature flag
  src/MasterSite.php
Labels: Review, [Test Env] janus

#2077 PLANET-6646 Write an e2e test for the navigation bar
  package-lock.json
  package.json
  tests/e2e/navigation-bar.spec.js
Labels: Review, [Test Env] iocaste

#2089 PLANET-7210: Rewrite search test independent of content
  src/MasterSite.php
  tests/e2e/search.spec.js
Labels: [Test Env] jupiter

#2092 PLANET-7216: Fix error on tag page
  tag.php
Labels: [Test Env] iocaste

#2090 PLANET-7209: Move Reading Time option to Reading settings
  src/CustomTaxonomy.php
  src/Loader.php
  src/Migrations/M019MigrateReadingTime.php
  src/Post.php
  src/Post/ReadingTimeCalculator.php
  src/Settings.php
  src/Settings/ReadingTime.php
Labels: [Test Env] atlas

#2093 Add CSS variable for the burger menu color
  assets/src/scss/layout/navbar/_burger-menu.scss
Labels: Review, [Test Env] janus

#2079 PLANET-7159 Add help tooltip to Media Archive
  admin/css/picker.css
  assets/src/js/Components/ArchivePicker.js
Labels: Review, UAT Passed, [Test Env] telesto

#2096 PLANET-7222 Fix Donate button menu dropdown alignment
  assets/src/scss/layout/_navbar.scss
Labels: Review, UAT Passed, [Test Env] leda

#2094 PLANET-7177 Move Default P4 Post Type setting under Settings > Writing
  src/CustomTaxonomy.php
  src/Loader.php
  src/Migrations/M021MigrateDefaultPostType.php
  src/Migrator.php
  src/Settings.php
  src/Settings/DefaultPostType.php
Labels: Review, [Test Env] iocaste

#2091 Implement CSS variables to font families
  assets/src/scss/base/_css-variables.scss
  assets/src/scss/base/_variables.scss
  assets/src/scss/new-identity/style.scss
Labels: Review, [Test Env] leda

#2101 Add template include for custom scripts
  templates/html-header.twig
Labels: Review, [Test Env] leda

#2095 PLANET-7215 Apply the new design to the Submenu block
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] oberon

#2084 PLANET-7117: Implment Bulk Select / Bulk Import in the media archive
  admin/css/picker.css
  assets/src/js/Components/ArchivePicker.js
  assets/src/js/Components/ArchivePicker/ArchivePicker.js
  assets/src/js/Components/ArchivePicker/ArchivePickerList.js
  assets/src/js/Components/ArchivePicker/ArchivePickerToolbar.js
  assets/src/js/Components/ArchivePicker/MultiSearchOption.js
  assets/src/js/Components/ArchivePicker/MultiSidebar.js
  assets/src/js/Components/ArchivePicker/SingleSidebar.js
  assets/src/js/Components/ArchivePicker/sizeFunctions.js
  assets/src/js/Components/archivePicker/ArchivePickerList.js
  assets/src/js/Components/archivePicker/MultiSidebar.js
  assets/src/js/Components/archivePicker/SingleSidebar.js
  assets/src/js/media_archive.js
Labels: Review, UAT Passed, [Test Env] neptune

#2102 PLANET-7225: Fix font family for headings, links and body text
  assets/src/scss/base/_css-variables.scss
Labels: Review, [Test Env] atlas

#2085 PLANET-6793: Sitemap native taxonomies
  assets/src/scss/pages/_sitemap.scss
  page-templates/sitemap.php
  templates/sitemap.twig
Labels: UAT Passed, [Test Env] mars

#2104 Modify the children alignment within the donate nav
  assets/src/scss/layout/_navbar.scss
Labels: [Test Env] atlas

#2105 Fix Sitemap links
  assets/src/scss/pages/_sitemap.scss
  page-templates/sitemap.php
  templates/sitemap.twig
Labels: [Test Env] pandora

#2107 Update Playwright version
  .circleci/config.yml
  package-lock.json
  package.json
Labels: [Test Env] nix
