Repository greenpeace/planet4-master-theme, pull requests merged in 2023-11, with the labels that each got.

#2143 PLANET-7291: Replace Twitter icon with X
  assets/src/images/icons/twitter-square.svg
  assets/src/images/icons/twitter.svg
  assets/src/scss/base/_colors.scss
Labels: [Test Env] atlas

#2144 Maintenance: Upgrade the lite-youtube-embed npm library
  package-lock.json
  package.json
Labels: Review, [Test Env] phobos

#2150 PLANET-7275 Update login button color to reflect new visual identity
  admin/css/login.css
Labels: Review, [Test Env] saturn

#2151 PLANET-7333: Fix author avatar URL trimmed
  templates/author.twig
  templates/blocks/author_profile.twig
Labels: [Test Env] pluto

#2145 PLANET-7320: Migrate old colors from palette
  src/Migrations/M026ReplaceDeprecatedColorsFromContent.php
  src/Migrator.php
Labels: Review, [Test Env] titan

#2149 PLANET-7251 Build an Actions List block
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/editorIndex.js
  assets/src/blocks/styles/blocks.scss
  assets/src/blocks/styles/blocks/Guestbook.scss
  assets/src/blocks/styles/editorOverrides.scss
  assets/src/blocks/styles/editorStyle.scss
  assets/src/blocks/styles/style.scss
  assets/src/scss/blocks/ActionsList.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
  src/Loader.php
  src/MasterBlocks.php
  webpack.config.js
Labels: Review

#2155 Add missing first-child selector to remove margin top
  assets/src/scss/pages/_page.scss
Labels: Review, [Test Env] umbriel

#2156 Fix regex to get YouTube video id for shorts
  src/MasterSite.php
Labels: Review, [Test Env] pandora

#2158 PLANET-7340: Make Post title mandatory for publishing
  src/MasterSite.php
Labels: [Test Env] pluto
