Repository greenpeace/planet4-master-theme, pull requests merged in 2023-01, with the labels that each got.

#1852 PLANET-6936 Remove jQuery from frontend
  package-lock.json
  package.json
  src/PublicAssets.php
Labels: Review, [Test Env] neptune

#1848 PLANET-6957 Remove action-type string from Action Type permalink url & Use Action Type slug on Actions permalink url
  src/ActionPage.php
Labels: Review, [Test Env] leda

#1876 Add CSS variables for typography settings in theme file
  theme.json
Labels: [Test Env] mars

#1864 PLANET-6981 Remove jQuery from post_tag.js
  admin/css/post_tag.css
  admin/js/post_tag.js
  src/Campaigns.php
Labels: Review

#1878 Add font-family css variables
  assets/src/scss/base/_body.scss
  assets/src/scss/base/_variables.scss
  assets/src/scss/components/_blockquote.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/layout/_breadcrumbs.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/layout/_footer.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_gravity-forms.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/_page-header.scss
  assets/src/scss/layout/_page-section.scss
  assets/src/scss/layout/_tables.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
  assets/src/scss/pages/_author.scss
  assets/src/scss/pages/_category.scss
  assets/src/scss/pages/_listing-page.scss
  assets/src/scss/pages/_page_type.scss
  assets/src/scss/pages/_sitemap.scss
  assets/src/scss/pages/post/_article-content.scss
  assets/src/scss/pages/post/_comments-block.scss
  assets/src/scss/pages/post/_comments-form.scss
  assets/src/scss/pages/post/_post.scss
  assets/src/scss/pages/search/_filtered-tags.scss
  assets/src/scss/pages/search/_search-results.scss
Labels: Review, [Test Env] neptune

#1883 Fix copyright values from Media Library
  src/ImageArchive/ApiClient.php
  src/ImageArchive/Image.php
Labels: Review, [Test Env] phobos

#1884 PLANET-7027: Fix tag listing page
  tag.php
Labels: Review, [Test Env] iocaste

#1882 PLANET-6964 Remove background image on listing pages by default
  languages/planet4-master-theme-backend.pot
  src/Campaigns.php
  src/Features/HideListingPagesBackground.php
  src/Migrations/M015RemoveListingPagesBackgroundImages.php
  src/Migrator.php
  src/Settings/InformationArchitecture.php
  tag.php
  templates/tag.twig
Labels: Review, [Test Env] rhea

#1887 PLANET-6982 Clean up tmp files
  languages/plugins/gravityforms/gravityforms-el-backup-202301270835480.po~
  languages/plugins/gravityforms/gravityforms-hi_IN-backup-202301270653230.po~
  languages/plugins/gravityforms/gravityforms-hi_IN-backup-202301270655530.po~
  languages/plugins/gravityforms/index.php
Labels: Review

#1888 Add rel="me" on footer social icon links
  templates/footer_social_media.twig
Labels: Review, [Test Env] leda

#1889 Enable Opengraph metadata for tag listing pages
  languages/planet4-master-theme-backend.pot
  tag.php
  templates/blocks/meta_fields.twig
Labels: Review, [Test Env] titan

#1805 PLANET-6864 Clean up unused json files generated by Loco translation …
  languages/de_CH-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/de_CH-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-ar-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-bg_BG-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-cs_CZ-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-cs_CZ-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-da_DK-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-da_DK-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-de_DE-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-el-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-el-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-en_GB-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-en_US-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-es_AR-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-es_AR-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-es_CO-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-es_MX-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-es_MX-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-fi-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-fi-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-fr_CA-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-fr_CA-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-fr_FR-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-fr_FR-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-he_IL-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-hi_IN-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-hr-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-hu_HU-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-hu_HU-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-id_ID-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-it_IT-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-ja-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-ja-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-kl-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-ko_KR-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-nb_NO-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-nb_NO-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-nl_NL-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-nl_NL-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-pl_PL-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-pt_BR-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-pt_BR-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-sk_SK-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-sl_SI-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-sl_SI-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-sv_SE-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-sv_SE-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-th-e2c3e9cc63e3e76d21e33a2979354e21.json
  languages/planet4-master-theme-tr_TR-8a22d9364aa6037d4d83c107cc6bfde6.json
  languages/planet4-master-theme-tr_TR-e2c3e9cc63e3e76d21e33a2979354e21.json
Labels: Review

#1886 PLANET-7029 Add default action type, if no action type added
  src/ActionPage.php
  src/Migrations/M016CreateDefaultActionType.php
  src/Migrator.php
Labels: Review, [Test Env] oberon

#1899 PLANET-7056 Change form attributes to enforce Ajax submission
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] iocaste
