Repository greenpeace/planet4-master-theme, pull requests merged in 2023-03, with the labels that each got.

#1914 PLANET-7020 Add new site identity feature toggle
  assets/src/scss/base/_css-variables.scss
  assets/src/scss/base/_variables.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/new-identity/style.scss
  assets/src/scss/style.scss
  src/MasterSite.php
  src/PublicAssets.php
  src/Settings.php
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] phobos

#1944 Fix tag creation when certain fields are missing
  src/Campaigns.php
Labels: Review, [Test Env] phobos

#1941 PLANET-6977 Hide WPML footer language switcher
  admin/css/wpml.css
  assets/src/scss/style.scss
  src/ControlPanel.php
Labels: Review, [Test Env] rhea

#1875 PLANET-7012 Completely remove jQuery from frontend
  src/PublicAssets.php
Labels: [Test Env] titan

#1946 PLANET-6970 WPML option disabling access to WordPress admin panel
  admin/css/wpml.css
Labels: Review, [Test Env] rhea

#1948 PLANET-6992 Update footer background colors for new identity
  assets/src/scss/layout/_country-selector.scss
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] neptune

#1952 PLANET-7015 Apply new identity colors to Columns Tasks block
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] neptune

#1950 PLANET-6985 Update primary buttons colors for new identity
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/search/_filter-sidebar.scss
  templates/search.twig
Labels: Review, UAT Passed, [Test Env] pandora

#1953 PLANET-6988: New layout applied to tag links
  assets/src/scss/base/_typography.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] pandora

#1949 PLANET-6987 Update Donate button colors for new identity
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] rhea

#1958 PLANET-6999 Apply the new colors to the Author block
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/post/_author-block.scss
  images/blue-chevron.svg
Labels: Review, UAT Passed, [Test Env] neptune

#1961 Remove buttons box-shadow
  admin/css/login.css
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/layout/_navbar.scss
Labels: Review

#1957 PLANET-6991 Apply the new dark green color to contextual links
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/_listing-page.scss
Labels: Review, UAT Passed, [Test Env] leda

#1956 Add new datalayer value to track blocks
  page-templates/evergreen.php
  page.php
  single-campaign.php
  single-p4_action.php
  single.php
  src/Context.php
  templates/blocks/google_tag_manager.twig
Labels: Review, UAT Passed, [Test Env] umbriel

#1951 PLANET-6986 Update secondary buttons colors for new identity
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] nix

#1936 PLANET-7028 Add analytics feed meta on new GF form add
  src/GravityFormsExtensions.php
Labels: Review, UAT Passed, [Test Env] saturn
