Repository greenpeace/planet4-master-theme, pull requests merged in 2023-09, with the labels that each got.

#2081 PLANET-7035: Add new Page Types to the Data Layer values
  author.php
  category.php
  index.php
  single-p4_action.php
  src/Post.php
  taxonomy.php
Labels: Review, UAT Passed

#2110 PLANET-7191: Fix search action and content toggles
  templates/search.twig
  tests/e2e/tickets/PLANET-7191/PLANET-7191.test.js
Labels: [Test Env] pandora

#2111 Add Slack SVG icons
  assets/src/images/icons/slack-square.svg
  assets/src/images/icons/slack.svg
Labels: [Test Env] rhea

#2109 PLANET-7247: Fix tag listing page not listing all posts
  tag.php
Labels: [Test Env] atlas

#2114 PLANET-7072 Set PageType DLV for High Level & Deep Dive Topic pages
  src/Post.php
Labels: Review, UAT Passed, [Test Env] phoebe

#2115 Add Threads SVG icons
  assets/src/images/icons/threads-square.svg
  assets/src/images/icons/threads.svg
Labels: [Test Env] atlas

#1945 PLANET-5727: Limit of post revisions
  src/MasterSite.php
  src/Migrations/M022UpdatePostRevisions.php
  src/Migrator.php
Labels: Review, [Test Env] phobos

#2116 PLANET-7243 Fix new identity secondary buttons active styles
  assets/src/scss/components/_buttons.scss
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed, [Test Env] nix

#2117 PLANET-7267 Make sure editor links are styled with the new identity
  assets/src/scss/new-identity/style.scss
Labels: Review

#2119 Pin E2E test packages versions
  .circleci/config.yml
Labels: [Test Env] phobos

#2120 Fix limit post revisions query
  src/Migrations/M022UpdatePostRevisions.php
Labels: Review, [Test Env] nix

#2118 PLANET-7264: Endpoint for listing options and plugins
  functions.php
  src/Api/Settings.php
  src/Loader.php
  src/Settings/Features.php
Labels: [Test Env] atlas

#2121 Fix E2E flaky tests failing CI job
  playwright.config.js
  tests/e2e/env/.env.ci
  tests/e2e/env/.env.default
Labels: [Test Env] phobos
