Repository greenpeace/planet4-master-theme, pull requests merged in 2023-06, with the labels that each got.

#2027 PLANET-7147 Form Builder: Enable integration with native export tool
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] pandora

#2029 Add GPSA into the footer country list
  templates/countries.json
Labels: Review, [Test Env] janus

#2030 PLANET-7163 Re-write the Search test in Playwright
  .eslintrc.json
  tests/e2e/search.spec.js
Labels: Review, [Test Env] oberon

#2028 PLANET-7131 Sync Global Project Standards using sheet tab name
  src/AnalyticsValues.php
  src/GoogleDocsClient.php
Labels: Review, UAT Needed, [Test Env] leda

#2034 PLANET-7183 Fix search unwanted attachments
  src/Search.php
Labels: Review, [Test Env] pandora

#2035 PLANET-7183 Fix search password protected content
  src/Search.php
Labels: Review

#2037 Add new fonts
  assets/src/scss/new-identity/_fonts.scss
Labels: [Test Env] neptune

#2040 Revert Search ElasticPress fixes
  src/Search.php
Labels: Review, [Test Env] telesto

#2039 Design Tokens: New release [v0.13.1]
  assets/src/scss/base/_tokens.scss
Labels: [Test Env] oberon, Design Tokens

#2043 Design Tokens: New release [v0.14.0]
  assets/src/scss/base/_tokens.scss
Labels: Design Tokens

#2044 Rename fonts variable names
  assets/src/scss/new-identity/_fonts.scss
Labels: Review, [Test Env] rhea

#2045 PLANET-5789 Make sure posts report is only visible to some users
  src/PostReportController.php
Labels: Review, [Test Env] deimos

#2038 Disable Akismet admin spam button
  admin/js/options.js
  src/Settings.php
Labels: Review, [Test Env] atlas

#2041 PLANET-7103 Fix comment form logged in text overlap
  assets/src/scss/pages/post/_comments-form.scss
Labels: Review, [Test Env] neptune

#2047 Improve Playwright tests
  tests/e2e/404.spec.js
  tests/e2e/comments.spec.js
  tests/e2e/footer.spec.js
  tests/e2e/special-pages.spec.js
  tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
  tests/e2e/tools/lib/login.js
  tests/e2e/tools/lib/nonce.js
  tests/e2e/tools/lib/rest.js
Labels: Review, [Test Env] telesto

#2048 Expand eslint check on all js code
  .circleci/config.yml
  admin/js/dashboard.js
  admin/js/post_tag.js
  admin/js/posts_report.js
  tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
  tests/e2e/tools/php-errors.test.js
Labels: Review, [Test Env] deimos
