Repository greenpeace/planet4-master-theme, pull requests merged in 2023-02, with the labels that each got.

#1911 PLANET-7044 Create new toggle that enables all new IA features
  archive-p4_action.php
  author.php
  category.php
  functions.php
  index.php
  src/ActionPage.php
  src/Features/ActionPostType.php
  src/Features/ListingPagePagination.php
  src/Features/MobileTabsMenu.php
  src/Features/PostPageCategoryLinks.php
  src/MasterSite.php
  src/Migrations/M014RemoveDropdownNavigationMenusOption.php
  src/Migrations/M015RemoveListingPagesBackgroundImage.php
  src/Migrations/M017NewIAToggle.php
  src/Migrator.php
  src/Post.php
  src/Search.php
  src/Settings.php
  src/Settings/InformationArchitecture.php
  tag.php
  taxonomy.php
Labels: Review, [Test Env] rhea

#1908 PLANET-7055 Setup Playwright
  .gitignore
  package-lock.json
  package.json
  playwright.config.js
  tests/e2e/404.spec.js
  tests/e2e/cookies-banner.spec.js
Labels: Review, [Test Env] iocaste

#1915 PLANET-7073: Fix custom taxonomy pagination
  src/CustomTaxonomy.php
Labels: [Test Env] oberon

#1918 Fix type error on author page
  author.php
  single-attachment.php
Labels: [Test Env] rhea

#1919 Fix some links hover/visited/active color
  assets/src/scss/pages/_sitemap.scss
  assets/src/scss/pages/post/_post.scss
Labels: Review

#1920 Set CSS variables defaults and remove them from theme file
  assets/src/scss/base/_variables.scss
  assets/src/scss/components/_blockquote.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/layout/_breadcrumbs.scss
  assets/src/scss/layout/_cookies-settings.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/layout/_country-selector.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_gravity-forms.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/_page-header.scss
  assets/src/scss/layout/_page-section.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/layout/navbar/languages.scss
  assets/src/scss/pages/_evergreen.scss
  assets/src/scss/pages/_listing-page.scss
  assets/src/scss/pages/_sitemap.scss
  assets/src/scss/pages/post/_article-content.scss
  assets/src/scss/pages/post/_author-block.scss
  assets/src/scss/pages/post/_comments-block.scss
  assets/src/scss/pages/post/_post.scss
  assets/src/scss/pages/search/_filter-sidebar.scss
  assets/src/scss/pages/search/_search-results.scss
  assets/src/scss/partials/country-selector.scss
  assets/src/scss/partials/navigation-bar.scss
  assets/src/scss/post.scss
  assets/src/scss/style.scss
  theme.json
Labels: [Test Env] iocaste

#1916 PLANET-7005: Analytics sidebar in native UI
  assets/src/scss/editorOverrides.scss
  src/ActionPage.php
  src/AnalyticsValues.php
  src/MetaboxRegister.php
  src/PageMeta.php
  src/PostCampaign.php
  src/PostMeta.php
Labels: [Test Env] neptune

#1927 Fix donate button visited color
  assets/src/scss/components/_buttons.scss
Labels: Review, [Test Env] neptune

#1926 Decrease Google login font-size to fix overflow
  admin/css/login.css
Labels: Review, [Test Env] iocaste

#1923 PLANET-6473 Add focus state to checkboxes and radio buttons
  assets/src/scss/layout/_forms.scss
Labels: Review, UAT Passed, [Test Env] rhea

#1935 Design Tokens: New release [v0.10.0]
  assets/src/scss/base/_tokens.scss
Labels: [Test Env] rhea, Design Tokens

#1924 Purge caches for posts that contain a form
  src/GravityFormsExtensions.php
Labels: Review

#1480 Revert fix added in Planet-6060
  src/MasterSite.php
Labels: DO NOT MERGE, [Test Env] tavros

#1937 Fix PHP type errors
  src/GravityFormsExtensions.php
  src/MasterSite.php
Labels: [Test Env] pandora

#1938 Fix return type on GF custom confirmation function
  src/GravityFormsExtensions.php
Labels: [Test Env] rhea

#1930 PLANET-6989 Apply the new UI for the share buttons
  assets/src/scss/base/_colors.scss
  assets/src/scss/components/_share-buttons.scss
Labels: Review, UAT Needed, [Test Env] neptune

#1939 PLANET-6959 Fix possible overflow in comment text
  assets/src/scss/pages/post/_comments-block.scss
Labels: Review, [Test Env] pandora
