Repository greenpeace/planet4-master-theme, pull requests merged in 2023-10, with the labels that each got.

#2020 PLANET-6373 Blocks as a theme feature POC
  .circleci/config.yml
  assets/src/blocks/GuestBook/GuestBookBlock.js
  assets/src/blocks/GuestBook/GuestBookEditorScript.js
  assets/src/blocks/GuestBook/GuestBookFrontend.js
  assets/src/blocks/GuestBook/GuestBookScript.js
  assets/src/blocks/components/FrontendBlockNode/FrontendBlockNode.js
  assets/src/blocks/editorIndex.js
  assets/src/blocks/frontendIndex.js
  assets/src/blocks/frontendRendered.js
  assets/src/blocks/styles/blocks.scss
  assets/src/blocks/styles/blocks/Guestbook.scss
  assets/src/blocks/styles/editorOverrides.scss
  assets/src/blocks/styles/editorStyle.scss
  assets/src/blocks/styles/style.scss
  package-lock.json
  package.json
  src/Blocks/BaseBlock.php
  src/Blocks/BlockList.php
  src/Blocks/GuestBook.php
  src/Features/Planet4Blocks.php
  src/Loader.php
  src/MasterBlocks.php
  src/Migrations/M023EnablePlanet4Blocks.php
  src/Migrator.php
  src/Settings/Features.php
  templates/block_templates/block-error-message.twig
  webpack.config.js
Labels: Review, [Test Env] sinope

#2112 PLANET-7158 Editor Version of Media Archive
  admin/css/archive-picker.css
  assets/src/js/Components/ArchivePicker/ArchivePicker.js
  assets/src/js/Components/ArchivePicker/ArchivePickerList.js
  assets/src/js/Components/ArchivePicker/SingleSidebar.js
  assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
  assets/src/js/media_archive_editor_view.js
  assets/src/scss/editorOverrides.scss
  package-lock.json
  package.json
  src/AdminAssets.php
  src/MediaArchive/UiIntegration.php
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] titan

#2125 PLANET-7178 Move Copyright settings to Navigation settings
  src/Settings.php
Labels: Review, [Test Env] nix

#2127 Fix Playwright package
  package-lock.json
  package.json
Labels: [Test Env] saturn

#2128 PLANET-7227 Enable new Media Archive implementation
  src/AdminAssets.php
  src/Features/MediaArchive.php
  src/MediaArchive/Rest.php
  src/MediaArchive/UiIntegration.php
  src/Settings/Features.php
Labels: Review, [Test Env] atlas

#2129 PLANET-7268 Add meta and opengraph html tags on listing pages
  author.php
  category.php
  src/Post.php
  tag.php
  taxonomy.php
  templates/base.twig
  templates/blocks/meta_fields.twig
Labels: Review, [Test Env] rhea

#2134 PLANET-7240 Update new identity listing pages fonts
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/_listing-page.scss
Labels: Review, [Test Env] nix

#2131 PLANET-7250 Add Actions list to posts report
  admin/js/posts_report.js
  posts-report.php
  templates/posts_report.twig
  tests/e2e/env/.env.ci
  underscore_templates/posts_reports.tpl.php
Labels: Review, [Test Env] pluto

#2083 PLANET-7269: Implement Sendgrid smtp integration
  src/Features/Dev/ListingPageGridView.php
  src/Features/Sendgrid.php
  src/MasterSite.php
  src/Sendgrid.php
  src/Settings/Features.php
  tests/e2e/env/.env.ci
Labels: [Test Env] oberon, [Test Env] atlas

#2141 Add code GravityForms Hubspot snippet
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] pluto
