Repository greenpeace/planet4-master-theme, pull requests merged in 2023-07, with the labels that each got.

#2042 PLANET-7113 Add more space and columns to Media Archive list
  admin/css/picker.css
Labels: Review, UAT Passed, [Test Env] janus

#2053 Update dashdash dependency
  package-lock.json
  package.json
Labels: Review, [Test Env] telesto

#2023 PLANET-7127: Apply the new Greenpeace sans typeface
  assets/src/scss/base/_typography.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/post/_comments-form.scss
Labels: Review, UAT Needed, [Test Env] jupiter

#2052 PLANET-7126: Apply the new source sans pro typeface
  assets/src/scss/new-identity/style.scss
Labels: Review, [Test Env] neptune

#2054 Small fix to get bigger avatars on certain pages
  templates/author.twig
  templates/blocks/author_profile.twig
Labels: Review, [Test Env] mars

#2055 Design Tokens: New release [v0.15.0]
  assets/src/scss/base/_tokens.scss
Labels: [Test Env] leda, Design Tokens

#2056 PLANET-5284 Add Playwright test for password protected content
  tests/e2e/password-protected-content.spec.js
Labels: Review, [Test Env] janus

#2057 PLANET-6840: Rename admin panel configuration options from Media Archive
  assets/src/js/media_archive.js
  src/MediaArchive/UiIntegration.php
  src/Settings.php
Labels: Review, [Test Env] oberon

#2065 Design Tokens: New release [v0.15.1]
  assets/src/scss/base/_tokens.scss
Labels: Design Tokens

#2063 Add trailing slash on Opengraph url
  src/MasterSite.php
Labels: Review, [Test Env] jupiter

#2059 PLANET-7169 Fix analytics Field tracking ID(i.e projectID) bug
  src/AnalyticsValues.php
  src/Loader.php
  src/MasterSite.php
  src/MetaboxRegister.php
Labels: Review, UAT Passed, [Test Env] mars

#2066 Follow up design tokens's feedback
  assets/src/scss/components/_buttons.scss
  assets/src/scss/layout/_cookies-settings.scss
  assets/src/scss/layout/_country-selector.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
  assets/src/scss/new-identity/style.scss
Labels: UAT Passed, [Test Env] janus

#2062 PLANET-7118 Update Media Archive import flow
  admin/css/picker.css
  assets/src/js/Components/ArchivePicker.js
  assets/src/js/Components/archivePicker/SingleSidebar.js
  assets/src/js/Components/archivePicker/useImages.js
  images/black-cross.svg
Labels: Review, UAT Needed, [Test Env] saturn

#2058 Fix link style rule
  assets/src/scss/new-identity/style.scss
Labels: [Test Env] neptune

#2069 PLANET-7186 Add setting for Hubspot tracking code
  src/MasterSite.php
  src/Settings.php
  templates/base.twig
  templates/hubspot_tracking_code.twig
Labels: Review, [Test Env] leda

#2072 Fix act_page notices
  src/MasterSite.php
Labels: [Test Env] janus

#2073 PLANET-7045 Create settings options for new IA pages
  admin/css/options.css
  admin/js/options.js
  src/Post.php
  src/Settings.php
  tests/e2e/special-pages.spec.js
Labels: Review, UAT Passed, [Test Env] jupiter

#2075 PLANET-7198 Add self-reference canonical urls to listing pages
  author.php
  category.php
  page.php
  tag.php
  taxonomy.php
  templates/base.twig
  templates/html-header.twig
  tests/test-category-page.php
Labels: Review, [Test Env] neptune

#2068 PLANET-7115: Implement media library multi search options
  admin/css/picker.css
  assets/src/js/Components/ArchivePicker.js
  assets/src/js/Components/archivePicker/ArchivePickerList.js
  assets/src/js/Components/archivePicker/MultiSearchOption.js
  assets/src/js/Components/archivePicker/MultiSidebar.js
  assets/src/js/Components/archivePicker/SingleSidebar.js
  assets/src/js/Components/archivePicker/useImages.js
  src/MediaArchive/Rest.php
Labels: Review, UAT Passed, [Test Env] deimos

#2078 PLANET-7203 Fix menu notice showing multiple times
  assets/src/js/menu_editor.js
Labels: [Test Env] janus
