Repository greenpeace/planet4-master-theme, pull requests merged in 2023-05, with the labels that each got.

#1998 PLANET-6997 Apply new identity colors to cookies box
  assets/src/scss/new-identity/style.scss
Labels: Review, UAT Passed

#2007 PLANET-7149 Fix Gravity Forms submit button styles
  assets/src/scss/components/_buttons.scss
Labels: Review, [Test Env] telesto

#2004 PLANET-7143 Fix spacing in RTL paginated listing pages
  assets/src/scss/pages/_listing-page.scss
Labels: Review, [Test Env] neptune

#1996 PLANET-7132: Apply new identity colors to Split Two Columns block
  assets/src/scss/new-identity/style.scss
Labels: UAT Passed, [Test Env] pandora

#2003 PLANET-7063 Re-write the Editor Selector test in Playwright
  tests/acceptance/editor.feature
Labels: Review

#2005 Implement new yellow CSS variables to links
  assets/src/scss/new-identity/style.scss
Labels: Review, [Test Env] rhea

#2010 PLANET-7157 Harmonise search input clear buttons
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/search/_search-bar.scss
  templates/search.twig
Labels: Review, UAT Passed, [Test Env] telesto

#2013 PLANET-7060 Write Playwright test for special pages
  tests/acceptance/ActPageCept.php
  tests/acceptance/ExplorePageCept.php
  tests/e2e/special-pages.spec.js
Labels: Review, [Test Env] neptune

#2015 Design Tokens: New release [v0.12.0]
  assets/src/scss/base/_tokens.scss
Labels: [Test Env] sinope, Design Tokens

#1997 PLANET-6235: Fix ElasticSearch class usage
  src/Search.php
Labels: [Test Env] leda

#2018 Adjust test user trigger to new instance parameter
  .circleci/config.yml
Labels: Review

#2017 PLANET-7061 Re-write the Footer test in Playwright
  tests/acceptance/FooterCept.php
  tests/e2e/footer.spec.js
Labels: Review, [Test Env] neptune

#2012 PLANET-7154: Duplicate Feeds on form duplication
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] jupiter

#2014 PLANET-7058 Re-write the Comments test in Playwright
  tests/e2e/comments.spec.js
Labels: Review

#2021 Design Tokens: New release [v0.12.1]
  assets/src/scss/base/_tokens.scss
Labels: [Test Env] leda, Design Tokens

#2024 Reset Act and Explore pages after special pages test
  tests/e2e/special-pages.spec.js
Labels: Review, [Test Env] telesto

#2019 Rename Image Archive to Media Archive
  admin/css/media-api-info.css
  assets/src/js/media_archive.js
  functions.php
  languages/planet4-master-theme-backend.pot
  src/Capability.php
  src/Features/MediaArchive.php
  src/ImageArchive/UiIntegration.php
  src/Loader.php
  src/MediaArchive/ApiClient.php
  src/MediaArchive/Image.php
  src/MediaArchive/ImageSize.php
  src/MediaArchive/Rest.php
  src/MediaArchive/UiIntegration.php
  src/Role/Campaigner.php
  src/Settings/Features.php
  webpack.config.js
Labels: Review, [Test Env] telesto

#2025 PLANET-7146 Form Builder: Disable IP address retention during submission
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] atlas

#2008 PLANET-7128: Apply the new Source Sans 3 typeface
  assets/src/scss/layout/_breadcrumbs.scss
  assets/src/scss/layout/_cookies-settings.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/layout/_footer.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_gravity-forms.scss
  assets/src/scss/new-identity/_fonts.scss
  assets/src/scss/new-identity/style.scss
  assets/src/scss/pages/post/_author-block.scss
  assets/src/scss/pages/post/_comments-block.scss
  assets/src/scss/pages/post/_comments-form.scss
  assets/src/scss/pages/post/_post.scss
Labels: Review, UAT Needed, [Test Env] deimos

#2026 PLANET-7148 Form Builder: Enforce data retention policy
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] janus
