Repository greenpeace/planet4-master-theme, pull requests merged in 2024-10, with the labels that each got.

#2392 PLANET-7568 Fix styles for the Gravity Forms multiple file upload
  assets/src/scss/layout/_gravity-forms.scss
Labels: Review, [Test Env] venus

#2380 PLANET-7598: Form Builder - Add a petition counter id field
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] iocaste

#2391 PLANET-7597 Fix Block Usage Report 'group by post id' links'
  src/BlockReportSearch/Block/BlockUsageTable.php
  src/BlockReportSearch/Pattern/PatternUsageTable.php
  src/BlockReportSearch/RowActions.php
Labels: Review, [Test Env] nix

#2396 Fix special characters in sitemap links
  templates/sitemap.twig
Labels: Review, [Test Env] iocaste

#2357 PLANET-7521: Migrate Media Block to Audio/Video blocks
  assets/src/blocks/Media/MediaBlock.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/Media/MediaElementVideo.js
  assets/src/blocks/Media/MediaFrontend.js
  assets/src/blocks/Media/deprecated/mediaV1.js
  assets/src/blocks/Media/setupMediaElementJS.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Media.scss
  exporter-helper.php
  src/BlockSettings.php
  src/Blocks/Media.php
  src/Importer.php
  src/Loader.php
  src/Migrations/M031MigrateMediaBlockToAudioVideoBlock.php
  src/Migrations/Utils/Constants.php
  src/Migrations/Utils/Functions.php
  src/Migrator.php
Labels: Review, UAT Passed, [Test Env] tavros

#2398 Fix new Sentry warning
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] iocaste

#2399 Add styles to embed elements
  assets/src/scss/base/_mixins.scss
  assets/src/scss/core-overrides/embed.scss
  assets/src/scss/style.scss
Labels: Review, [Test Env] iocaste

#2397 PLANET-7607 Fix Cookies block frontend bug
  admin/js/options.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  src/Settings.php
Labels: Review, [Test Env] nix

#2400 Fix zoom on hover in the home template
  assets/src/scss/variations/stretched-link/index.scss
Labels: Review, UAT Passed, [Test Env] pluto

#2401 Bug fix: Take Action Boxout spacing below missing
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
  assets/src/scss/pages/post/_article-content.scss
Labels: Review, [Test Env] proteus

#2403 PLANET-7631 Twitter embed doesn't work in the frontend
  assets/src/scss/core-overrides/embed.scss
Labels: Review, [Test Env] iocaste

#2405 PLANET-7628: Add Articles block from the P4 plugin
  assets/src/blocks/Articles/ArticlePreview.js
  assets/src/blocks/Articles/ArticlesBlock.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/Articles/ArticlesEditorScript.js
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/Articles/ArticlesList.js
  assets/src/blocks/Articles/ArticlesScript.js
  assets/src/blocks/Articles/frontendRendered.js
  assets/src/blocks/Articles/imageSizes.js
  assets/src/blocks/Articles/useArticlesFetch.js
  assets/src/blocks/components/withCharacterCounter/withCharacterCounter.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Articles/ArticlesEditorStyle.scss
  assets/src/scss/blocks/Articles/ArticlesStyle.scss
  assets/src/scss/editorStyle.scss
  functions.php
  src/Admin/Published.php
  src/Admin/Rest.php
  src/Api/Articles.php
  src/Blocks/Articles.php
  src/Loader.php
  tests/e2e/blocks/articles.spec.js
  tests/e2e/blocks/related-articles.spec.js
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/post.js
  webpack.config.js
Labels: Review, [Test Env] pluto

#2351 PLANET-7575: Rename social media events
  assets/src/blocks/ENForm/ShareButtons.js
  src/GravityFormsExtensions.php
  templates/blocks/share_buttons.twig
Labels: Review, UAT Passed, [Test Env] atlas

#2411 PLANET-7636 Remove editor sidebar labels uppercase
  assets/src/scss/editorOverrides.scss
Labels: Review

#2412 PLANET-7638 Add e2e tests for GF redirect and page confirmation types
  tests/e2e/gravity-forms.spec.js
  tests/e2e/tools/lib/gravity-forms.js
Labels: Review, [Test Env] jupiter

#2408 PLANET-7605 Implement page_date dataLayer variable for Posts
  single.php
  templates/blocks/google_tag_manager.twig
Labels: Review, UAT Passed, [Test Env] phobos

#2319 PLANET-7525 Media Import does not work with Featured Image
  assets/src/js/Components/ArchivePicker/ArchivePicker.js
  assets/src/js/Components/ArchivePicker/SingleSidebar.js
  assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
  assets/src/js/media_archive.js
  assets/src/js/media_archive_editor_view.js
Labels: Review, [Test Env] janus

#2415 PLANET-7637 Planet 4 Bug Report: Gallery Block - Upload image issue
  assets/src/blocks/CarouselHeader/StaticCaption.js
  src/MasterSite.php
Labels: Review, [Test Env] tavros

#2423 PLANET-7643: Media Library - Show restrictions on imported media
  admin/css/archive-picker.css
  assets/src/js/Components/ArchivePicker/SingleSidebar.js
  src/MasterSite.php
Labels: Review, [Test Env] iocaste

#2417 Fix Carousel Header layout
  assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss
Labels: Review, [Test Env] pluto

#2424 PLANET-7616: Merge CSS core overrides folders
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/core-overrides/Columns.scss
  assets/src/scss/blocks/core-overrides/Embed.scss
  assets/src/scss/blocks/core-overrides/Heading.scss
  assets/src/scss/blocks/core-overrides/Image.scss
  assets/src/scss/blocks/core-overrides/MediaText.scss
  assets/src/scss/core-overrides/_heading.scss
  assets/src/scss/core-overrides/_image.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
Labels: Review, [Test Env] rhea

#2425 Fix warnings and errors reported by Sentry
  single-campaign.php
  src/CustomTaxonomy.php
  src/DevReport.php
  tag.php
  taxonomy.php
Labels: Review, [Test Env] umbriel

#2426 Make SoundCloud embed full width
  assets/src/scss/blocks/core-overrides/Embed.scss
Labels: Review, UAT Passed, [Test Env] jupiter
