Repository greenpeace/planet4-master-theme, pull requests merged in 2024-03, with the labels that each got.

#2215 PLANET-7409: Implement new parameters on Google Consent Mode
  assets/src/js/cookies.js
  templates/blocks/google_tag_manager.twig
Labels: UAT Needed, [Test Env] pandora

#2222 PLANET-7413 Redirect Import button to Greenpeace Media
  src/Exporter.php
Labels: [Test Env] leda

#2220 PLANET-7416 Add carousel layout to Posts List block
  assets/src/block-editor/QueryBlockExtension/index.js
  assets/src/block-editor/QueryLoopBlockExtension/index.js
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/PostsList/index.js
  assets/src/editorIndex.js
  assets/src/js/query_loop_carousel.js
  assets/src/scss/blocks/ActionsList.scss
  assets/src/scss/blocks/PostsList.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/layout/_query-loop-overrides.scss
Labels: Review, UAT Passed, [Test Env] rhea

#2221 PLANET-7426: Add reading_time datalayer variable
  single.php
  src/Context.php
  src/Post.php
  templates/blocks/google_tag_manager.twig
  templates/single.twig
  templates/tease-author.twig
  templates/tease-taxonomy-action.twig
  templates/tease-taxonomy-post.twig
Labels: UAT Passed, [Test Env] pluto

#2208 PLANET-7415: Add manual override to Actions list block
  assets/src/block-editor/PostSelector/PostSelector.js
  assets/src/block-editor/QueryLoopBlockExtension/index.js
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/PostsList/index.js
  assets/src/editorIndex.js
  src/Blocks/QueryLoopExtension.php
  src/Loader.php
Labels: [Test Env] umbriel

#2226 PLANET-7444 Remove unnecessary code for image alignment
  assets/src/scss/pages/post/_article-content.scss
Labels: Review

#2207 PLANET-7348 Migrate Page Header options to Page Header block pattern
  assets/src/block-editor/Sidebar/PageHeaderSidebar.js
  page-templates/sitemap.php
  src/Migrations/M028MovePageHeaderSideBarOptions.php
  src/Migrator.php
Labels: Review, [Test Env] oberon

#2219 PLANET-7447 Unescape HTML entities in Carousel header title
  assets/src/blocks/CarouselHeader/StaticCaption.js
Labels: Review, [Test Env] neptune

#2232 Update Image Archive name to Greenpeace Media
  src/MediaArchive/UiIntegration.php
Labels: Review, [Test Env] venus

#2227 PLANET-7417 Add grid layout to Posts List block
  assets/src/blocks/PostsList/index.js
  assets/src/scss/blocks/ActionsList.scss
  assets/src/scss/blocks/PostsList.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/layout/_query-loop-overrides.scss
Labels: Review, UAT Passed, [Test Env] sinope

#2225 PLANET-7402 Move Media block into master theme
  assets/src/blocks/Media/MediaBlock.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/Media/MediaElementVideo.js
  assets/src/blocks/Media/MediaFrontend.js
  assets/src/blocks/Media/deprecated/mediaV1.js
  assets/src/blocks/Media/setupMediaElementJS.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/hooks/useStylesheet/addLinkTag.js
  assets/src/hooks/useStylesheet/useStylesheet.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Media.scss
  src/Blocks/Media.php
  src/Loader.php
Labels: Review, [Test Env] iocaste

#2233 PLANET-7443: Fix Exclude from search EP functionality
  src/ElasticSearch.php
Labels: [Test Env] pluto

#2234 Add missing is_rest_request function to BaseBlock class
  src/Blocks/BaseBlock.php
Labels: Review, [Test Env] saturn

#2236 Fix clear search button in large screens
  assets/src/scss/layout/navbar/_search.scss
Labels: [Test Env] pandora

#2235 PLANET-7478 Remove skewed overlay
  assets/src/scss/layout/_skewed-overlay.scss
  assets/src/scss/pages/post/_post.scss
  assets/src/scss/style.scss
  templates/404.twig
  templates/all-actions.twig
  templates/all-posts.twig
  templates/blocks/header.twig
  templates/taxonomy.twig
  themes/climate.json
  themes/oceans.json
Labels: Review, [Test Env] umbriel

#2238 PLANET-7448: Exclude password-protected content from Action/Post list block
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/PostsList/index.js
  src/Blocks/QueryLoopExtension.php
Labels: [Test Env] neptune

#2239 PLANET-7431: Author profile page returns all posts by Editor
  author.php
  src/AuthorPage.php
  src/MasterSite.php
Labels: [Test Env] venus

#2237 PLANET-7430: Elastic search not returning correct results
  src/ElasticSearch.php
  src/Search.php
Labels: [Test Env] oberon
