Repository greenpeace/planet4-master-theme, pull requests merged in 2024-05, with the labels that each got.

#2255 PLANET-7453 Add new DL variable for email in Gravity Forms
  src/GravityFormsExtensions.php
Labels: Review, UAT Passed, [Test Env] neptune

#2243 PLANET-7410 Update the default and update consent mode scripts
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/js/cookies.js
  templates/blocks/google_tag_manager.twig
Labels: Review, UAT Passed

#2277 PLANET-7399 Move Reality Check block pattern into master theme
  assets/src/block-templates/reality-check/block.json
  assets/src/block-templates/reality-check/index.js
  assets/src/block-templates/reality-check/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/RealityCheck.php
Labels: Review, [Test Env] nix

#2276 PLANET-7398 Move Quick Links block pattern into master theme
  assets/src/block-templates/quick-links/block.json
  assets/src/block-templates/quick-links/index.js
  assets/src/block-templates/quick-links/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/QuickLinks.php
Labels: Review, [Test Env] pandora

#2272 PLANET-7503: Fix selector to exclude submenu header in submenu block
  assets/src/blocks/Submenu/getHeadingsFromDom.js
Labels: Review

#2246 PLANET-7485: Rewrite search to avoid double queries
  assets/src/js/search.js
  functions.php
  load-class-aliases.php
  search.php
  src/Api/Search.php
  src/ElasticSearch.php
  src/MasterSite.php
  src/PublicAssets.php
  src/Search.php
  src/Search/Aggregations.php
  src/Search/ElasticSearch.php
  src/Search/Filters/ActionTypes.php
  src/Search/Filters/Categories.php
  src/Search/Filters/ContentTypes.php
  src/Search/Filters/PostTypes.php
  src/Search/Filters/Tags.php
  src/Search/Search.php
  src/Search/SearchPage.php
  templates/search.twig
  templates/search/action_types.twig
  templates/search/categories.twig
  templates/search/content_types.twig
  templates/search/post_types.twig
  templates/tease-search.twig
Labels: [Test Env] umbriel

#2283 PLANET-7366 Add filter hook for overriding Sendgrid from address
  src/Sendgrid.php
Labels: Review, UAT Passed, [Test Env] venus

#2285 Include custom block styles from plugin
  assets/src/block-styles/index.js
  assets/src/editorIndex.js
  assets/src/scss/base/_mixins.scss
  assets/src/scss/core-overrides/_heading.scss
  assets/src/scss/core-overrides/_image.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
Labels: [Test Env] nix

#2258 PLANET-7395: Move Deep Dive block pattern into master theme
  assets/src/block-templates/deep-dive/block.json
  assets/src/block-templates/deep-dive/index.js
  assets/src/block-templates/deep-dive/template.js
  assets/src/block-templates/template-list.js
  assets/src/scss/editorOverrides.scss
  src/Patterns/BlockPattern.php
  src/Patterns/DeepDive.php
Labels: Review, [Test Env] janus

#2259 PLANET-7396: Move Highlighted CTA block pattern into master theme
  assets/src/block-templates/highlighted-cta/block.json
  assets/src/block-templates/highlighted-cta/index.js
  assets/src/block-templates/highlighted-cta/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/HighlightedCta.php
Labels: Review, [Test Env] pluto

#2289 Fix gallery spec
  tests/e2e/tools/lib/editor.js
Labels: [Test Env] sinope

#2281 PLANET-7516: Fix Analytics Tracking Sidebar component
  assets/src/block-editor/Sidebar/AnalyticsTrackingSidebar.js
Labels: Review, [Test Env] saturn

#2287 Add alt attribute to nav-items
  templates/burger-menu-items.twig
  templates/burger-menu.twig
  templates/desktop-menu.twig
  templates/footer.twig
  templates/navigation-bar.twig
  templates/navigation-bar_min.twig
  templates/navigation-submenu.twig
Labels: [Test Env] tavros

#2293 PLANET-7509 Enable Sendgrid integration on all websites
  src/Features/Sendgrid.php
  src/MasterSite.php
  src/Settings/Features.php
Labels: Review, [Test Env] nix

#2284 PLANET-7505 Adjust Greenpeace Media search UX
  admin/css/archive-picker.css
  assets/src/js/Components/ArchivePicker/ArchivePickerToolbar.js
Labels: Review, UAT Passed, [Test Env] neptune

#2291 PLANET-7533 Fix Type error in function param
  src/Controllers/Menu/EnformPostController.php
  src/MasterSite.php
Labels: Review, [Test Env] telesto

#2294 PLANET-7532 Retire unused feature flags
  src/Features/Dev/WPTemplateEditor.php
  src/Features/PurgeOnFeatureChanges.php
  src/MasterSite.php
  src/Migrations/M029RemoveTemplateEditorOption.php
  src/Migrations/M030RemovePurgeOnFeatureChangeOption.php
  src/Migrator.php
  src/Settings/Features.php
Labels: Review, [Test Env] janus

#2295 Fix search clear button rtl position
  assets/src/scss/pages/search/_search-bar.scss
Labels: Review, [Test Env] pluto

#2292 PLANET-7369 Use custom button text setting in Actions List block
  assets/src/blocks/ActionCustomButtonText/edit.js
  assets/src/blocks/ActionCustomButtonText/index.js
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/editorIndex.js
  assets/src/js/actions_list_clickable_cards.js
  assets/src/scss/blocks/ActionsList.scss
  src/Blocks/ActionButtonText.php
  src/Loader.php
Labels: Review, [Test Env] venus
