Repository greenpeace/planet4-master-theme, pull requests merged in 2024-07, with the labels that each got.

#2313 PLANET-7554 Move Take Action block pattern layout into master theme
  assets/src/block-templates/take-action/block.json
  assets/src/block-templates/take-action/index.js
  assets/src/block-templates/take-action/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/TakeAction.php
Labels: Review

#2317 Update theme file version from 2 to 3
  theme.json
Labels: [Test Env] tavros

#2305 PLANET-7401 Move Page Header block pattern into master theme
  assets/src/block-templates/page-header/block.json
  assets/src/block-templates/page-header/index.js
  assets/src/block-templates/page-header/template.js
  assets/src/block-templates/template-list.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/PageHeader.scss
  src/Loader.php
  src/Patterns/BlockPattern.php
  src/Patterns/PageHeader.php
  src/Patterns/PageHeaderImgLeft.php
Labels: Review, [Test Env] iocaste

#2309 PLANET-7531 Posts/Actions blocks: Show message when no posts found
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/PostsList/index.js
  assets/src/js/app.js
  assets/src/js/query-no-posts.js
  assets/src/js/query_loop_carousel.js
Labels: Review, [Test Env] neptune

#2320 PLANET-7497: Backend Text Changes on Counter Block
  assets/src/blocks/Counter/CounterEditor.js
Labels: Review, [Test Env] pandora

#2323 PLANET-7513 Remove the style section from the Carousel Header backend…
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss
Labels: Review, [Test Env] iocaste

#2308 Generate and save a hashed gp_user_id on form submissions
  assets/src/js/cookies.js
  src/GravityFormsExtensions.php
  src/MasterSite.php
  src/Settings.php
  templates/blocks/google_tag_manager.twig
Labels: Review

#2314 PLANET-7543 Add spinner to Greenpeace Media when searching for images
  admin/css/archive-picker.css
  assets/src/js/Components/ArchivePicker/MultiSearchOption.js
Labels: Review, UAT Passed, [Test Env] jupiter

#2325 PLANET-7515: Accordion block design fixes on mobile
  assets/src/scss/blocks/Accordion/AccordionStyle.scss
Labels: Review, UAT Passed, [Test Env] sinope

#2329 Make sure 'no post text' exists before manipulating it
  assets/src/js/query-no-posts.js
Labels: Review, [Test Env] pandora

#2303 PLANET-7527 Move blocks report into master theme
  src/BlockReportSearch/Block/BlockUsage.php
  src/BlockReportSearch/Block/BlockUsageApi.php
  src/BlockReportSearch/Block/BlockUsageTable.php
  src/BlockReportSearch/Block/Query.php
  src/BlockReportSearch/Block/Query/Parameters.php
  src/BlockReportSearch/Block/Sql/Like.php
  src/BlockReportSearch/Block/Sql/Regex.php
  src/BlockReportSearch/Block/Sql/SqlQuery.php
  src/BlockReportSearch/BlockSearch.php
  src/BlockReportSearch/Pattern/ContentStructure.php
  src/BlockReportSearch/Pattern/PatternData.php
  src/BlockReportSearch/Pattern/PatternUsage.php
  src/BlockReportSearch/Pattern/PatternUsageApi.php
  src/BlockReportSearch/Pattern/PatternUsageTable.php
  src/BlockReportSearch/Pattern/Query/Parameters.php
  src/BlockReportSearch/PatternSearch.php
  src/BlockReportSearch/RowActions.php
  src/Commands/DuplicatedPostmeta.php
  src/Controllers/Menu/BlocksReportController.php
  src/Controllers/Menu/BlocksUsageController.php
  src/Controllers/Menu/ClassicBlocksUsage.php
  src/Controllers/Menu/PostmetaCheckController.php
  src/Controllers/Menu/ReusableBlocksController.php
  src/Loader.php
  src/Migrations/M009PopulateCookiesFields.php
  templates/duplicate-postmeta-report.twig
Labels: Review, [Test Env] venus

#2310 PLANET-7365: Clean up Listing page code
  archive-p4_action.php
  author.php
  index.php
  src/ListingPage.php
  tag.php
  taxonomy.php
  templates/burger-menu-items.twig
Labels: [Test Env] oberon

#2321 PLANET-7553 Move Homepage block pattern layout into master theme
  assets/src/block-templates/homepage/block.json
  assets/src/block-templates/homepage/index.js
  assets/src/block-templates/homepage/template.js
  assets/src/block-templates/template-list.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/WideBlocks.scss
  assets/src/scss/blocks/core-overrides/BlockSpacing.scss
  assets/src/scss/blocks/core-overrides/Heading.scss
  assets/src/scss/blocks/core-overrides/HeadingEditor.scss
  assets/src/scss/blocks/core-overrides/Image.scss
  assets/src/scss/blocks/core-overrides/Separator.scss
  assets/src/scss/blocks/core-overrides/Table.scss
  assets/src/scss/blocks/core-overrides/_columns.scss
  assets/src/scss/blocks/core-overrides/_media-text.scss
  src/Patterns/BlockPattern.php
  src/Patterns/Homepage.php
Labels: Review

#2333 PLANET-7496: Backend Text Changes on Submenu Block
  assets/src/blocks/Submenu/SubmenuEditor.js
Labels: Review

#2332 PLANET-7500: Backend text changes on Happypoint block
  assets/src/blocks/Happypoint/HappypointEditor.js
Labels: Review

#2330 PLANET-7565: Explicitly import "regenerator-runtime"
  assets/src/frontendIndex.js
Labels: [Test Env] iocaste

#2335 PLANET-7551: Move GetInformed pattern block to theme
  assets/src/block-templates/get-informed/block.json
  assets/src/block-templates/get-informed/index.js
  assets/src/block-templates/get-informed/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/GetInformed.php
Labels: Review, [Test Env] titan
