Repository greenpeace/planet4-master-theme, pull requests merged in 2024-01, with the labels that each got.

#2182 PLANET-7345: Disable Posts List Query Loop WP variation
  assets/src/blocks/editorIndex.js
Labels: Review, [Test Env] iocaste

#2185 PLANET-7367: Add manual override to Posts List block
  assets/src/block-editor/PostSelector/PostSelector.js
  assets/src/blocks/PostsList/index.js
  src/Blocks/PostsList.php
  src/Loader.php
Labels: [Test Env] oberon

#2192 Update phpunit polyfills
  composer.json
  composer.lock
  tests/bootstrap.php
Labels: [Test Env] iocaste

#2180 PLANET-7255: Move Gallery block to master theme
  assets/src/blocks/Gallery/GalleryBlock.js
  assets/src/blocks/Gallery/GalleryCarousel.js
  assets/src/blocks/Gallery/GalleryEditor.js
  assets/src/blocks/Gallery/GalleryEditorScript.js
  assets/src/blocks/Gallery/GalleryFrontend.js
  assets/src/blocks/Gallery/GalleryGrid.js
  assets/src/blocks/Gallery/GalleryScript.js
  assets/src/blocks/Gallery/GalleryThreeColumns.js
  assets/src/blocks/Gallery/getCaptionWithCredits.js
  assets/src/blocks/Gallery/getGalleryLayout.js
  assets/src/blocks/Gallery/imageSizes.js
  assets/src/blocks/Gallery/useGalleryImages.js
  assets/src/blocks/components/Lightbox/Lightbox.js
  assets/src/blocks/components/Lightbox/setupLightboxForImages.js
  assets/src/blocks/components/Lightbox/useLightbox.js
  assets/src/functions/addQueryArgs.js
  assets/src/functions/fetchJson.js
  assets/src/functions/getAbortController.js
  assets/src/functions/getStyleLabel.js
  assets/src/scss/blocks/Gallery/GalleryEditorStyle.scss
  assets/src/scss/blocks/Gallery/GalleryStyle.scss
  assets/src/scss/blocks/Gallery/styles/GalleryCarousel.scss
  assets/src/scss/blocks/Gallery/styles/GalleryGrid.scss
  assets/src/scss/blocks/Gallery/styles/GalleryThreeColumns.scss
  functions.php
  package-lock.json
  package.json
  src/Api/Gallery.php
  src/Blocks/BaseBlock.php
  src/Blocks/Gallery.php
  src/Loader.php
  tests/e2e/gallery.spec.js
  webpack.config.js
Labels: [Test Env] umbriel

#2194 PLANET-7394: Fix missing up/down arrow icon in CarouselHeader
  assets/src/scss/blocks/CarouselHeader/SidebarSlidesEditor.scss
Labels: Review, [Test Env] atlas

#2178 PLANET-7303 Move Spreadsheet block into master theme
  assets/src/block-editor/ColorPaletteControl/ColorPaletteControl.js
  assets/src/blocks/Spreadsheet/ArrowIcon.js
  assets/src/blocks/Spreadsheet/HighlightMatches.js
  assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
  assets/src/blocks/Spreadsheet/SpreadsheetScript.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/scss/blocks/Spreadsheet.scss
  src/Blocks/Spreadsheet.php
  src/Loader.php
  webpack.config.js
Labels: Review, [Test Env] titan

#2195 PLANET-7382 Move Submenu block into master theme
  assets/src/blocks/Submenu/SubmenuBlock.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/Submenu/SubmenuFrontend.js
  assets/src/blocks/Submenu/SubmenuItems.js
  assets/src/blocks/Submenu/SubmenuLevel.js
  assets/src/blocks/Submenu/example.js
  assets/src/blocks/Submenu/generateAnchor.js
  assets/src/blocks/Submenu/getHeadingsFromBlocks.js
  assets/src/blocks/Submenu/getHeadingsFromDom.js
  assets/src/blocks/Submenu/getSubmenuStyle.js
  assets/src/blocks/Submenu/makeHierarchical.js
  assets/src/blocks/editorIndex.js
  assets/src/blocks/frontendIndex.js
  assets/src/functions/deepClone.js
  assets/src/functions/unescape.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Submenu/SubmenuEditorStyle.scss
  assets/src/scss/blocks/Submenu/SubmenuStyle.scss
  assets/src/scss/editorStyle.scss
  src/Blocks/Submenu.php
  src/Loader.php
Labels: Review

#2183 PLANET-7306: Move Take Action Boxout block into master-theme
  assets/src/block-editor/ImageHoverControls/index.js
  assets/src/blocks/TakeActionBoxout/ImagePlaceholder.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
  assets/src/blocks/TakeActionBoxout/deprecated/takeActionBoxoutV1.js
  assets/src/blocks/editorIndex.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutEditorStyle.scss
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
  assets/src/scss/editorStyle.scss
  src/Blocks/BaseBlock.php
  src/Blocks/TakeActionBoxout.php
  src/Loader.php
  src/MasterBlocks.php
  src/MasterSite.php
  templates/blocks/take-action-boxout.twig
Labels: Review, [Test Env] rhea

#2198 Maintenance: move REST_NAMESPACE const to BaeBlock PHP class
  src/Blocks/BaseBlock.php
  src/Blocks/Spreadsheet.php
Labels: Review, [Test Env] iocaste

#2196 Include wide-blocks stylesheet into master theme
  assets/src/scss/layout/_wide-blocks.scss
  assets/src/scss/style.scss
Labels: Review, [Test Env] nix

#2197 PLANET-7324 Unify listing pages UI and refactor template code
  archive-p4_action.php
  author.php
  category.php
  index.php
  load-class-aliases.php
  src/Context.php
  src/ListingPage.php
  src/MasterSite.php
  src/TaxonomyCampaign.php
  tag.php
  taxonomy.php
  templates/all-actions.twig
  templates/all-posts.twig
  templates/author.twig
  templates/blocks/meta_fields.twig
  templates/listing-page.twig
  templates/tag.twig
  templates/taxonomy.twig
  tests/e2e/special-pages.spec.js
  tests/test-category-page.php
Labels: Review, [Test Env] oberon

#2200 Lower Sentry sampling rate to 25%
  functions.php
Labels: [Test Env] umbriel

#2184 PLANET-7378: Move the Happypoint block into master-theme
  assets/src/block-editor/HTMLSidebarHelp/HTMLSidebarHelp.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Happypoint/HappypointConstants.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Happypoint/HappypointFrontend.js
  assets/src/blocks/Happypoint/OverrideFormHelp.js
  assets/src/blocks/Happypoint/deprecated/HappypointBlocklV1.js
  assets/src/blocks/Happypoint/useHappypointImageData.js
  assets/src/blocks/editorIndex.js
  assets/src/blocks/frontendIndex.js
  assets/src/hooks/useHubspotEmbedCode.js
  assets/src/hooks/useScript/addScriptTag.js
  assets/src/hooks/useScript/useScript.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Happypoint/HappypointEditorStyle.scss
  assets/src/scss/blocks/Happypoint/HappypointStyle.scss
  assets/src/scss/editorStyle.scss
  src/Blocks/Happypoint.php
  src/Loader.php
Labels: Review, [Test Env] saturn

#2201 PLANET-7388: Update google/apiclient package
  .circleci/config.yml
  composer.json
  composer.lock
  src/MasterSite.php
  src/Migrations/M025CreateDefaultPostsPage.php
Labels: [Test Env] venus

#2199 PLANET-7343 Unify Post breadcrumbs structure
  src/Post.php
Labels: Review, [Test Env] pandora

#2204 Fix warning on articles list on author page
  src/ListingPage.php
Labels: [Test Env] rhea

#2203 PLANET-7404: Fix page type feed url matching
  src/CustomTaxonomy.php
Labels: [Test Env] titan
