Repository greenpeace/planet4-master-theme, pull requests merged in 2024-02, with the labels that each got.

#2164 PLANET-7213 Move OpenGraph Sidebar settings to master theme
  assets/src/block-editor/Sidebar/OpenGraphSidebar.js
  assets/src/block-editor/Sidebar/getSidebarFunctions.js
  assets/src/block-editor/SidebarFields/CheckboxSidebarField.js
  assets/src/block-editor/SidebarFields/ImageSidebarField.js
  assets/src/block-editor/SidebarFields/SelectSidebarField.js
  assets/src/block-editor/SidebarFields/TextSidebarField.js
  assets/src/block-editor/SidebarFields/TextareaSidebarField.js
  assets/src/block-editor/setupCustomSidebar.js
  assets/src/blocks/Counter/CounterBlock.js
  assets/src/blocks/Gallery/GalleryBlock.js
  assets/src/blocks/GuestBook/GuestBookBlock.js
  assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
  assets/src/blocks/editorIndex.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/functions/frontendRendered.js
  src/MasterBlocks.php
  webpack.config.js
Labels: Review, [Test Env] phoebe

#2210 PLANET-6081 Remove external link icon when no href
  assets/src/js/external_links.js
Labels: Review, [Test Env] venus

#2209 PLANET-7411 Change name of Media Archive to Greenpeace Media
  assets/src/js/Components/ArchivePicker/ArchivePickerToolbar.js
  assets/src/js/media_archive_editor_view.js
  src/MediaArchive/UiIntegration.php
Labels: Review, UAT Passed, [Test Env] saturn

#2169 PLANET-7238: Fix core/query layout for WP6.4
  assets/src/blocks/ActionsList/index.js
Labels: Review

#2211 PLANET-7319 Add a Gravity Forms e2e test for Hubspot feeds
  tests/e2e/gravity-forms.spec.js
  tests/e2e/tools/lib/gravity-forms.js
Labels: Review, [Test Env] pandora

#2213 PLANET-7405 Remove GF feed duplication custom code
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] neptune

#2212 PLANET-7425 Add post categories to body dataset
  single.php
  templates/base.twig
Labels: Review, [Test Env] rhea

#2189 fix: change gsutil into gcloud
  .circleci/config.yml
Labels: [Test Env] pluto

#2214 Fix Gravity Forms tests
  tests/e2e/gravity-forms.spec.js
Labels: Review, [Test Env] nix

#2163 PLANET-7342: Implement carousel layout to core/query
  assets/src/block-editor/QueryBlockExtension/index.js
  assets/src/blocks/ActionsList/index.js
  assets/src/editorIndex.js
  assets/src/js/app.js
  assets/src/js/query_loop_carousel.js
  assets/src/scss/blocks/ActionsList.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/editorStyle.scss
  assets/src/scss/layout/_query-loop-overrides.scss
  assets/src/scss/style.scss
  src/MasterBlocks.php
Labels: UAT Passed, [Test Env] leda

#2206 Planet 7379 Move remaining sidebar fields to Master theme
  assets/src/block-editor/NavigationType/NavigationType.js
  assets/src/block-editor/Sidebar/ActionSidebar.js
  assets/src/block-editor/Sidebar/AnalyticsTrackingSidebar.js
  assets/src/block-editor/Sidebar/CampaignThemeSidebar.js
  assets/src/block-editor/Sidebar/LocalThemeSettings.js
  assets/src/block-editor/Sidebar/PageHeaderSidebar.js
  assets/src/block-editor/Sidebar/PostParentLink.js
  assets/src/block-editor/Sidebar/SearchEngineOptimizationsSidebar.js
  assets/src/block-editor/Sidebar/ThemeSettings.js
  assets/src/block-editor/fromThemeOptions/fromThemeOptions.js
  assets/src/block-editor/saveMetaToPreview.js
  assets/src/block-editor/setupCustomSidebar.js
  assets/src/theme/p4ServerThemes.js
Labels: Review, [Test Env] nix

#2216 PLANET-7428: Add survey to WP Dashboard
  src/MasterSite.php
Labels: [Test Env] saturn
