Repository greenpeace/planet4-master-theme, pull requests merged in 2024-04, with the labels that each got.

#2242 PLANET-7400 Move Side image with text and CTA block pattern into master theme
  assets/src/block-templates/edit.js
  assets/src/block-templates/main-theme-url.js
  assets/src/block-templates/register.js
  assets/src/block-templates/save.js
  assets/src/block-templates/side-image-with-text-and-cta/block.json
  assets/src/block-templates/side-image-with-text-and-cta/index.js
  assets/src/block-templates/side-image-with-text-and-cta/template.js
  assets/src/block-templates/template-list.js
  assets/src/editorIndex.js
  src/Loader.php
  src/Patterns/BlockPattern.php
  src/Patterns/SideImageWithTextAndCta.php
Labels: Review, [Test Env] pluto

#2190 PLANET-7304 Move ENForm block to master theme
  admin/css/admin_en.css
  admin/js/enforms.js
  assets/src/block-editor/ImageOrButton/ImageOrButton.js
  assets/src/blocks/ENForm/CountrySelector.js
  assets/src/blocks/ENForm/ENFormBlock.js
  assets/src/blocks/ENForm/ENFormEditor.js
  assets/src/blocks/ENForm/ENFormEditorScript.js
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  assets/src/blocks/ENForm/ENFormScript.js
  assets/src/blocks/ENForm/ENFormSettings.js
  assets/src/blocks/ENForm/FormGenerator.js
  assets/src/blocks/ENForm/PositionSelector.js
  assets/src/blocks/ENForm/ShareButtons.js
  assets/src/blocks/ENForm/deprecated/ENFormV1.js
  assets/src/blocks/ENForm/deprecated/ENFormV2.js
  assets/src/blocks/ENForm/inputId.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/ENForm/ENFormEditorStyle.scss
  assets/src/scss/blocks/ENForm/ENFormStyle.scss
  assets/src/scss/blocks/ENForm/campaigns/_campaign_enform.scss
  assets/src/scss/blocks/ENForm/campaigns/_mixins.scss
  assets/src/scss/blocks/ENForm/campaigns/themes/_theme_climate.scss
  assets/src/scss/blocks/ENForm/components/_enform-full-width-bg.scss
  assets/src/scss/blocks/ENForm/components/_enform-full-width.scss
  assets/src/scss/blocks/ENForm/components/_enform-side-style.scss
  assets/src/scss/blocks/ENForm/components/_enform.scss
  assets/src/scss/editorStyle.scss
  functions.php
  images/en.png
  phpcs.xml.dist
  src/Api/ENForm.php
  src/Blocks/BaseBlock.php
  src/Blocks/Cookies.php
  src/Blocks/ENForm.php
  src/Blocks/Spreadsheet.php
  src/Controllers/Api/QuestionsController.php
  src/Controllers/Api/RestController.php
  src/Controllers/EnformFieldsListTable.php
  src/Controllers/EnformQuestionsListTable.php
  src/Controllers/EnsapiController.php
  src/Controllers/Menu/Controller.php
  src/Controllers/Menu/EnSettingsController.php
  src/Controllers/Menu/EnformPostController.php
  src/Loader.php
  src/MasterBlocks.php
  src/MasterSite.php
  src/Model/QuestionsModel.php
  src/View/View.php
  templates/block_templates/en_selected_meta_box.twig
  templates/block_templates/enform.twig
  templates/block_templates/enform/country_select.twig
  templates/block_templates/enform/enblock.twig
  templates/block_templates/enform/enform_post.twig
  templates/block_templates/enform/position_select.twig
  templates/block_templates/enform/tease-thankyou.twig
  templates/block_templates/selected_enform_fields.twig
  templates/block_templates/settings.twig
  webpack.config.js
Labels: Review, [Test Env] janus

#2245 PLANET-7457 Remove Layout sidebar section in Query Loop block
  theme.json
Labels: Review, [Test Env] pandora

#2229 PLANET-7290 Move Timeline block into master theme
  assets/src/block-templates/main-theme-url.js
  assets/src/blocks/Timeline/Timeline.js
  assets/src/blocks/Timeline/TimelineBlock.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
  assets/src/blocks/Timeline/TimelineFrontend.js
  assets/src/blocks/Timeline/TimelineLanguages.js
  assets/src/blocks/Timeline/TimelineScript.js
  assets/src/blocks/Timeline/URLDescriptionHelp.js
  assets/src/editorIndex.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Timeline/TimelineEditorStyle.scss
  assets/src/scss/blocks/Timeline/TimelineStyle.scss
  assets/src/scss/editorStyle.scss
  src/Blocks/Timeline.php
  src/Loader.php
  webpack.config.js
Labels: Review

#2231 PLANET-7420 Actions List: make the whole card clickable
  assets/src/js/actions_list_clickable_cards.js
  assets/src/js/app.js
  assets/src/js/query_loop_carousel.js
  assets/src/scss/blocks/ActionsList.scss
Labels: Review, UAT Passed, [Test Env] nix

#2248 Fix migration to avoid failing on post update errors
  src/MasterSite.php
  src/Migrations/M028MovePageHeaderSideBarOptions.php
Labels: [Test Env] venus

#2251 PLANET-7492 Make sure blocks are not registered twice
  assets/src/blocks/Media/MediaBlock.js
  assets/src/blocks/SocialMedia/SocialMediaBlock.js
  assets/src/blocks/Submenu/SubmenuBlock.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
  assets/src/blocks/Timeline/TimelineBlock.js
Labels: Review, [Test Env] pluto

#2247 PLANET-7462: Remove Lodash dependency from enforms.js
  admin/js/enforms.js
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/scss/blocks/ENForm/components/_enform-side-style.scss
  src/Loader.php
Labels: [Test Env] neptune

#2252 Fix ENForm background color
  assets/src/scss/blocks/ENForm/ENFormEditorStyle.scss
  assets/src/scss/blocks/ENForm/components/_enform-full-width-bg.scss
  assets/src/scss/blocks/ENForm/components/_enform-full-width.scss
  assets/src/scss/blocks/ENForm/components/_enform.scss
Labels: Review, [Test Env] jupiter

#2249 PLANET-7397 Move Issues block pattern into master theme
  assets/src/block-templates/issues/block.json
  assets/src/block-templates/issues/index.js
  assets/src/block-templates/issues/template.js
  assets/src/block-templates/register.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/Issues.php
Labels: Review, [Test Env] sinope

#2223 PLANET-7344 Make featured image mandatory for publishing
  src/MasterSite.php
  src/Migrations/M017NewIAToggle.php
  src/Migrations/M025CreateDefaultPostsPage.php
  tests/bootstrap.php
  tests/e2e/comments.spec.js
  tests/e2e/gallery.spec.js
  tests/e2e/gravity-forms.spec.js
  tests/e2e/navigation-bar.spec.js
  tests/e2e/password-protected-content.spec.js
  tests/e2e/search.spec.js
  tests/e2e/special-pages.spec.js
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/post.js
  tests/p4-testcase.php
  tests/test-action-type-custom-taxonomy.php
  tests/test-category-page.php
  tests/test-custom-permalinks.php
  tests/test-custom-taxonomy.php
  tests/test-open-graph.php
Labels: Review, [Test Env] rhea

#2254 PLANET-7458 Fix Actions List and Posts List carousel layout in RTL sites
  assets/src/scss/blocks/PostsList.scss
  assets/src/scss/layout/_query-loop-overrides.scss
Labels: Review, [Test Env] janus

#2250 PLANET-7175 Fix timeline block editor error
  assets/src/blocks/Timeline/TimelineEditorScript.js
  assets/src/functions/isLodash.js
Labels: Review, [Test Env] iocaste

#2253 PLANET-7491 Add see all link to Posts List block
  assets/src/blocks/PostsList/index.js
  assets/src/scss/blocks/PostsList.scss
  src/MasterBlocks.php
Labels: Review, UAT Passed, [Test Env] venus

#2228 PLANET-7390: Require Timber as composer package
  composer.json
  composer.lock
  functions.php
  src/AnalyticsValues.php
  src/Blocks/ENForm.php
  src/Campaigns.php
  src/CloudflarePurger.php
  src/CustomTaxonomy.php
  src/GravityFormsExtensions.php
  src/Importer.php
  src/ListingPage.php
  src/Loader.php
  src/MasterBlocks.php
  src/MasterSite.php
  src/Post.php
  src/Post/ReadingTimeCalculator.php
  src/Search.php
  src/Settings.php
  src/Settings/Features.php
  src/Sitemap.php
  tests/test-category-page.php
  tests/test-open-graph.php
Labels: [Test Env] leda

#2262 PLANET-7199 Fix Image block caption/credits
  src/MasterSite.php
Labels: Review, UAT Needed, [Test Env] jupiter

#2265 Rename object_to_array function
  src/MasterBlocks.php
  templates/block_templates/enform/enform_post.twig
Labels: Review, [Test Env] venus

#2260 PLANET-7490 Update search limit from 6 to 8 on Greenpeace Media
  admin/css/archive-picker.css
  assets/src/js/Components/ArchivePicker/MultiSearchOption.js
Labels: Review, UAT Passed, [Test Env] oberon

#2267 Add id for page-content and post-content
  templates/evergreen.twig
  templates/listing-page.twig
  templates/page.twig
  templates/single-attachment.twig
  templates/single-page.twig
  templates/single-password.twig
  templates/single.twig
Labels: Review, [Test Env] janus

#2269 Adding a new planet4 category
  src/MasterBlocks.php
Labels: Review, [Test Env] iocaste

#2256 PLANET-7442 Move P4 Columns block to the theme
  assets/src/blocks/Columns/ColumnConstants.js
  assets/src/blocks/Columns/Columns.js
  assets/src/blocks/Columns/ColumnsBlock.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Columns/ColumnsFrontend.js
  assets/src/blocks/Columns/ColumnsImagePlaceholder.js
  assets/src/blocks/Columns/ColumnsTasks.js
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/blocks/Columns/example.js
  assets/src/blocks/Columns/imageSizes.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Columns/ColumnsEditorStyle.scss
  assets/src/scss/blocks/Columns/ColumnsStyle.scss
  assets/src/scss/components/_image-hover-buttons.scss
  assets/src/scss/editorStyle.scss
  src/Blocks/Columns.php
  src/Loader.php
  src/MasterBlocks.php
Labels: Review, [Test Env] pandora

#2270 Add stretched link variations from plugin
  assets/src/block-variations/index.js
  assets/src/editorIndex.js
  assets/src/scss/editorStyle.scss
  assets/src/scss/style.scss
  assets/src/scss/variations/stretched-link/edit.scss
  assets/src/scss/variations/stretched-link/index.scss
Labels: Review, [Test Env] venus

#2274 Hide GravityForms update message
  admin/css/dashboard.css
Labels: Review, [Test Env] iocaste
