Repository greenpeace/planet4-master-theme, pull requests merged in 2024-11, with the labels that each got.

#2430 PLANET-7446: Force no lightbox
  assets/src/blocks/Gallery/GalleryFrontend.js
  assets/src/blocks/components/Lightbox/setupLightboxForImages.js
  assets/src/frontendIndex.js
  assets/src/scss/blocks/Gallery/styles/GalleryCarousel.scss
  assets/src/scss/blocks/Gallery/styles/GalleryGrid.scss
  assets/src/scss/blocks/Gallery/styles/GalleryThreeColumns.scss
  assets/src/scss/pages/_page.scss
  assets/src/scss/style.scss
  assets/src/scss/vendors/photoswipe/_main-settings.scss
  assets/src/scss/vendors/photoswipe/main.scss
  assets/src/scss/vendors/photoswipe/p4-skin.scss
  assets/src/scss/vendors/photoswipe/planet4-photoswipe.scss
  images/vendors/photoswipe/default-skin.png
  images/vendors/photoswipe/default-skin.svg
  images/vendors/photoswipe/preloader.gif
  theme.json
Labels: Review, [Test Env] tavros

#2416 PLANET-7564: Implement media replacement feature
  admin/js/media_replacer.js
  src/Loader.php
  src/MediaReplacer.php
Labels: Review, [Test Env] proteus

#2431 PLANET-7563 Apply New Link Style to lists in Posts
  assets/src/scss/pages/post/_article-content.scss
Labels: Review, [Test Env] deimos

#2370 PLANET-7592 Re-implement related articles with Query Loop block
  assets/src/js/app.js
  assets/src/js/remove_related_section_no_posts.js
  assets/src/scss/pages/post/_post.scss
  functions.php
  single.php
  tests/e2e/blocks/related-articles.spec.js
Labels: Review, [Test Env] saturn

#2433 PLANET-7445: Migrate Split Two Columns blocks to Columns blocks
  exporter-helper.php
  src/BlockSettings.php
  src/Importer.php
  src/Migrations/M032MigrateSplit2ColumnBlock.php
  src/Migrations/Utils/Constants.php
  src/Migrations/Utils/Functions.php
  src/Migrator.php
Labels: Review, UAT Passed, [Test Env] titan

#2422 PLANET-7614 Add categories filter to News & Stories page
  assets/src/js/listing_pages.js
  assets/src/scss/layout/_forms.scss
  assets/src/scss/pages/_listing-page.scss
  functions.php
  src/ListingPage.php
  templates/listing-page-filters.twig
  templates/listing-page.twig
Labels: Review, UAT Passed, [Test Env] oberon

#2438 Fix tag page when redirection is not set
  tag.php
Labels: Review, [Test Env] pandora

#2439 Fix tiny search page typo
  templates/search.twig
Labels: Review, [Test Env] phobos

#2442 Fix Related Posts URL for see all posts
  functions.php
Labels: Review, [Test Env] umbriel

#2443 Show media import button only on Media Library
  src/Exporter.php
Labels: Review, [Test Env] venus

#2446 PLANET-7666 Add template include for extra footer block
  templates/footer.twig
Labels: Review, [Test Env] deimos

#2436 PLANET-7523 Remove Twitter from Social Media block and rename it Meta
  assets/src/blocks/SocialMedia/SocialMediaBlock.js
  assets/src/blocks/SocialMedia/SocialMediaConstants.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  src/Blocks/SocialMedia.php
  src/Migrations/M033MigrateSocialMediaTwitterBlockToEmbedBlock.php
  src/Migrations/Utils/Constants.php
  src/Migrations/Utils/Functions.php
  src/Migrator.php
  templates/blocks/social-media.twig
Labels: Review, UAT Passed

#2449 PLANET-7618 Make sure nav links don't exceed 2 lines
  assets/src/scss/layout/_navbar.scss
  templates/burger-menu-items.twig
  templates/navigation-submenu.twig
Labels: Review, [Test Env] titan

#2450 PLANET-7672 Update TAB custom image width in the editor
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutEditorStyle.scss
Labels: Review, [Test Env] sinope

#2448 PLANET-7670 Show author override in Related Posts
  assets/src/scss/blocks/PostsList/PostsListStyle.scss
  assets/src/scss/pages/post/_post.scss
  functions.php
Labels: Review, [Test Env] telesto

#2454 Add Social Media block API endpoint
  functions.php
  src/Api/SocialMedia.php
Labels: Review, [Test Env] phobos

#2445 PLANET-7648: Added opt-in archive notice on old posts
  assets/src/scss/pages/post/_post.scss
  single.php
  src/Features/OldPostsArchiveNotice.php
  src/Migrations/M034PrePopulateOldPostsArchiveNotice.php
  src/Migrator.php
  src/Post.php
  src/Settings.php
  src/Settings/Features.php
  templates/single.twig
Labels: Review, UAT Passed

#2453 PLANET-7674: Fix tags list
  assets/src/block-editor/TagSelector/index.js
Labels: Review, [Test Env] pandora

#2187 PLANET-7135: Fix country selector tab index
  assets/src/js/app.js
  assets/src/js/country_selector.js
  assets/src/scss/layout/_country-selector.scss
  templates/footer.twig
  templates/footer_country_selector.twig
  templates/footer_social_media.twig
Labels: Review, [Test Env] jupiter

#2458 PLANET-7651 Fix PageHeader for tablets
  assets/src/scss/blocks/core-overrides/MediaText.scss
Labels: Review, [Test Env] pluto

#2460 PLANET-7679 Add Bluesky icon for footer social media
  assets/src/images/icons/bluesky.svg
Labels: Review, [Test Env] titan
