Repository greenpeace/planet4-master-theme, pull requests merged in 2024-09, with the labels that each got.

#2361 PLANET-7596 Gravity forms won't send thank you pages
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] nix

#2362 Revert Greenpeace Media specs
  tests/e2e/greenpeace-media.spec.js
Labels: [Test Env] saturn

#2366 Add line-clamp CSS attribute
  assets/src/scss/blocks/ActionsList.scss
  assets/src/scss/blocks/Gallery/styles/GalleryCarousel.scss
  assets/src/scss/blocks/PageHeader.scss
  assets/src/scss/blocks/PostsList.scss
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutEditorStyle.scss
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
  assets/src/scss/layout/_featured-action.scss
  assets/src/scss/pages/_listing-page.scss
  assets/src/scss/pages/post/_article-content.scss
Labels: Review, [Test Env] iocaste

#2364 PLANET-7602: Fix link hover color
  assets/src/scss/base/_body.scss
Labels: [Test Env] venus

#2355 Unify default tests environment
  tests/e2e/env/.env.ci
  tests/e2e/env/.env.default
Labels: Review, [Test Env] iocaste

#2365 PLANET-7512 Update Take Action Boxout styles
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutEditorStyle.scss
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
  images/close-boxout.svg
  templates/blocks/take-action-boxout.twig
Labels: Review, UAT Passed, [Test Env] pluto

#2372 Fix error in the Counter block
  assets/src/blocks/Counter/CounterScript.js
Labels: Review, [Test Env] iocaste

#2369 PLANET-7606 Fix Cookies block crashing in the frontend
  assets/src/blocks/Cookies/CookiesBlock.js
  assets/src/blocks/Cookies/CookiesEditor.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/blocks/Cookies/CookiesScript.js
Labels: Review, [Test Env] nix

#2373 Add Ukraine to country selector
  languages/planet4-master-theme-en_GB.l10n.php
  languages/planet4-master-theme-it_IT.l10n.php
  languages/planet4-master-theme-nb_NO.l10n.php
  languages/planet4-master-theme-pt_BR.l10n.php
  languages/planet4-master-theme-uk.l10n.php
  templates/countries.json
Labels: Review, [Test Env] venus

#2371 PLANET-7220: Add definitions to blocks settings
  assets/src/block-editor/QueryLoopBlockExtension/index.js
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Accordion/AccordionEditorScript.js
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/blocks/Columns/ColumnsBlock.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Cookies/CookiesBlock.js
  assets/src/blocks/Cookies/CookiesEditor.js
  assets/src/blocks/Counter/CounterBlock.js
  assets/src/blocks/Counter/CounterEditor.js
  assets/src/blocks/ENForm/ENFormBlock.js
  assets/src/blocks/ENForm/ENFormSettings.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/PostsList/index.js
  assets/src/blocks/SocialMedia/SocialMediaBlock.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
  assets/src/blocks/Submenu/SubmenuBlock.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/Timeline/TimelineBlock.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
Labels: Review, UAT Passed, [Test Env] pandora

#2376 PLANET-7610: Rename the Submenu block as Table Of Contents
  assets/src/blocks/Submenu/SubmenuFrontend.js
  assets/src/blocks/TableOfContents/TableOfContentsBlock.js
  assets/src/blocks/TableOfContents/TableOfContentsEditor.js
  assets/src/blocks/TableOfContents/TableOfContentsFrontend.js
  assets/src/blocks/TableOfContents/TableOfContentsItems.js
  assets/src/blocks/TableOfContents/TableOfContentsLevel.js
  assets/src/blocks/TableOfContents/example.js
  assets/src/blocks/TableOfContents/generateAnchor.js
  assets/src/blocks/TableOfContents/getHeadingsFromBlocks.js
  assets/src/blocks/TableOfContents/getHeadingsFromDom.js
  assets/src/blocks/TableOfContents/getTableOfContentsStyle.js
  assets/src/blocks/TableOfContents/makeHierarchical.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/TableOfContents/TableOfContentsEditorStyle.scss
  assets/src/scss/blocks/TableOfContents/TableOfContentsStyle.scss
  assets/src/scss/editorStyle.scss
  src/Blocks/TableOfContents.php
  src/Loader.php
Labels: Review, [Test Env] venus

#2374 PLANET-7584 Fix PostsList block in the editor
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/ActionsList/ActionsListEditorStyle.scss
  assets/src/scss/blocks/ActionsList/ActionsListStyle.scss
  assets/src/scss/blocks/PostsList/PostsListEditorStyle.scss
  assets/src/scss/blocks/PostsList/PostsListStyle.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/editorStyle.scss
Labels: Review

#2378 PLANET-7563 Apply link styles to rest of body links
  assets/src/scss/base/_mixins.scss
  assets/src/scss/base/_typography.scss
  assets/src/scss/blocks/core-overrides/Table.scss
  assets/src/scss/core-overrides/_heading.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/pages/post/_article-content.scss
Labels: Review, UAT Passed, [Test Env] iocaste

#2368 PLANET-7454 Implement GF variables in page load
  assets/src/js/gravityforms-client-side.js
  src/GravityFormsExtensions.php
Labels: Review, UAT Needed, [Test Env] pluto

#2379 PLANET-7615: Add block post type filter
  src/BlockSettings.php
  src/Loader.php
Labels: Review, [Test Env] nix

#2381 PLANET-7617 Apply caption styles to all figcaption elements
  assets/src/scss/base/_typography.scss
  assets/src/scss/blocks/core-overrides/Image.scss
  assets/src/scss/blocks/core-overrides/Table.scss
  assets/src/scss/core-overrides/_image.scss
  assets/src/scss/pages/post/_article-content.scss
Labels: Review, UAT Passed, [Test Env] venus

#2377 PLANET-7611: Use the block name "Happy Point" consistently
  assets/src/blocks/HappyPoint/HappyPointBlock.js
  assets/src/blocks/HappyPoint/HappyPointConstants.js
  assets/src/blocks/HappyPoint/HappyPointEditor.js
  assets/src/blocks/HappyPoint/HappyPointFrontend.js
  assets/src/blocks/HappyPoint/OverrideFormHelp.js
  assets/src/blocks/HappyPoint/deprecated/HappyPointBlockV1.js
  assets/src/blocks/HappyPoint/useHappyPointImageData.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/js/Components/ArchivePicker/ArchivePicker.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/HappyPoint/HappyPointEditorStyle.scss
  assets/src/scss/blocks/HappyPoint/HappyPointStyle.scss
  assets/src/scss/editorStyle.scss
  src/Blocks/HappyPoint.php
  src/Loader.php
  src/Settings.php
Labels: Review, [Test Env] jupiter

#2385 Align the Read More button in the Actions List block
  assets/src/scss/blocks/ActionsList/ActionsListStyle.scss
Labels: Review, UAT Passed, [Test Env] pluto

#2386 Fix special characters in submenu navigation and in footer
  templates/burger-menu-items.twig
  templates/footer.twig
  templates/navigation-submenu.twig
Labels: Review, [Test Env] venus

#2387 Remove native share button background
  assets/src/scss/components/_share-buttons.scss
Labels: Review, [Test Env] nix
