Repository greenpeace/planet4-master-theme, pull requests merged in 2024-12, with the labels that each got.

#2459 Simplify CF zone code to only remove www. from hostname
  src/Commands/SaveCloudflareKey.php
Labels: Review, [Test Env] janus

#2462 PLANET-7482 Use proper function for displaying author bio
  assets/src/scss/pages/_author.scss
  assets/src/scss/pages/post/_author-block.scss
  templates/author.twig
  templates/blocks/author_profile.twig
Labels: Review, [Test Env] oberon

#2455 PLANET-7677: Consolidate parent act page injected to window p4_vars
  assets/src/block-editor/PostSelector/index.js
  assets/src/blocks/ActionsList/index.js
  src/MasterBlocks.php
Labels: Review, [Test Env] nix

#2444 PLANET-7662: Fix action pages dropdown
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
Labels: [Test Env] tavros

#2464 Expand PR template
  .github/pull_request_template.md
Labels: Review, [Test Env] proteus

#2467 PLANET-7688 Fixed huge space between Spotify embed and captions
  assets/src/scss/blocks/core-overrides/Embed.scss
Labels: Review, [Test Env] umbriel

#2441 PLANET-7660: Fix checkbox mark alignement
  assets/src/scss/base/_mixins.scss
  assets/src/scss/base/_variables.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_gravity-forms.scss
  assets/src/scss/pages/post/_comments-form.scss
Labels: Review, [Test Env] rhea

#2471 Fix undefined act_page warning
  src/MasterBlocks.php
  src/Post.php
Labels: Review, [Test Env] titan

#2474 PLANET-7694 Fix design issues in Posts List with carousel style
  assets/src/scss/layout/_query-loop-overrides.scss
Labels: Review, [Test Env] telesto

#2477 Follow up GF checkbox styles issue
  assets/src/scss/layout/_forms.scss
Labels: Review, [Test Env] tavros

#2469 Update apiVersion for our blocks to 3
  assets/src/block-templates/action/block.json
  assets/src/block-templates/campaign/block.json
  assets/src/block-templates/deep-dive-topic/block.json
  assets/src/block-templates/deep-dive/block.json
  assets/src/block-templates/get-informed/block.json
  assets/src/block-templates/high-level-topic/block.json
  assets/src/block-templates/highlighted-cta/block.json
  assets/src/block-templates/homepage/block.json
  assets/src/block-templates/issues/block.json
  assets/src/block-templates/page-header/block.json
  assets/src/block-templates/quick-links/block.json
  assets/src/block-templates/reality-check/block.json
  assets/src/block-templates/side-image-with-text-and-cta/block.json
  assets/src/block-templates/take-action/block.json
Labels: Review, [Test Env] mars

#2475 PLANET-7697 Add Posts/Actions List indicators only when needed
  assets/src/js/query_loop_carousel.js
Labels: Review, [Test Env] deimos

#2481 Fix page header title font-weight
  assets/src/scss/layout/_page-header.scss
Labels: Review, UAT Passed, [Test Env] jupiter

#2432 PLANET-6532 Adding a bottom navigation block for pages
  assets/src/scss/pages/_page.scss
  functions.php
  images/arrow_back.svg
  images/arrow_forward.svg
  templates/page.twig
Labels: Review, UAT Passed, [Test Env] saturn

#2465 PLANET-7671 Add post type filter to News & Stories page
  assets/src/js/listing_pages.js
  assets/src/scss/pages/_listing-page.scss
  functions.php
  src/ListingPage.php
  templates/listing-page-filters.twig
Labels: Review, UAT Passed, [Test Env] leda

#2472 PLANET-7656 Prepare for WordPress 6.7 upgrade
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/PostsList/index.js
  assets/src/editorIndex.js
  tests/e2e/navigation-bar.spec.js
  tests/e2e/tools/lib/post.js
Labels: Review, [Test Env] janus

#2484 Remove campaign related images
  images/antarctic/logo-dark.png
  images/antarctic/logo-light.png
  images/arctic/logo-dark.png
  images/arctic/logo-light.png
  images/climate/logo-dark.png
  images/climate/logo-light.png
  images/forest/logo-dark.png
  images/forest/logo-light.png
  images/oceans/logo-dark.png
  images/oceans/logo-light.png
  images/oil/logo-dark.png
  images/oil/logo-light.png
  images/plastic/logo-dark.png
  images/plastic/logo-light.png
Labels: Review, [Test Env] oberon

#2188 PLANET-7393: Update webpack to v5
  .circleci/config.yml
  .eslintrc.json
  assets/src/blocks/Articles/ArticlePreview.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
  assets/src/frontendIndex.js
  assets/src/js/Components/ArchivePicker/ArchivePickerToolbar.js
  assets/src/js/Components/ArchivePicker/SingleSidebar.js
  assets/src/js/external_links.js
  assets/src/js/menu_editor.js
  assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/scss/blocks/Gallery/styles/GalleryCarousel.scss
  assets/src/scss/blocks/SocialMedia/SocialMediaStyle.scss
  assets/src/scss/blocks/Timeline/TimelineStyle.scss
  assets/src/scss/bootstrap-build.scss
  assets/src/scss/components/_blockquote.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/layout/_page-header.scss
  assets/src/scss/pages/post/_post.scss
  assets/src/scss/pages/search/_search-results.scss
  package-lock.json
  package.json
  src/MasterBlocks.php
  tests/e2e/404.spec.js
  tests/e2e/blocks/carousel-header.spec.js
  tests/e2e/greenpeace-media.spec.js
  tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
  tests/e2e/tools/lib/gravity-forms.js
  tests/e2e/tools/lib/post.js
  webpack.config.js
Labels: Review, [Test Env] phoebe

#2486 Remove beta blocks that we won't migrate
  exporter-helper.php
  src/BlockSettings.php
  src/Importer.php
Labels: Review, [Test Env] nix
