Repository greenpeace/planet4-master-theme, pull requests merged in 2024-08, with the labels that each got.

#2339 PLANET-7550: Move Deep Dive Topic pattern block to theme
  assets/src/block-templates/deep-dive-topic/block.json
  assets/src/block-templates/deep-dive-topic/index.js
  assets/src/block-templates/deep-dive-topic/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/DeepDiveTopic.php
Labels: Review

#2337 PLANET-7565: Fix warnings in WordPress 6.6.x
  assets/src/block-editor/Sidebar/ActionSidebar.js
  assets/src/block-editor/Sidebar/AnalyticsTrackingSidebar.js
  assets/src/block-editor/Sidebar/CampaignSidebar.js
  assets/src/block-editor/Sidebar/OpenGraphSidebar.js
  assets/src/block-editor/Sidebar/PageHeaderSidebar.js
  assets/src/block-editor/Sidebar/SearchEngineOptimizationsSidebar.js
  assets/src/blocks/ActionsList/index.js
Labels: Review

#2334 PLANET-7565: Fix tests broken by WordPress v6.6.x
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/post.js
Labels: [Test Env] sinope

#2341 PLANET-7389 Add PHP8.3 tests job
  .circleci/config.yml
  composer.json
  composer.lock
  exporter-helper.php
  src/Loader.php
Labels: Review, [Test Env] sinope

#2345 PLANET-7565: Fix tests broken by WordPress v6.6.x
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/post.js
Labels: Review, [Test Env] titan

#2340 PLANET-7540: Clean up auto-save revisions fix
  single-campaign.php
  src/Loader.php
Labels: Review, [Test Env] jupiter

#2336 PLANET-7549: Move Campaign pattern block to theme
  assets/src/block-templates/campaign/block.json
  assets/src/block-templates/campaign/index.js
  assets/src/block-templates/campaign/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/BlockPattern.php
  src/Patterns/Campaign.php
Labels: Review, [Test Env] venus

#2301 PLANET-7362 Write a Greenpeace Media e2e test for importing images
  tests/e2e/greenpeace-media.spec.js
  tests/e2e/tools/lib/media-library.js
Labels: Review, [Test Env] saturn

#2348 Fix Action Button Text
  assets/src/blocks/ActionCustomButtonText/edit.js
Labels: Review, [Test Env] tavros

#2342 PLANET-7576: Move Planet4 blocks (beta) category
  assets/src/editorIndex.js
  src/Loader.php
  src/MasterBlocks.php
Labels: Review, [Test Env] pandora

#2326 PLANET-7542: Move e2e tests from the plugin to the theme
  src/Admin/Rest.php
  src/Admin/Transient.php
  src/Loader.php
  tests/e2e/blocks/blocks-report-api.spec.js
  tests/e2e/blocks/carousel-header.spec.js
  tests/e2e/blocks/columns-icons.spec.js
  tests/e2e/blocks/columns-images.spec.js
  tests/e2e/blocks/columns-no-image.spec.js
  tests/e2e/blocks/columns-tasks.spec.js
  tests/e2e/blocks/enform.spec.js
  tests/e2e/blocks/page-layouts-modal.spec.js
  tests/e2e/blocks/spreadsheet.spec.js
  tests/e2e/blocks/take-action-boxout.spec.js
  tests/e2e/fixtures/enform/enformData.js
  tests/e2e/fixtures/enform/ensapi_sample_fields_response.json
  tests/e2e/fixtures/enform/ensapi_sample_pages_response.json
  tests/e2e/fixtures/enform/ensapi_sample_question_220954_response.json
  tests/e2e/fixtures/enform/ensapi_sample_question_236734_response.json
  tests/e2e/fixtures/enform/ensapi_sample_question_3877_response.json
  tests/e2e/fixtures/enform/ensapi_sample_questions_response.json
  tests/e2e/tools/lib/columns.js
Labels: Review, [Test Env] umbriel

#2352 PLANET-7557 Fix author page pagination
  src/AuthorPage.php
Labels: Review, [Test Env] jupiter

#2353 PLANET-7499: Apply backend text changes on Gallery block
  assets/src/blocks/Gallery/GalleryEditor.js
Labels: Review, UAT Passed, [Test Env] oberon

#2324 PLANET-7556 Implement purchase dataLayer event for forms without redirect
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] neptune

#2358 Skip Media spec test
  tests/e2e/greenpeace-media.spec.js
Labels: Review, [Test Env] pandora

#2338 PLANET-7548: Move Action pattern block to theme
  assets/src/block-templates/action/block.json
  assets/src/block-templates/action/index.js
  assets/src/block-templates/action/template.js
  assets/src/block-templates/template-list.js
  src/Patterns/Action.php
  src/Patterns/BlockPattern.php
Labels: Review, [Test Env] pluto
