Repository greenpeace/planet4-master-theme, pull requests merged in 2024-06, with the labels that each got.

#2282 PLANET-7263 Media Archive: add in editor option for P4 blocks
  admin/css/archive-picker.css
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/EditableBackground.js
  assets/src/js/Components/ArchivePicker/ArchivePicker.js
  assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
  src/Blocks/CarouselHeader.php
Labels: [Test Env] oberon

#2299 PLANET-7480 Stop hiding page header when Query Loop block is used
  src/Context.php
Labels: Review, [Test Env] pandora

#2278 PLANET-7380 Drop Campaigns theme customizer
  assets/src/block-editor/Sidebar/CampaignSidebar.js
  assets/src/block-editor/Sidebar/CampaignThemeSidebar.js
  assets/src/block-editor/Sidebar/LocalThemeSettings.js
  assets/src/block-editor/Sidebar/ThemeSettings.js
  assets/src/block-editor/fromThemeOptions/fromThemeOptions.js
  assets/src/block-editor/setupCustomSidebar.js
  assets/src/scss/blocks/ENForm/campaigns/themes/_theme_climate.scss
  assets/src/theme/p4ServerThemes.js
  single-campaign.php
  src/Context.php
  src/PostCampaign.php
  theme_options/climate.json
  theme_options/default.json
  theme_options/forest.json
  theme_options/oceans.json
  theme_options/plastic.json
  themes/climate.json
  themes/forest.json
  themes/oceans.json
  themes/plastic.json
Labels: Review

#2300 PLANET-7536 Add share text to WhatsApp share button
  templates/blocks/share_buttons.twig
  tests/e2e/gravity-forms.spec.js
Labels: Review, [Test Env] nix

#2297 Add filter hook to allow changing the formSubmission event parameters
  src/GravityFormsExtensions.php
Labels: Review

#2296 Change tweet to post
  assets/src/blocks/ENForm/ShareButtons.js
  templates/blocks/share_buttons.twig
Labels: Review, [Test Env] umbriel

#2306 PLANET-7535 Credit is removed when caption is edited
  src/MasterSite.php
Labels: Review, [Test Env] janus

#2312 PLANET-7537 Fix slice offset on Cloudflare hostname
  src/Commands/SaveCloudflareKey.php
Labels: Review, [Test Env] pandora

#2311 PLANET-7524 Add noindex meta tag on pages that are excluded from search
  src/MasterSite.php
Labels: [Test Env] venus
