Repository greenpeace/planet4-master-theme, pull requests merged in 2025-05, with the labels that each got.

#2613 PLANET-6407 Fix Spreadsheet block indicators
  assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
  assets/src/scss/blocks/Spreadsheet.scss
  assets/src/scss/editorOverrides.scss
Labels: Review, [Test Env] janus

#2614 Adjust Sentry server name to work in all cases
  functions.php
Labels: Review, [Test Env] iocaste

#2617 PLANET-7801 Remove unwanted margin bottom in sticky Take Action Boxout
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
Labels: Review, [Test Env] venus

#2612 PLANET-7650 Fix News & Stories top spacing on mobile
  assets/src/scss/base/_body.scss
  assets/src/scss/layout/_page-header.scss
  assets/src/scss/pages/_page.scss
  templates/base.twig
  templates/navigation-bar.twig
Labels: Review, [Test Env] jupiter

#2611 PLANET-7720: Use semantic HTML to convey content meaning
  assets/src/js/toggle_comment_submit.js
  src/Post.php
  templates/burger-menu.twig
  templates/comments_section.twig
  templates/desktop-menu.twig
  templates/evergreen.twig
  templates/listing-page.twig
  templates/navigation-bar.twig
  templates/navigation-bar_min.twig
  templates/page.twig
  templates/single-attachment.twig
  templates/single-page.twig
  templates/single-password.twig
  templates/single.twig
Labels: Review, UAT Passed, [Test Env] saturn

#2616 PLANET-7432 Reduce Typographic wt of non-links author's name on PostL…
  assets/src/scss/blocks/PostsList/PostsListStyle.scss
  assets/src/scss/pages/post/_post.scss
  templates/single.twig
Labels: [Test Env] proteus

#2615 PLANET-7776 Remove link styles from Quick Links & Deep Dive patterns
  assets/src/scss/variations/stretched-link/edit.scss
  assets/src/scss/variations/stretched-link/index.scss
Labels: Review, UAT Passed, [Test Env] pluto

#2492 PLANET-7657: Add support for Take Action pages
  assets/src/block-editor/setupTaxonomyBreadcrumbBlock.js
  assets/src/blocks/ActionsList/index.js
  functions.php
  src/Api/QueryLoopExtension.php
  src/Blocks/QueryLoopExtension.php
  src/Loader.php
Labels: Review, [Test Env] sinope

#2606 PLANET-7777 Added transparent background effect for Homepage nav
  assets/src/js/app.js
  assets/src/js/homepage_transparent_nav.js
  assets/src/scss/components/_buttons.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/style.scss
  images/white_arrow_up.svg
  src/MasterSite.php
  src/Migrations/M047EnableTransparentNavigation.php
  src/Migrator.php
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] oberon

#2624 PLANET-7432 Revert fix added for missing default avatar for author override
  templates/single.twig
Labels: Review

#2623 Fixed Color issues on Transparent navbar
  assets/src/scss/components/_buttons.scss
  assets/src/scss/layout/navbar/_languages.scss
  assets/src/scss/style.scss
Labels: Review, [Test Env] neptune

#2619 Allow links in Accordion content
  assets/src/blocks/Accordion/AccordionEditor.js
Labels: Review, [Test Env] telesto

#2628 Fix e2e tests for WordPress 6.8.1
  tests/e2e/blocks/audio-video.spec.js
  tests/e2e/blocks/posts-list.spec.js
  tests/e2e/blocks/spreadsheet.spec.js
  tests/e2e/comments.spec.js
  tests/e2e/navigation-bar.spec.js
  tests/e2e/password-protected-content.spec.js
  tests/e2e/related-posts.spec.js
  tests/e2e/search.spec.js
  tests/e2e/special-pages.spec.js
  tests/e2e/tools/lib/editor.js
Labels: Review, [Test Env] iocaste

#2630 Revert "PLANET-7657: Add support for Take Action pages"
  assets/src/block-editor/setupTaxonomyBreadcrumbBlock.js
  assets/src/blocks/ActionsList/index.js
  functions.php
  src/Api/QueryLoopExtension.php
  src/Blocks/QueryLoopExtension.php
  src/Loader.php
Labels: Review, [Test Env] jupiter

#2621 PLANET-7792 Register block pattern categories
  src/Loader.php
Labels: Review, [Test Env] titan

#2622 PLANET-7456 Apply link styles in lists
  assets/src/scss/base/_mixins.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/pages/_page.scss
  assets/src/scss/pages/post/_article-content.scss
Labels: Review, [Test Env] mars

#2626 PLANET-7811 Fix Posts List Block manual override
  src/Blocks/QueryLoopExtension.php
Labels: Review, [Test Env] pluto

#2634 Fix TermSelector findTerm function
  assets/src/block-editor/TermSelector/index.js
Labels: Review, [Test Env] umbriel

#2635 Fix error with Entry Dates in Gravity Forms
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] proteus

#2631 PLANET-7657: Add support for Take Action pages in the Actions List block
  assets/src/block-editor/PostSelector/index.js
  assets/src/block-editor/setupTaxonomyBreadcrumbBlock.js
  assets/src/blocks/ActionsList/index.js
  src/Blocks/QueryLoopExtension.php
  tests/e2e/blocks/covers-take-action.spec.js
Labels: Review, [Test Env] saturn

#2625 PLANET-7808: Add a global setting for taxonomy breadcrumb
  assets/src/block-editor/QueryLoopBlockExtension/index.js
  assets/src/block-editor/setupTaxonomyBreadcrumbBlock.js
  functions.php
  src/MasterBlocks.php
  src/Migrations/M048SetDefaultTaxonomyBreadcrumb.php
  src/Migrator.php
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] janus
