Repository greenpeace/planet4-master-theme, pull requests merged in 2025-09, with the labels that each got.

#2733 PLANET-7921: Fix bug with the manual override feature in the Posts List block
  src/Blocks/QueryLoopExtension.php
Labels: Review, [Test Env] umbriel

#2730 PLANET-7904 Fix Sentry TypeError in GF form filter
  src/GravityFormsExtensions.php
Labels: Review, [Test Env] sinope

#2736 PLANET-7907 Strengthen Account Password Policy
  assets/src/js/hide_weak_pw_checkbox.js
  src/EnqueueController.php
  src/MasterSite.php
  webpack.config.js
Labels: Review, [Test Env] titan

#2748 Fix search e2e test
  tests/e2e/search.spec.js
Labels: Review, [Test Env] umbriel

#2746 Add migration for missing button type
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/PostsList/index.js
  src/Migrations/M059AddMissingTypeToButtons.php
  src/Migrator.php
Labels: Review, [Test Env] neptune

#2750 PLANET-7919 Fix Sentry warning about undefined post__in
  src/Blocks/QueryLoopExtension.php
Labels: Review, [Test Env] jupiter

#2757 Hide ElasticPress version notice
  admin/css/options.css
Labels: Review, [Test Env] pluto
