Repository greenpeace/planet4-master-theme, pull requests merged in 2025-08, with the labels that each got.

#2715 PLANET-7770 Added default site icon
  src/Migrations/M055AddDefaultSiteIcon.php
  src/Migrator.php
Labels: Review, [Test Env] tavros

#2713 PLANET-7821 Fix elasticpress post_date type mapping issue
  src/Search/ElasticSearch.php
  templates/tease-search.twig
Labels: Review, [Test Env] saturn

#2716 Planet 7821 full es sync
  src/CronJob.php
  src/Loader.php
  src/Search/ElasticSearch.php
Labels: Review, [Test Env] deimos

#2723 Change IRL label to offline
  assets/src/block-editor/Sidebar/ActionSidebar.js
  assets/src/js/resistance-hub-campaign.js
  single-p4_action-resistance_hub.php
  src/Features/ActionsTaskType.php
Labels: Review, [Test Env] oberon

#2709 PLANET-7849: Refactor `header.js` file I
  assets/src/js/header.js
  assets/src/js/header/setupNavMenu.js
Labels: Review

#2710 PLANET-7849: Refactor `header.js` file II
  assets/src/js/app.js
  assets/src/js/header.js
  assets/src/js/header/setupAccessibleNavMenu.js
  assets/src/js/header/setupNavInteractions.js
  assets/src/js/header/setupNavMenu.js
  assets/src/js/header/setupTransparentNavHomepage.js
Labels: Review

#2705 PLANET-7608: Fix Quick Links layout issues on small screens
  assets/src/block-templates/quick-links/template.js
  assets/src/scss/base/_mixins.scss
  assets/src/scss/blocks/core-overrides/Columns.scss
  assets/src/scss/layout/_wide-blocks.scss
  src/Migrations/M056UpdateQuickLinksClassName.php
  src/Migrations/Utils/Constants.php
  src/Migrator.php
Labels: UAT Passed, [Test Env] pandora

#2708 PLANET-7865 Enable Load More functionality in Actions List
  assets/src/block-editor/QueryLoopBlockExtension/index.js
  assets/src/blocks/ActionsList/index.js
  assets/src/js/actions_list_clickable_cards.js
  assets/src/js/actions_list_load_more.js
  assets/src/js/app.js
  assets/src/scss/blocks/ActionsList/ActionsListEditorStyle.scss
  assets/src/scss/blocks/ActionsList/ActionsListStyle.scss
  assets/src/scss/components/_buttons.scss
  src/Blocks/QueryLoopExtension.php
  src/Migrations/M057ActionsListBlockLoadMore.php
  src/Migrations/Utils/Functions.php
  src/Migrator.php
Labels: Review, UAT Passed, [Test Env] janus
