Repository greenpeace/planet4-master-theme, pull requests merged in 2025-03, with the labels that each got.

#2550 Remove carousel autoplay
  assets/src/blocks/Covers/CoversCarouselLayout.js
  assets/src/js/query_loop_carousel.js
  src/MasterSite.php
Labels: Review, [Test Env] janus

#2548 Add mixin for focus styles
  assets/src/scss/base/_mixins.scss
  assets/src/scss/base/_typography.scss
  assets/src/scss/layout/_country-selector.scss
  assets/src/scss/layout/_forms.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_search.scss
Labels: Review, [Test Env] jupiter

#2538 PLANET-7613: Track content created
  src/Api/Tracking.php
Labels: Review, UAT Needed, [Test Env] phoebe

#2557 PLANET-7780 Update Posts List block Handbook link
  assets/src/block-editor/QueryLoopBlockExtension/index.js
Labels: Review, [Test Env] deimos

#2559 Fix tag redirect functionality
  tag.php
Labels: Review, [Test Env] umbriel

#2560 PLANET-7769 Remove PageHeader box-shadow
  assets/src/scss/blocks/PageHeader.scss
Labels: Review, [Test Env] janus

#2552 Fix more focused states
  assets/src/scss/base/_mixins.scss
  assets/src/scss/base/_variables.scss
  assets/src/scss/blocks/Gallery/styles/GalleryCarousel.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/pages/_listing-page.scss
  assets/src/scss/pages/post/_author-block.scss
  assets/src/scss/pages/search/_search-bar.scss
  images/cross-circle.svg
  templates/listing-page.twig
Labels: Review, [Test Env] saturn

#2555 PLANET-7702: Add Actions List Block CTA text for Screen Reader
  assets/src/block-editor/Sidebar/ActionSidebar.js
  src/ActionPage.php
  src/Blocks/ActionButtonText.php
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] neptune

#2553 PLANET-7756: Navigation Menu: fix accessibility issues on mobile
  assets/src/js/accessible_nav_menu.js
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
  assets/src/scss/layout/navbar/mobile.scss
  templates/burger-menu.twig
Labels: Review, UAT Passed, [Test Env] oberon

#2562 PLANET-7783: Fixed issue with the main navigation arrows
  assets/src/scss/layout/_navbar.scss
  templates/desktop-menu.twig
Labels: Review, [Test Env] tavros

#2561 PLANET-7782 & PLANET-7738 Improve comments form
  assets/src/scss/layout/_forms.scss
  assets/src/scss/pages/post/_comments-block.scss
  assets/src/scss/pages/post/_comments-form.scss
Labels: Review, UAT Passed, [Test Env] jupiter

#2565 PLANET-7603 Add an option to change TAB heading size
  assets/src/blocks/TakeActionBoxout/HeadingFontSizes.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
  src/Blocks/TakeActionBoxout.php
  templates/blocks/take-action-boxout.twig
Labels: Review, UAT Passed, [Test Env] sinope

#2569 PLANET-7786: Fix failing Audio & Video e2e test
  tests/e2e/blocks/audio-video.spec.js
Labels: Review, [Test Env] saturn

#2568 PLANET-7752 Make Table Of Contents content links by default
  assets/src/blocks/TableOfContents/TableOfContentsBlock.js
  assets/src/blocks/TableOfContents/TableOfContentsEditor.js
  src/Blocks/TableOfContents.php
Labels: Review, UAT Passed, [Test Env] janus

#2554 PLANET-7749 Add Bluesky share button
  assets/src/scss/base/_colors.scss
  assets/src/scss/components/_share-buttons.scss
  src/GravityFormsExtensions.php
  src/Post.php
  src/Settings.php
  templates/blocks/share_buttons.twig
Labels: Review, UAT Passed, [Test Env] titan

#2567 PLANET-7716: Make the layout toggle button operable by screen readers
  templates/listing-page.twig
Labels: Review, UAT Passed, [Test Env] umbriel

#2571 Fix error with GTM and Google Consent Mode
  src/EnqueueController.php
Labels: Review, UAT Passed, [Test Env] proteus

#2546 Set server_name tag for Sentry logging
  functions.php
Labels: Review, [Test Env] venus

#2504 PLANET-7707: Upgrade to NodeJS v20
  .circleci/config.yml
  package-lock.json
  package.json
Labels: Review, [Test Env] jupiter

#2573 Fix issues notified by Sentry
  src/MediaReplacer.php
  src/Post.php
  src/Sitemap.php
  tag.php
Labels: Review, [Test Env] tavros

#2572 PLANET-7718 Improve search page accessibility
  assets/src/scss/pages/search/_sort-filter.scss
  templates/base.twig
  templates/search.twig
  templates/search/action_types.twig
  templates/search/categories.twig
  templates/search/content_types.twig
  templates/search/post_types.twig
Labels: Review, UAT Needed, [Test Env] oberon

#2577 Update package-lock.json file
  package-lock.json
Labels: [Test Env] neptune

#2581 PLANET-7546 Increase Page Header title limit on mobile
  assets/src/scss/blocks/PageHeader.scss
Labels: Review, [Test Env] proteus
