Repository greenpeace/planet4-master-theme, pull requests merged in 2025-06, with the labels that each got.

#2637 PLANET-7817 Enable core Cover block
  src/BlockSettings.php
Labels: Review, UAT Passed, [Test Env] telesto

#2643 PLANET-7810 Fix notice(Theme translations are loaded too early)
  src/MasterSite.php
Labels: Review, [Test Env] jupiter

#2648 PLANET-7832: Refactor `QueryLoopExtension` class
  src/Blocks/QueryLoopExtension.php
Labels: Review

#2645 PLANET-7812 Move See All Posts link under the list
  assets/src/scss/blocks/PostsList/PostsListStyle.scss
  src/Post.php
Labels: Review, UAT Passed, [Test Env] pluto

#2653 PLANET-7840 Enabled Greenpeace Media on Cover block
  admin/css/archive-picker.css
  assets/src/js/Components/ArchivePicker/ArchivePicker.js
  assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
Labels: Review, UAT Passed, [Test Env] proteus

#2636 PLANET-7579: Migrate Covers Take Action block to Actions List block
  assets/src/block-templates/action/template.js
  assets/src/block-templates/campaign/template.js
  assets/src/block-templates/deep-dive-topic/template.js
  assets/src/block-templates/high-level-topic/template.js
  assets/src/block-templates/homepage/template.js
  assets/src/block-templates/take-action/template.js
  assets/src/blocks/ActionsList/index.js
  assets/src/editorIndex.js
  src/Migrations/M049MigrateCoversBlockToActionsListBlock.php
  src/Migrations/Utils/Constants.php
  src/Migrations/Utils/Functions.php
  src/Migrator.php
Labels: Review, UAT Passed, [Test Env] neptune

#2632 PLANET-7809 Show tags on Posts List list layout
  assets/src/blocks/PostsList/index.js
  assets/src/scss/base/_mixins.scss
  assets/src/scss/blocks/PostsList/PostsListStyle.scss
  assets/src/scss/pages/_listing-page.scss
  parts/action/query-listing-page.html
  parts/query-listing-page.html
  src/Migrations/M050AddTagsBackInPostsListBlock.php
  src/Migrator.php
  src/Post.php
Labels: Review, UAT Passed, [Test Env] pandora

#2638 PLANET-7579: Remove Covers block
  assets/src/block-editor/PostSelector/index.js
  assets/src/blocks/Covers/Covers.js
  assets/src/blocks/Covers/CoversBlock.js
  assets/src/blocks/Covers/CoversCarouselLayout.js
  assets/src/blocks/Covers/CoversConstants.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/CoversFrontend.js
  assets/src/blocks/Covers/CoversGridLoadMoreButton.js
  assets/src/blocks/Covers/CoversImagePlaceholder.js
  assets/src/blocks/Covers/CoversScript.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Covers/deprecated/coversV1.js
  assets/src/blocks/Covers/deprecated/coversV2.js
  assets/src/blocks/Covers/deprecated/coversV3.js
  assets/src/blocks/Covers/example.js
  assets/src/blocks/Covers/imageSizes.js
  assets/src/blocks/Covers/useCovers.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Covers/CoversEditorStyle.scss
  assets/src/scss/blocks/Covers/CoversStyle.scss
  assets/src/scss/blocks/Covers/layouts/CoversCarouselLayout.scss
  assets/src/scss/blocks/Covers/layouts/CoversGridLayout.scss
  assets/src/scss/blocks/Covers/styles/TakeActionCovers.scss
  assets/src/scss/editorStyle.scss
  src/BlockSettings.php
  src/Blocks/Covers.php
  src/Loader.php
  tests/e2e/tools/lib/covers.js
  webpack.config.js
Labels: Review

#2662 Replace a fallback solution for loading a language files
  src/MasterSite.php
Labels: Review, [Test Env] phoebe

#2663 PLANET-7848: Fix the error "undefined array key `post__in`"
  src/Blocks/QueryLoopExtension.php
Labels: Review, [Test Env] telesto

#2659 PLANET-7698 GP Media works in Topic Link block
  assets/src/js/Components/ArchivePicker/ArchivePicker.js
  assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
Labels: Review, [Test Env] janus
