Repository greenpeace/planet4-master-theme, pull requests merged in 2025-02, with the labels that each got.

#2499 PLANET-7731 Add JS strings translation support for blocks plugin strings
  src/MasterBlocks.php
Labels: Review, [Test Env] deimos

#2498 PLANET-7691 Upgrade Playwright to latest version
  .circleci/config.yml
  package-lock.json
  package.json
  tests/e2e/blocks-report-api.spec.js
  tests/e2e/blocks/articles.spec.js
  tests/e2e/blocks/carousel-header.spec.js
  tests/e2e/blocks/columns-icons.spec.js
  tests/e2e/blocks/columns-images.spec.js
  tests/e2e/blocks/columns-no-image.spec.js
  tests/e2e/blocks/columns-tasks.spec.js
  tests/e2e/blocks/covers-take-action.spec.js
  tests/e2e/blocks/related-posts.spec.js
  tests/e2e/gravity-forms.spec.js
  tests/e2e/page-layouts-modal.spec.js
  tests/e2e/related-posts.spec.js
  tests/e2e/tools/lib/columns.js
  tests/e2e/tools/lib/covers.js
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/gravity-forms.js
  tests/e2e/tools/lib/post.js
  tests/e2e/tools/php-errors.test.js
Labels: Review, [Test Env] leda

#2447 PLANET-7633 Add e2e tests for Audio and Video blocks
  tests/e2e/blocks/audio-video.spec.js
Labels: Review, [Test Env] saturn

#2509 PLANET-7736: Move JS scripts away from PHP files
  assets/src/js/bulk_export.js
  assets/src/js/dismiss_dashboard_notice.js
  assets/src/js/filter_block_names.js
  assets/src/js/media_import_button.js
  assets/src/js/metabox_search.js
  src/BlockReportSearch/Block/BlockUsageTable.php
  src/EnqueueController.php
  src/Exporter.php
  src/MasterSite.php
  webpack.config.js
Labels: Review, [Test Env] rhea

#2515 PLANET-7681 Make existing social share buttons configurable
  admin/css/options.css
  src/GravityFormsExtensions.php
  src/Migrations/M039EnableNewSocialSharePlatforms.php
  src/Migrator.php
  src/Post.php
  src/Settings.php
  templates/blocks/header.twig
  templates/blocks/share_buttons.twig
  templates/single-attachment.twig
  templates/single.twig
Labels: Review, UAT Passed, [Test Env] sinope

#2508 PLANET-7732 Add an e2e test for the Posts List block (list layout)
  tests/e2e/blocks/posts-list.spec.js
Labels: Review, [Test Env] oberon

#2524 PLANET-7514 Update manual override text
  assets/src/block-editor/QueryLoopBlockExtension/index.js
Labels: Review, [Test Env] phoebe

#2528 PLANET-7436 Added search_results to DLV
  assets/src/js/google_tag_manager.js
  src/EnqueueController.php
Labels: Review, [Test Env] umbriel

#2527 PLANET-7754 Fix P4 sidebar panel disappear issue
  assets/src/editorIndex.js
Labels: Review, [Test Env] nix

#2532 PLANET-7706 Keep News & Stories page layout when reloading/filtering
  assets/src/js/listing_pages.js
  src/ListingPage.php
  templates/listing-page.twig
Labels: Review, [Test Env] titan

#2529 Replace special characters in the content of the posts
  src/Migrations/M040ReplaceSpecialCharactersInPostsContent.php
  src/Migrator.php
Labels: Review, [Test Env] deimos

#2535 PLANET-7761 Add new Portugal website to NRO footer selector
  templates/countries.json
Labels: Review, [Test Env] sinope

#2530 PLANET-7711 Updated Author link text
  assets/src/scss/pages/post/_author-block.scss
Labels: Review, UAT Passed, [Test Env] venus

#2534 PLANET-7715 Made skip links more visible
  assets/src/scss/components/_skip-links.scss
Labels: Review, UAT Passed, [Test Env] rhea

#2531 PLANET-7612: Track user logins
  functions.php
  src/Api/Tracking.php
Labels: Review, UAT Passed, [Test Env] jupiter

#2539 PLANET-7764 Fixed Author override update
  functions.php
Labels: Review, [Test Env] umbriel

#2523 PLANET-7645: Implement image replacement feature
  admin/js/media_replacer.js
  src/MediaReplacer.php
Labels: Review, [Test Env] janus

#2541 PLANET-7755 Add option for applying social share settings to Posts an…
  src/GravityFormsExtensions.php
  src/Migrations/M041SetDefaultSocialSharingOption.php
  src/Migrator.php
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] saturn

#2543 PLANET-7703 Fix country selector close button focus ring
  assets/src/scss/layout/_country-selector.scss
  templates/footer_country_selector.twig
Labels: Review, UAT Passed, [Test Env] titan

#2525 PLANET-7744 Fix Media & Text padding in large screens
  assets/src/scss/blocks/core-overrides/MediaText.scss
Labels: Review, UAT Passed, [Test Env] neptune

#2533 PLANET-7701: Fix main nav menu accessibility issues
  assets/src/js/accessible_nav_menu.js
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_search.scss
  src/EnqueueController.php
  templates/desktop-menu.twig
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] oberon

#2490 PLANET-7714 Fix Sentry errors
  src/GravityFormsExtensions.php
  tag.php
Labels: Review, [Test Env] proteus

#2536 PLANET-7741 Fixed ErrorException
  src/Post.php
Labels: Review, [Test Env] pluto

#2544 PLANET-7775 Add same favicon but with better resolution
  favicon.ico
Labels: Review, [Test Env] deimos

#2545 PLANET-7773: Fix error in the `toggleCommentSubmit` script
  assets/src/js/toggle_comment_submit.js
Labels: Review, [Test Env] sinope
