Repository greenpeace/planet4-master-theme, pull requests merged in 2025-04, with the labels that each got.

#2487 PLANET-7676 Added snippet for VWO Anti Flickering
  assets/src/js/vwo_smart_code.js
  src/EnqueueController.php
  src/HttpHeaders.php
  src/MasterSite.php
  src/Settings.php
  templates/html-header.twig
  webpack.config.js
Labels: Review, UAT Passed

#2582 PLANET-7793 Force WP to use UTC date for upload paths
  src/MasterSite.php
Labels: Review, [Test Env] atlas

#2556 PLANET-7762 Fixed Posts list layout and made links clickable
  assets/src/blocks/PostsList/index.js
  assets/src/scss/blocks/PostsList/PostsListEditorStyle.scss
  assets/src/scss/blocks/PostsList/PostsListStyle.scss
  src/Migrations/M042FixPostsListMigration.php
  src/Migrator.php
  src/Post.php
Labels: Review, [Test Env] pluto

#2579 Fix error in the core Image block
  assets/src/block-editor/BlockFilters/index.js
  assets/src/scss/blocks/core-overrides/Image.scss
  src/Migrations/M043SwitchClassesInImageBlock.php
  src/Migrations/Utils/Constants.php
  src/Migrator.php
Labels: Review, [Test Env] titan

#2563 PLANET-7772 Made listing page layout switch dynamic
  assets/src/js/app.js
  assets/src/js/listing_pages.js
  assets/src/scss/pages/_listing-page.scss
  images/grid-view.svg
  images/list-view.svg
  src/EnqueueController.php
  src/ListingPage.php
  templates/listing-page.twig
  webpack.config.js
Labels: Review, [Test Env] deimos, PoC

#2580 PLANET-7483 Use padding instead of line height for buttons
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
Labels: Review, UAT Needed, [Test Env] janus

#2583 Align main Greenpeace logo
  assets/src/scss/layout/navbar/_site-logo.scss
Labels: Review, [Test Env] jupiter

#2586 Add scss support for stylelint
  .circleci/config.yml
  .stylelintrc
  assets/src/scss/base/_icons.scss
  assets/src/scss/base/_typography.scss
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Accordion/AccordionStyle.scss
  assets/src/scss/blocks/Columns/ColumnsStyle.scss
  assets/src/scss/blocks/PostsList/PostsListStyle.scss
  assets/src/scss/blocks/TopicLink/TopicLinkStyle.scss
  assets/src/scss/blocks/core-overrides/Heading.scss
  assets/src/scss/layout/_navbar.scss
  assets/src/scss/layout/navbar/_burger-menu.scss
  assets/src/scss/layout/navbar/languages.scss
  assets/src/scss/pages/_listing-page.scss
  assets/src/scss/pages/post/_author-block.scss
  assets/src/scss/vendors/photoswipe/main.scss
  assets/src/scss/vendors/photoswipe/p4-skin.scss
  package-lock.json
  package.json
Labels: Review, [Test Env] saturn

#2585 Add husky pre-commit hook
  .githooks/prepare-commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
Labels: Review, [Test Env] tavros

#2584 PLANET-7659 Hide empty restrictions text field in media library
  src/MasterSite.php
Labels: Review, [Test Env] venus

#2591 PLANET-7796: Pass the variable `cf_local_project` to GTM
  src/EnqueueController.php
Labels: Review, [Test Env] oberon

#2592 PLANET-7101: Lightbox shows all images for Gallery 3 columns style
  src/Blocks/Gallery.php
Labels: Review, [Test Env] neptune

#2593 Fix VWO script
  assets/src/js/vwo_smart_code.js
  src/HttpHeaders.php
  src/MasterSite.php
Labels: Review, [Test Env] telesto

#2590 PLANET-7034: Show empty columns in the P4 Columns block
  src/Blocks/Columns.php
Labels: Review, UAT Passed, [Test Env] phoebe

#2598 PLANET-7686: Hide WP-Stateless admin notices
  admin/css/dashboard.css
Labels: Review, [Test Env] jupiter

#2597 Update Counter block layout
  assets/src/scss/blocks/Counter/CounterStyle.scss
Labels: UAT Passed, [Test Env] pluto

#2605 Fix layout toggle size
  assets/src/scss/pages/_listing-page.scss
Labels: Review, [Test Env] proteus

#2596 PLANET-7483 Use padding instead of line height for buttons
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/scss/blocks/Accordion/AccordionStyle.scss
  assets/src/scss/blocks/Covers/styles/TakeActionCovers.scss
  assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
  assets/src/scss/components/_buttons.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/layout/_cookies-settings.scss
  assets/src/scss/layout/_cookies.scss
  assets/src/scss/layout/navbar/_search.scss
  assets/src/scss/pages/post/_comments-block.scss
  assets/src/scss/pages/search/_filter-sidebar.scss
  assets/src/scss/pages/search/_search-bar.scss
  templates/cookies.twig
  templates/cookies/cookies_settings.twig
  templates/single.twig
Labels: Review, UAT Passed

#2600 PLANET-7791: Create `url_passthrough` setting
  assets/src/js/google_tag_manager.js
  src/EnqueueController.php
  src/MasterSite.php
  src/Migrations/M044SetDefaultUrlPassthroughOption.php
  src/Migrator.php
  src/Settings.php
Labels: Review, UAT Passed, [Test Env] tavros

#2608 Fix Gallery warning issue
  src/Blocks/Gallery.php
Labels: Review, [Test Env] telesto

#2594 PLANET-7745: Adjust taxonomy breadcrumbs in Actions/Posts List blocks
  assets/src/block-editor/QueryLoopBlockExtension/index.js
  assets/src/block-editor/setupTaxonomyBreadcrumbBlock.js
  assets/src/blocks/ActionsList/index.js
  assets/src/blocks/PostsList/index.js
  assets/src/editorIndex.js
  assets/src/scss/editorOverrides.scss
  functions.php
  parts/action/query-listing-page.html
  parts/query-listing-page.html
  src/Migrations/M045ReplaceTaxonomyInQueryBlock.php
  src/Migrations/Utils/Constants.php
  src/Migrations/Utils/Functions.php
  src/Migrator.php
  src/Post.php
Labels: Review, UAT Passed, [Test Env] atlas

#2609 PLANET-7803 Fix mobile tabs transition
  assets/src/scss/layout/navbar/mobile.scss
Labels: Review, UAT Passed, [Test Env] titan

#2491 PLANET-7511 Migrate Articles block to Posts List block
  assets/src/block-templates/deep-dive-topic/template.js
  assets/src/block-templates/get-informed/template.js
  assets/src/block-templates/high-level-topic/template.js
  assets/src/block-templates/homepage/template.js
  assets/src/block-templates/take-action/template.js
  assets/src/blocks/Articles/ArticlePreview.js
  assets/src/blocks/Articles/ArticlesBlock.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/Articles/ArticlesEditorScript.js
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/Articles/ArticlesList.js
  assets/src/blocks/Articles/ArticlesScript.js
  assets/src/blocks/Articles/imageSizes.js
  assets/src/blocks/Articles/useArticlesFetch.js
  assets/src/blocks/PostsList/index.js
  assets/src/blocks/TableOfContents/getHeadingsFromBlocks.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/Articles/ArticlesEditorStyle.scss
  assets/src/scss/blocks/Articles/ArticlesStyle.scss
  assets/src/scss/editorStyle.scss
  single.php
  src/BlockSettings.php
  src/Blocks/Articles.php
  src/Loader.php
  src/MetaboxRegister.php
  src/Migrations/M046MigrateArticlesBlockToPostsListBlock.php
  src/Migrations/Utils/Constants.php
  src/Migrations/Utils/Functions.php
  src/Migrator.php
  tests/e2e/blocks/articles.spec.js
  tests/e2e/related-posts.spec.js
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] mars
