Repository greenpeace/planet4-master-theme, pull requests merged in 2025-01, with the labels that each got.

#2473 Add translation text-domain for Blocks
  languages/blocks/planet4-blocks-backend-backup-202412031425460.pot~
  languages/blocks/planet4-blocks-backup-202412031424110.pot~
  languages/blocks/planet4-blocks-cs_CZ-backup-202412061513440.po~
  languages/blocks/planet4-blocks-da_DK-backup-202412041359500.po~
  languages/blocks/planet4-blocks-de_DE-backup-202412061518380.po~
  languages/blocks/planet4-blocks-el-backup-202412041357340.po~
  languages/blocks/planet4-blocks-es_MX-backup-202412061518520.po~
  languages/blocks/planet4-blocks-fi-backup-202412041401110.po~
  languages/blocks/planet4-blocks-fr_CA-backup-202412061518310.po~
  languages/blocks/planet4-blocks-fr_FR-backup-202412061514320.po~
  languages/blocks/planet4-blocks-he_IL-backup-202412041523550.po~
  languages/blocks/planet4-blocks-hr-backup-202412061518490.po~
  languages/blocks/planet4-blocks-hu_HU-backup-202412061515190.po~
  languages/blocks/planet4-blocks-it_IT-backup-202412061515470.po~
  languages/blocks/planet4-blocks-ja-backup-202412061519190.po~
  languages/blocks/planet4-blocks-nb_NO-backup-202412041401490.po~
  languages/blocks/planet4-blocks-nl_NL-backup-202412061516430.po~
  languages/blocks/planet4-blocks-pl_PL-backup-202412061514410.po~
  languages/blocks/planet4-blocks-pt_BR-backup-202412061518340.po~
  languages/blocks/planet4-blocks-ro_RO-backup-202412061515280.po~
  languages/blocks/planet4-blocks-sk_SK-backup-202412061518360.po~
  languages/blocks/planet4-blocks-sl_SI-backup-202412061514050.po~
  languages/blocks/planet4-blocks-sv_SE-backup-202412041400410.po~
  languages/blocks/planet4-blocks-tr_TR-backup-202412061518540.po~
  languages/blocks/planet4-blocks-uk-backup-202412061518590.po~
  src/MasterSite.php
Labels: Review, [Test Env] oberon

#2470 PLANET-6692: Create Topic Link Block
  assets/src/block-editor/setupBlockEditorValidation.js
  assets/src/blocks/TopicLink/TopicLinkBlock.js
  assets/src/blocks/TopicLink/TopicLinkEditor.js
  assets/src/blocks/TopicLink/TopicLinkFrontend.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/scss/blocks.scss
  assets/src/scss/blocks/TopicLink/TopicLinkStyle.scss
  src/BlockSettings.php
  src/Blocks/TopicLink.php
  src/Loader.php
Labels: Review, UAT Passed, [Test Env] pluto

#2489 PLANET-7646 Add placeholder image to Author block
  author.php
  images/p4-avatar.jpg
  src/MasterSite.php
  templates/author.twig
  templates/blocks/author_profile.twig
  templates/single.twig
Labels: Review, UAT Passed, [Test Env] tavros

#2497 PLANET-7729: Fix Carousel interval issue
  assets/src/blocks/Covers/CoversCarouselLayout.js
Labels: Review, [Test Env] saturn

#2501 Fix <ol> selector issue
  assets/src/scss/blocks/Covers/layouts/CoversCarouselLayout.scss
Labels: Review, [Test Env] phoebe

#2500 PLANET-7730 Fix bottom navigation block issue
  src/Post.php
Labels: Review

#2505 Move blocks API endpoints to their own PHP file
  functions.php
  src/Api/Articles.php
  src/Api/Covers.php
  src/Api/Gallery.php
  src/Api/SocialMedia.php
  src/Blocks/Articles.php
  src/Blocks/Covers.php
  src/Blocks/Gallery.php
  src/Blocks/HappyPoint.php
  src/Blocks/SocialMedia.php
Labels: Review, [Test Env] jupiter

#2493 PLANET-7489: Check number of columns in the P4 columns block
  src/BlockReportSearch/Block/BlockUsageTable.php
Labels: Review

#2507 PLANET-7647 Enforce consistency on default favicon
  src/MasterSite.php
  src/Migrations/M038RemoveCustomSiteIcon.php
  src/Migrator.php
Labels: Review, [Test Env] tavros

#2502 PLANET-7625: Move JS scripts away from Twig templates
  assets/src/js/hubspot_cookie.js
  assets/src/js/share_buttons.js
  assets/src/js/toggle_comment_submit.js
  src/EnqueueController.php
  src/GravityFormsExtensions.php
  src/Loader.php
  templates/blocks/share_buttons.twig
  templates/comment_form/submit_button.twig
  templates/head/hubspot.twig
  templates/html-header.twig
  webpack.config.js
Labels: Review, [Test Env] nix

#2512 Follow up Carousel issues
  assets/src/js/query_loop_carousel.js
  assets/src/scss/layout/_query-loop-overrides.scss
Labels: Review, [Test Env] saturn

#2483 PLANET-7635 Move remaining code from plugin
  assets/src/block-editor/AssignOnlyFlatTermSelector/index.js
  assets/src/block-editor/BlockFilters/index.js
  assets/src/block-editor/TermSelector/index.js
  assets/src/block-editor/addButtonLinkPasteWarning.js
  assets/src/block-editor/replaceTaxonomyTermSelectors.js
  assets/src/block-editor/saveMetaToPreview.js
  assets/src/block-editor/setupImageBlockExtension.js
  assets/src/block-templates/readme.md
  assets/src/block-templates/register.js
  assets/src/blocks/Articles/frontendRendered.js
  assets/src/blocks/components/Parallax/setupParallax.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/js/app.js
  assets/src/js/cookies.js
  assets/src/scss/blocks/TableOfContents/TableOfContentsEditorStyle.scss
  assets/src/scss/components/_character-counter.scss
  assets/src/scss/editorOverrides.scss
  assets/src/scss/editorStyle.scss
  functions.php
  src/Api/AnalyticsValues.php
  src/Blocks/BaseBlock.php
  src/Blocks/HappyPoint.php
  src/BreakpointsImageSizes.php
  src/Controllers/Menu/ArchiveImport.php
  src/Loader.php
  src/MasterBlocks.php
  src/MasterSite.php
  src/QueryLoopPagination.php
  tests/e2e/cookies-banner.spec.js
  tests/p4-testcase.php
Labels: Review, [Test Env] umbriel

#2503 PLANET-7625: Move Google Tag Manager scripts away from Twig templates
  404.php
  archive.php
  assets/src/js/google_tag_manager.js
  author.php
  index.php
  page-templates/evergreen.php
  page-templates/sitemap.php
  page.php
  single-attachment.php
  single-campaign.php
  single-p4_action.php
  single.php
  src/EnqueueController.php
  src/ListingPage.php
  src/Search/SearchPage.php
  templates/blocks/google_tag_manager.twig
  templates/html-header.twig
  webpack.config.js
Labels: Review, UAT Passed

#2510 PLANET-7578: Improve Migration Script M037
  src/Migrations/M037MigrateCoversContentBlockToPostsListBlock.php
  src/Migrations/Utils/Functions.php
Labels: Review
