Repository greenpeace/planet4-master-theme, pull requests merged in 2025-07, with the labels that each got.

#2669 PLANET-7828: Add Task Type field
  assets/src/block-editor/Sidebar/ActionSidebar.js
  src/ActionPage.php
  src/Features/ActionsTaskType.php
  src/Settings/Features.php
Labels: Review, UAT Passed, [Test Env] pandora

#2670 PLANET-7841: Add Action Deadline field
  assets/src/block-editor/Sidebar/ActionSidebar.js
  assets/src/block-editor/SidebarFields/DatePickerSidebarField.js
  src/ActionPage.php
  src/Features/ActionsDeadline.php
  src/Settings/Features.php
Labels: Review, UAT Passed, [Test Env] proteus

#2675 Skip the M051 migration from execution
  admin/css/options.css
  src/DevReport.php
  src/Loader.php
  src/MigrationStatus.php
  src/Migrations/M051ReplaceSpecialCharactersInPostsContent.php
  src/Migrator.php
Labels: Review, [Test Env] phoebe

#2680 Log errors during the migration process
  src/Migrations/M046MigrateArticlesBlockToPostsListBlock.php
  src/Migrations/M049MigrateCoversBlockToActionsListBlock.php
  src/Migrations/Utils/Functions.php
Labels: [Test Env] umbriel

#2681 Fixes in the `MediaReplacer` class
  admin/js/media_replacer.js
  src/Loader.php
  src/MediaReplacer.php
Labels: Review, [Test Env] venus

#2672 PLANET-7857 Adjust See All link based on taxonomy filters
  assets/src/block-editor/QueryLoopBlockExtension/index.js
Labels: Review, UAT Passed

#2641 PLANET-7793 Revert fix added in 2582 PR
  src/MasterSite.php
Labels: Review

#2685 PLANET-7872 Fix missing image dimensions in Library upload
  src/AttachmentsController.php
Labels: Review, [Test Env] rhea

#2660 PLANET-7829 Enable Footnotes block
  index.php
  page-templates/evergreen.php
  page.php
  single-campaign.php
  single-p4_action.php
  single.php
  src/BlockSettings.php
Labels: Review, UAT Passed, [Test Env] tavros

#2683 Reduce the length of the `MasterSite` class
  src/Loader.php
  src/MasterSite.php
  src/YouTubeHandler.php
Labels: Review, [Test Env] pandora

#2690 Move metabox search functionalities out of MasterSite.php
  src/MasterSite.php
  src/MetaboxRegister.php
Labels: Review, [Test Env] deimos

#2693 Remove mentions of navbar-search-toggle class
  assets/src/js/header.js
Labels: Review, [Test Env] venus

#2654 PLANET-7820: Research and shared solution(s) of XSS atack
  src/Search/Search.php
  templates/comment.twig
Labels: DO NOT MERGE, [Test Env] titan, PoC

#2697 Move close nav element functionality to separate file
  assets/src/js/header.js
  assets/src/js/header/setupCloseNavMenuButton.js
  templates/burger-menu.twig
Labels: Review, [Test Env] pandora

#2696 Move mobile tabs behaviour to separate file
  assets/src/js/header.js
  assets/src/js/header/setupMobileTabsMenuScroll.js
Labels: Review, [Test Env] jupiter

#2701 Move lock screen when nav open function to separate file
  assets/src/js/header.js
  assets/src/js/header/accessibleNavMenu.js
  assets/src/js/header/setupNavMenu.js
Labels: Review, [Test Env] rhea

#2703 Fix blank page when no posts are found
  assets/src/scss/pages/_listing-page.scss
  index.php
  page-templates/evergreen.php
  page.php
  single-campaign.php
  single-p4_action.php
  single.php
Labels: Review, [Test Env] tavros

#2698 Reduce the length of the `MasterSite` class II
  assets/src/scss/pages/post/_comments-form.scss
  src/CommentFormCustomizer.php
  src/Loader.php
  src/MasterSite.php
Labels: Review, [Test Env] proteus

#2706 PLANET-7890 Fix backend link to settings for News Stories page
  functions.php
Labels: Review, [Test Env] venus

#2707 PLANET-7849 Move toggleNavElement function to separate file
  assets/src/js/header.js
  assets/src/js/header/setupNavMenu.js
Labels: Review, [Test Env] mars
