Repository greenpeace/planet4-master-theme, pull requests merged in 2025-10, with the labels that each got.

#2759 PLANET-7649: Fix lightbox not using largest image
  assets/src/blocks/components/Lightbox/setupLightboxForImages.js
Labels: Review

#2766 Remove Hotjar tracking event
  assets/src/js/header/setupNavInteractions.js
Labels: Review, [Test Env] sinope

#2761 PLANET-7908 Fix weak authentication lockout threshold
  src/LoginHandler.php
Labels: Review, [Test Env] umbriel

#2756 PLANET-7937: Integrate Turnstile to comments form
  assets/src/js/toggle_comment_submit.js
  assets/src/js/turnstile_render.js
  single.php
  src/CloudflareTurnstileHandler.php
  src/EnqueueController.php
  src/Loader.php
  src/Settings/CloudflareTurnstile.php
  src/Settings/Features.php
  templates/comment_form/submit_button.twig
  tests/e2e/comments.spec.js
  webpack.config.js
Labels: Review, [Test Env] phoebe

#2280 PLANET-7390: Update to Timber 2.1
  404.php
  archive-p4_action.php
  archive.php
  author.php
  composer.json
  composer.lock
  functions.php
  index.php
  page-templates/evergreen.php
  page-templates/sitemap.php
  page.php
  phpcs.xml.dist
  search.php
  single-attachment.php
  single-campaign.php
  single-p4_action.php
  single.php
  src/Blocks/BaseBlock.php
  src/Context.php
  src/GravityFormsExtensions.php
  src/Loader.php
  src/MasterBlocks.php
  src/MasterSite.php
  src/Post.php
  src/PublicAssets.php
  src/Search/SearchPage.php
  src/TimberSettings.php
  src/User.php
  src/View/View.php
  tag.php
  taxonomy.php
  templates/author.twig
  templates/burger-menu-items.twig
  templates/desktop-menu.twig
  templates/html-header.twig
  templates/navigation-bar.twig
  templates/navigation-bar_min.twig
  templates/navigation-submenu.twig
  templates/tease-post.twig
  templates/tease.twig
  tests/bootstrap.php
  tests/test-category-page.php
  tests/test-open-graph.php
  tests/test-p4-master-theme.php
Labels: [Test Env] leda

#2618 PLANET-7712 Carousel Header: enhance keyboard navigation accessibility
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/CarouselHeader/CarouselControls.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/blocks/CarouselHeader/Slide.js
  assets/src/blocks/CarouselHeader/StaticCaption.js
  assets/src/blocks/CarouselHeader/useSlides.js
  assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss
  images/pause.svg
  images/play.svg
  package-lock.json
  src/Blocks/CarouselHeader.php
Labels: Review, UAT Passed, [Test Env] janus

#2768 PLANET-7460: Hide GF notification checkbox for attachments
  admin/css/gravity-forms-admin.css
  src/GravityFormsExtensions.php
Labels: Review
